/* Generated by Nim Compiler v1.4.4 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3   -I/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib -I/home/kyohei/nim/nmark/tests -o /home/kyohei/nim/nmark/nimcache/tests/testRegular.nim_0d61f8370cad1d412f80b84d143e1257/@m..@ssrc@snmarkpkg@sprivate@sdefBlock.nim.c.o /home/kyohei/nim/nmark/nimcache/tests/testRegular.nim_0d61f8370cad1d412f80b84d143e1257/@m..@ssrc@snmarkpkg@sprivate@sdefBlock.nim.c */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw;
typedef struct tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ;
typedef struct tySequence__ysZ0yvYJsxyGumT80SPhXQ tySequence__ysZ0yvYJsxyGumT80SPhXQ;
typedef struct tySequence__lBgZ7a89beZGYPl8PiANMTA tySequence__lBgZ7a89beZGYPl8PiANMTA;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;

/* section: NIM_merge_TYPES */
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tySet_tyEnum_RegexFlag__gA189bEOtGhLt2cCHGW4ywg;
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw {
NIM_BOOL flagBlockQuote;
NIM_BOOL flagIndentedCodeBlock;
NI indentedCodeBlockDepth;
NIM_BOOL flagFencedCodeBlockChar;
NIM_BOOL flagFencedCodeBlockTild;
NI openingFenceLength;
NI fencedCodeBlocksdepth;
NIM_BOOL flagHtmlBlock1;
NIM_BOOL flagHtmlBlock2;
NIM_BOOL flagHtmlBlock3;
NIM_BOOL flagHtmlBlock4;
NIM_BOOL flagHtmlBlock5;
NIM_BOOL flagHtmlBlock6;
NIM_BOOL flagHtmlBlock7;
NIM_BOOL flagLinkReference;
NIM_BOOL flagUnorderedList;
NIM_BOOL flagUnorderedListMarker;
NI uldepth;
NIM_BOOL flagOrderedList;
NIM_BOOL flagOrderedListMarker;
NI oldepth;
NIM_BOOL hasEmptyLine;
NIM_BOOL afterEmptyLine;
NIM_BOOL looseUnordered;
NIM_BOOL looseOrdered;
};
typedef NU8 tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q;
typedef NU8 tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ;
struct tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ {
tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q kind;
union{
struct {tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ containerType;
tySequence__ysZ0yvYJsxyGumT80SPhXQ* children;
} _kind_1;
struct {tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ leafType;
NimStringDesc* raw;
} _kind_2;
};
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (NIM_CHAR x, void* ClE_0);
void* ClE_0;
} tyProc__SL9a4kwASyzvPJy9bdobKVUw;
typedef N_CLOSURE_PTR(NIM_BOOL, TM__jIupzeCA9b9b1r5qjBNmoFLw_65) (NIM_CHAR x);
typedef N_CLOSURE_PTR(NIM_BOOL, TM__jIupzeCA9b9b1r5qjBNmoFLw_67) (NIM_CHAR x, void* ClE_0);
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];

/* section: NIM_merge_SEQ_TYPES */
struct tySequence__ysZ0yvYJsxyGumT80SPhXQ {
  TGenericSeq Sup;
  tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* data[SEQ_DECL_SIZE];
};
struct tySequence__lBgZ7a89beZGYPl8PiANMTA {
  TGenericSeq Sup;
  NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};

/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_2)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_LIB_PRIVATE N_NIMCALL(tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw*, re__BHdoI8AriYxT9bGXrX9c7EhQ)(NimStringDesc* s, tySet_tyEnum_RegexFlag__gA189bEOtGhLt2cCHGW4ywg flags);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__AT1eRuflKWyTTBdLjEDZbgsystem)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___dgYAo7RfdUVVpvkfKDym8w_2system)(NI x, NI y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem)(void* usr);
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y);
static N_INLINE(void, decRef__AT1eRuflKWyTTBdLjEDZbg_2system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NIM_BOOL, ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_3system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__Y66tOYFjgwJ0k4aLz4bc0Q)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_4)(void);
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_6)(void);
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_8)(void);
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_10)(void);
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_12)(void);
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_14)(void);
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_16)(void);
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_18)(void);
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_20)(void);
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_22)(void);
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_24)(void);
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_26)(void);
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_28)(void);
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_30)(void);
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_32)(void);
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_34)(void);
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_36)(void);
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_38)(void);
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_40)(void);
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_42)(void);
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_44)(void);
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_46)(void);
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_48)(void);
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_50)(void);
static N_NIMCALL(void, Marker_tyRef__QKxGI1JtsfnFT0BOgq4LIA)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A)(NimStringDesc* msg);
static N_INLINE(NIM_BOOL, match__ATpcLUBGRWa2duwyoHgYLAre)(NimStringDesc* s, tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start);
static N_INLINE(NI, matchLen__vylpKAr9bdsSOgr8tMJwQ6wre)(NCSTRING buf, tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start, NI bufSize);
N_LIB_PRIVATE N_NIMCALL(int, matchOrFind__jpcUBS27e6bot0QabDwvkw)(NCSTRING buf, tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start, NI bufSize, int flags);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s);
static N_NIMCALL(void, Marker_tySequence__ysZ0yvYJsxyGumT80SPhXQ)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef__f8fGmzFqIDQtrEPBlkxIhw)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tySequence__lBgZ7a89beZGYPl8PiANMTA*, filter__3Uw65OIODxq9c01vSfAJhpgsequtils)(NIM_CHAR* s, NI sLen_0, tyProc__SL9a4kwASyzvPJy9bdobKVUw pred);
N_LIB_PRIVATE N_NIMCALL(tySequence__lBgZ7a89beZGYPl8PiANMTA*, newSeq__3jwSUBwo3nEjaheBcZzckg)(NI len);
N_LIB_PRIVATE N_NIMCALL(TGenericSeq*, incrSeqV3)(TGenericSeq* s, TNimType* typ);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, colonanonymous___Hhd0KV9cyGTuKcEOHJRGTww)(NIM_CHAR x);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ*, nsuSplitWhitespace)(NimStringDesc* s, NI maxsplit);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem__9bGgqEk7RXXl6eqM9c1HdELAsystem)(void* a, void* b, NI size);
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuStrip)(NimStringDesc* s, NIM_BOOL leading, NIM_BOOL trailing, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars);

/* section: NIM_merge_DATA */
extern TNimType NTI__dkhOdInu11QXB2HnNpgmJQ_;
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_3, "^ {0,3}(\\*{3,}|-{3,}|_{3,})$", 28);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_5, "^ {0,3}(=+)$", 12);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_7, "^ {0,3}(-{3,}) *$", 17);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_9, "^ {0,3}(#{1,6}) ", 16);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_11, "^(#{1,6})$", 10);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_13, "^ {0,3}> {0,1}", 14);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_15, "^ {0,3}(-|\\+|\\*) +", 18);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_17, "^ {0,3}[0-9]{1,9}(\\.|\\)) +", 26);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_19, "^ {4,}\\S", 8);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_21, "^ {0,3}\\S", 9);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_23, "^ {0,3}`{3,}\\S*$", 16);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_25, "^ {0,3}~{3,}\\S*$", 16);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_27, "(^(<script|<pre|<style)( |>|\\n))", 32);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_29, "(</script>|</pre>|</style>)", 27);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_31, "^<!--", 5);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_33, "-->", 3);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_35, "^<\\\?", 4);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_37, "\\\?>", 3);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_39, "^<![A-Z]", 8);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_41, ">", 1);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_43, "^<!\\[CDATA\\[", 12);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_45, "\\]\\]>", 5);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_47, "^(<|</)(address|article|aside|base|basefont|blockquote|body|cap"
"tion|center|col|colgroup|dd|details|dialog|dir|div|dl|dt|fieldse"
"t|figcaption|figure|footer|form|frame|frameset|h1|h2|h3|h4|h5|h6"
"|head|header|hr|html|iframe|legend|li|link|main|menu|menuitem|na"
"v|noframes|ol|optgroup|option|p|param|section|source|summary|tab"
"le|tbody|td|tfoot|th|thead|title|tr|track|ul)( |\\n|>|/>)", 375);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_49, "^<.*> *$", 8);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_51, "&[a-zA-Z0-9#]+;", 15);
N_LIB_PRIVATE TNimType NTI__QNb1YaizAryqcc2cKZsuyw_;
extern TNimType NTI__VaVACK0bpYmqIQ0mKcHfQQ_;
extern TNimType NTI__rR5Bzr1D5krxoo1NcNyeMA_;
N_LIB_PRIVATE TNimType NTI__QKxGI1JtsfnFT0BOgq4LIA_;
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_55, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim(222, 11) `len(a) == L` the length of the string changed w"
"hile iterating over it", 149);
N_LIB_PRIVATE TNimType NTI__Aao0goirPrklcSrQBcoeNQ_;
N_LIB_PRIVATE TNimType NTI__ipIjlgDkqbVTHr4JvmL47Q_;
TNimNode* NimDT___Aao0goirPrklcSrQBcoeNQ_kind[3];
N_LIB_PRIVATE TNimType NTI__f0C73Dxca1VbNsCJ9bxzvzQ_;
N_LIB_PRIVATE TNimType NTI__ysZ0yvYJsxyGumT80SPhXQ_;
extern TNimType NTI__77mFvmsOLKik79ci2hXkHEg_;
N_LIB_PRIVATE TNimType NTI__f8fGmzFqIDQtrEPBlkxIhw_;
extern TNimType NTI__lBgZ7a89beZGYPl8PiANMTA_;
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_68, "#", 1);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_69, "##", 2);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_70, "###", 3);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_71, "####", 4);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_72, "#####", 5);
STRING_LITERAL(TM__jIupzeCA9b9b1r5qjBNmoFLw_73, "######", 6);
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__jIupzeCA9b9b1r5qjBNmoFLw_74 = {
0x00, 0x00, 0x00, 0x00, 0x09, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;

/* section: NIM_merge_VARS */
N_LIB_PRIVATE tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* reThematicBreak__exGX706CkNVB7PBj71hg8Q;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__IcYaEuuWivYAS86vFMTS3Q;
N_LIB_PRIVATE tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* reSetextHeader1__jT0jZW9aoPJMKKxZ9a8luXNA;
N_LIB_PRIVATE tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* reBreakOrHeader__4bZZeaPoLKeXUaSS8KnqYw;
N_LIB_PRIVATE tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* reAtxHeader__GEr9bOIeUjEh09bzJD5FNvbw;
N_LIB_PRIVATE tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* reAnotherAtxHeader__ANfVU9bSju6anGNZNzSNUpA;
N_LIB_PRIVATE tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* reBlockQuote__JSbt8gQbosjOEdEj3Yz6qA;
N_LIB_PRIVATE tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* reUnorderedList__gnzB2GavH0mSSo4dnS9bJgQ;
N_LIB_PRIVATE tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* reOrderedList__OkYoHIkPoNM9bQjLi0h9ck5w;
N_LIB_PRIVATE tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* reIndentedCodeBlock__lgsdCjdVvq5rkUZ0oA4gxw;
N_LIB_PRIVATE tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* reBreakIndentedCode__M9bs8fT9cKQgQccoWZepAGZw;
N_LIB_PRIVATE tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* reFencedCodeBlockChar__qY9b0H3XeBMX9cBVHo7lMWeQ;
N_LIB_PRIVATE tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* reFencedCodeBlockTild__drHzwdPzIUdhxrgV2t0CZQ;
N_LIB_PRIVATE tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* reHtmlBlock1Begins__F0gzXWGKKtRyRjghcFi9b9bA;
N_LIB_PRIVATE tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* reHtmlBlock1Ends__DXwyl5igweZ9bPfP7H9c51zA;
N_LIB_PRIVATE tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* reHtmlBlock2Begins__ULdIaxWu22t25A9ciqyg2yg;
N_LIB_PRIVATE tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* reHtmlBlock2Ends__VDsIOHZCk3SoRk9acLtHIyQ;
N_LIB_PRIVATE tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* reHtmlBlock3Begins__pt9afGK6sTWS9b9cMAArUkljA;
N_LIB_PRIVATE tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* reHtmlBlock3Ends__VGcPVYopHc6DDK1hCUXrfQ;
N_LIB_PRIVATE tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* reHtmlBlock4Begins__e5VtUseEsuWaYCsA1wVvzA;
N_LIB_PRIVATE tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* reHtmlBlock4Ends__T7N0cyb7wE2J5t5UiJTemQ;
N_LIB_PRIVATE tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* reHtmlBlock5Begins__CmcKmVUi4Wn8CtIQXkYoQg;
N_LIB_PRIVATE tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* reHtmlBlock5Ends__3bR6i0nYCARckeg2FvxbhA;
N_LIB_PRIVATE tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* reHtmlBlock6Begins__SpfOp30e4hcOVn3aGXtApQ;
N_LIB_PRIVATE tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* reHtmlBlock7Begins__f0K9budy9bkRZHtiN2zjdA9cQ;
N_LIB_PRIVATE tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* reEntity__85u1ODpkOOUfYR1n113FPw;

/* section: NIM_merge_PROCS */
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_2)(void) {
	nimGCvisit((void*)reThematicBreak__exGX706CkNVB7PBj71hg8Q, 0);
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
static N_INLINE(NI, pluspercent___dgYAo7RfdUVVpvkfKDym8w_2system)(NI x, NI y) {
	NI result;
	nimfr_("+%", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/arithme"
"tics.nim");
	result = (NI)0;
	nimln_(426, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/arithme"
"tics.nim");
	nimln_(430, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/arithme"
"tics.nim");
	result = ((NI) ((NU)((NU64)(((NU) (x))) + (NU64)(((NU) (y))))));
	popFrame();
	return result;
}
static N_INLINE(void, incRef__AT1eRuflKWyTTBdLjEDZbgsystem)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	nimln_(184, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	(*c).refcount = pluspercent___dgYAo7RfdUVVpvkfKDym8w_2system((*c).refcount, ((NI) 8));
	popFrame();
}
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y) {
	NI result;
	nimfr_("-%", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/arithme"
"tics.nim");
	result = (NI)0;
	nimln_(437, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/arithme"
"tics.nim");
	nimln_(441, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/arithme"
"tics.nim");
	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));
	popFrame();
	return result;
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	nimfr_("usrToCell", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(130, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	T1_ = (NI)0;
	T1_ = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (usr)), ((NI) 16));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem)(NI x, NI y) {
	NIM_BOOL result;
	nimfr_("<%", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/compari"
"sons.nim");
	result = (NIM_BOOL)0;
	nimln_(188, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/compari"
"sons.nim");
	nimln_(190, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/compari"
"sons.nim");
	result = ((NU64)(((NU) (x))) < (NU64)(((NU) (y))));
	popFrame();
	return result;
}
static N_INLINE(void, rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_3system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	nimln_(196, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	addZCT__Y66tOYFjgwJ0k4aLz4bc0Q((&gch__IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}
static N_INLINE(void, decRef__AT1eRuflKWyTTBdLjEDZbg_2system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	nimln_(201, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	(*c).refcount = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem((*c).refcount, ((NI) 8));
	nimln_(202, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		nimln_(203, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
		rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_3system(c);
	}
	LA4_: ;
	popFrame();
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	nimln_(239, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem(src);
		incRef__AT1eRuflKWyTTBdLjEDZbgsystem(T5_);
	}
	LA3_: ;
	nimln_(240, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem((*dest));
		decRef__AT1eRuflKWyTTBdLjEDZbg_2system(T10_);
	}
	LA8_: ;
	nimln_(241, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	(*dest) = src;
	popFrame();
}
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_4)(void) {
	nimGCvisit((void*)reSetextHeader1__jT0jZW9aoPJMKKxZ9a8luXNA, 0);
}
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_6)(void) {
	nimGCvisit((void*)reBreakOrHeader__4bZZeaPoLKeXUaSS8KnqYw, 0);
}
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_8)(void) {
	nimGCvisit((void*)reAtxHeader__GEr9bOIeUjEh09bzJD5FNvbw, 0);
}
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_10)(void) {
	nimGCvisit((void*)reAnotherAtxHeader__ANfVU9bSju6anGNZNzSNUpA, 0);
}
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_12)(void) {
	nimGCvisit((void*)reBlockQuote__JSbt8gQbosjOEdEj3Yz6qA, 0);
}
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_14)(void) {
	nimGCvisit((void*)reUnorderedList__gnzB2GavH0mSSo4dnS9bJgQ, 0);
}
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_16)(void) {
	nimGCvisit((void*)reOrderedList__OkYoHIkPoNM9bQjLi0h9ck5w, 0);
}
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_18)(void) {
	nimGCvisit((void*)reIndentedCodeBlock__lgsdCjdVvq5rkUZ0oA4gxw, 0);
}
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_20)(void) {
	nimGCvisit((void*)reBreakIndentedCode__M9bs8fT9cKQgQccoWZepAGZw, 0);
}
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_22)(void) {
	nimGCvisit((void*)reFencedCodeBlockChar__qY9b0H3XeBMX9cBVHo7lMWeQ, 0);
}
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_24)(void) {
	nimGCvisit((void*)reFencedCodeBlockTild__drHzwdPzIUdhxrgV2t0CZQ, 0);
}
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_26)(void) {
	nimGCvisit((void*)reHtmlBlock1Begins__F0gzXWGKKtRyRjghcFi9b9bA, 0);
}
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_28)(void) {
	nimGCvisit((void*)reHtmlBlock1Ends__DXwyl5igweZ9bPfP7H9c51zA, 0);
}
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_30)(void) {
	nimGCvisit((void*)reHtmlBlock2Begins__ULdIaxWu22t25A9ciqyg2yg, 0);
}
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_32)(void) {
	nimGCvisit((void*)reHtmlBlock2Ends__VDsIOHZCk3SoRk9acLtHIyQ, 0);
}
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_34)(void) {
	nimGCvisit((void*)reHtmlBlock3Begins__pt9afGK6sTWS9b9cMAArUkljA, 0);
}
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_36)(void) {
	nimGCvisit((void*)reHtmlBlock3Ends__VGcPVYopHc6DDK1hCUXrfQ, 0);
}
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_38)(void) {
	nimGCvisit((void*)reHtmlBlock4Begins__e5VtUseEsuWaYCsA1wVvzA, 0);
}
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_40)(void) {
	nimGCvisit((void*)reHtmlBlock4Ends__T7N0cyb7wE2J5t5UiJTemQ, 0);
}
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_42)(void) {
	nimGCvisit((void*)reHtmlBlock5Begins__CmcKmVUi4Wn8CtIQXkYoQg, 0);
}
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_44)(void) {
	nimGCvisit((void*)reHtmlBlock5Ends__3bR6i0nYCARckeg2FvxbhA, 0);
}
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_46)(void) {
	nimGCvisit((void*)reHtmlBlock6Begins__SpfOp30e4hcOVn3aGXtApQ, 0);
}
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_48)(void) {
	nimGCvisit((void*)reHtmlBlock7Begins__f0K9budy9bkRZHtiN2zjdA9cQ, 0);
}
static N_NIMCALL(void, TM__jIupzeCA9b9b1r5qjBNmoFLw_50)(void) {
	nimGCvisit((void*)reEntity__85u1ODpkOOUfYR1n113FPw, 0);
}
static N_NIMCALL(void, Marker_tyRef__QKxGI1JtsfnFT0BOgq4LIA)(void* p, NI op) {
	tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw* a;
	a = (tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw*)p;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw*, newFlag__DxdUCUJgf4cfmyNeIyxmiw)(void) {
	tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw* result;
	tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw* T1_;
	nimfr_("newFlag", "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	result = (tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw*)0;
	nimln_(69, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	T1_ = (tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw*)0;
	T1_ = (tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw*) newObj((&NTI__QKxGI1JtsfnFT0BOgq4LIA_), sizeof(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw));
	(*T1_).flagBlockQuote = NIM_FALSE;
	(*T1_).flagIndentedCodeBlock = NIM_FALSE;
	(*T1_).indentedCodeBlockDepth = ((NI) 0);
	(*T1_).flagFencedCodeBlockChar = NIM_FALSE;
	(*T1_).flagFencedCodeBlockTild = NIM_FALSE;
	(*T1_).flagHtmlBlock1 = NIM_FALSE;
	(*T1_).flagHtmlBlock2 = NIM_FALSE;
	(*T1_).flagHtmlBlock3 = NIM_FALSE;
	(*T1_).flagHtmlBlock4 = NIM_FALSE;
	(*T1_).flagHtmlBlock5 = NIM_FALSE;
	(*T1_).flagHtmlBlock6 = NIM_FALSE;
	(*T1_).flagHtmlBlock7 = NIM_FALSE;
	(*T1_).flagLinkReference = NIM_FALSE;
	(*T1_).flagUnorderedList = NIM_FALSE;
	(*T1_).flagUnorderedListMarker = NIM_FALSE;
	(*T1_).uldepth = ((NI) 0);
	(*T1_).flagOrderedList = NIM_FALSE;
	(*T1_).flagOrderedListMarker = NIM_FALSE;
	(*T1_).oldepth = ((NI) 0);
	(*T1_).hasEmptyLine = NIM_FALSE;
	(*T1_).afterEmptyLine = NIM_FALSE;
	(*T1_).looseUnordered = NIM_FALSE;
	(*T1_).looseOrdered = NIM_FALSE;
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, countWhitespace__wRjxHGnOkqhHD1hzudpzOA)(NimStringDesc* line) {
	NI result;
	NI i;
	nimfr_("countWhitespace", "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
{	result = (NI)0;
	nimln_(134, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	i = ((NI) 0);
	{
		NIM_CHAR c;
		NI i_2;
		NI L;
		c = (NIM_CHAR)0;
		nimln_(217, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
		i_2 = ((NI) 0);
		nimln_(218, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
		L = (line ? line->Sup.len : 0);
		{
			nimln_(219, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
			while (1) {
				NI TM__jIupzeCA9b9b1r5qjBNmoFLw_54;
				if (!(i_2 < L)) goto LA3;
				nimln_(135, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
				if ((NU)(i_2) >= (NU)(line ? line->Sup.len : 0)){ raiseIndexError2(i_2,(line ? line->Sup.len : 0)-1); }
				c = line->data[i_2];
				nimln_(136, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
				{
					NI TM__jIupzeCA9b9b1r5qjBNmoFLw_53;
					if (!((NU8)(c) == (NU8)(32))) goto LA6_;
					if (nimAddInt(i, ((NI) 1), &TM__jIupzeCA9b9b1r5qjBNmoFLw_53)) { raiseOverflow(); };
					i = (NI)(TM__jIupzeCA9b9b1r5qjBNmoFLw_53);
				}
				goto LA4_;
				LA6_: ;
				{
					nimln_(137, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
					result = i;
					goto BeforeRet_;
				}
				LA4_: ;
				nimln_(221, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
				if (nimAddInt(i_2, ((NI) 1), &TM__jIupzeCA9b9b1r5qjBNmoFLw_54)) { raiseOverflow(); };
				i_2 = (NI)(TM__jIupzeCA9b9b1r5qjBNmoFLw_54);
				nimln_(222, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
				{
					if (!!(((line ? line->Sup.len : 0) == L))) goto LA11_;
					failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_55));
				}
				LA11_: ;
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, matchLen__vylpKAr9bdsSOgr8tMJwQ6wre)(NCSTRING buf, tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start, NI bufSize) {
	NI result;
	int T1_;
	nimfr_("matchLen", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	result = (NI)0;
	nimln_(263, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	if ((start) < ((int) (-2147483647 -1)) || (start) > ((int) 2147483647)){ raiseRangeErrorI(start, ((int) (-2147483647 -1)), ((int) 2147483647)); }
	T1_ = (int)0;
	T1_ = matchOrFind__jpcUBS27e6bot0QabDwvkw(buf, pattern, ((NI) (((int) (start)))), bufSize, ((int) 16));
	result = ((NI) (T1_));
	popFrame();
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (s == ((NimStringDesc*) NIM_NIL));
		if (T3_) goto LA4_;
		T3_ = ((*s).Sup.len == ((NI) 0));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = "";
	}
	goto LA1_;
	LA5_: ;
	{
		result = ((NCSTRING) ((*s).data));
	}
	LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL, match__ATpcLUBGRWa2duwyoHgYLAre)(NimStringDesc* s, tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("match", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	result = (NIM_BOOL)0;
	nimln_(267, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	T1_ = (NI)0;
	T1_ = matchLen__vylpKAr9bdsSOgr8tMJwQ6wre(nimToCStringConv(s), pattern, start, (s ? s->Sup.len : 0));
	result = !((T1_ == ((NI) -1)));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, startsWith__HboK8oxIrqNkDvsNG7wJow)(NimStringDesc* line, tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* regex) {
	NIM_BOOL result;
	nimfr_("startsWith", "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	result = (NIM_BOOL)0;
	nimln_(125, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	result = match__ATpcLUBGRWa2duwyoHgYLAre(line, regex, ((NI) 0));
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tySequence__ysZ0yvYJsxyGumT80SPhXQ)(void* p, NI op) {
	tySequence__ysZ0yvYJsxyGumT80SPhXQ* a;
	NI T1_;
	a = (tySequence__ysZ0yvYJsxyGumT80SPhXQ*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < (a ? a->Sup.len : 0); T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}
static N_NIMCALL(void, Marker_tyRef__f8fGmzFqIDQtrEPBlkxIhw)(void* p, NI op) {
	tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* a;
	a = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)p;
	switch ((*a).kind) {
	case ((tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q) 0):
	nimGCvisit((void*)(*a)._kind_1.children, op);
	break;
	case ((tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q) 1):
	nimGCvisit((void*)(*a)._kind_2.raw, op);
	break;
	} 
}
N_LIB_PRIVATE N_NIMCALL(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*, openList__JEoUK0L3egmZksVMj51ikQ)(tySequence__ysZ0yvYJsxyGumT80SPhXQ* mdast) {
	tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* result;
	tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* T1_;
	nimfr_("openList", "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	result = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
	nimln_(200, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	T1_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
	T1_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*) newObj((&NTI__f8fGmzFqIDQtrEPBlkxIhw_), sizeof(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ));
	(*T1_).kind = ((tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q) 0);
	(*T1_)._kind_1.containerType = ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 18);
	genericSeqAssign((&(*T1_)._kind_1.children), mdast, (&NTI__ysZ0yvYJsxyGumT80SPhXQ_));
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*, openLooseUL__JEoUK0L3egmZksVMj51ikQ_2)(tySequence__ysZ0yvYJsxyGumT80SPhXQ* mdast) {
	tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* result;
	tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* T1_;
	nimfr_("openLooseUL", "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	result = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
	nimln_(203, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	T1_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
	T1_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*) newObj((&NTI__f8fGmzFqIDQtrEPBlkxIhw_), sizeof(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ));
	(*T1_).kind = ((tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q) 0);
	(*T1_)._kind_1.containerType = ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 15);
	genericSeqAssign((&(*T1_)._kind_1.children), mdast, (&NTI__ysZ0yvYJsxyGumT80SPhXQ_));
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*, openTightUL__JEoUK0L3egmZksVMj51ikQ_3)(tySequence__ysZ0yvYJsxyGumT80SPhXQ* mdast) {
	tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* result;
	tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* T1_;
	nimfr_("openTightUL", "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	result = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
	nimln_(206, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	T1_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
	T1_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*) newObj((&NTI__f8fGmzFqIDQtrEPBlkxIhw_), sizeof(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ));
	(*T1_).kind = ((tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q) 0);
	(*T1_)._kind_1.containerType = ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 14);
	genericSeqAssign((&(*T1_)._kind_1.children), mdast, (&NTI__ysZ0yvYJsxyGumT80SPhXQ_));
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, delWhitespace__L9aLByHKuv9crb4azSTKbg6Q)(NimStringDesc* line) {
	NimStringDesc* result;
	NimStringDesc* str;
	nimfr_("delWhitespace", "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
{	result = (NimStringDesc*)0;
	str = (NimStringDesc*)0;
	{
		NIM_CHAR c;
		NI i;
		NI L;
		c = (NIM_CHAR)0;
		nimln_(217, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
		i = ((NI) 0);
		nimln_(218, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
		L = (line ? line->Sup.len : 0);
		{
			nimln_(219, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
			while (1) {
				NI TM__jIupzeCA9b9b1r5qjBNmoFLw_64;
				if (!(i < L)) goto LA3;
				nimln_(129, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
				if ((NU)(i) >= (NU)(line ? line->Sup.len : 0)){ raiseIndexError2(i,(line ? line->Sup.len : 0)-1); }
				c = line->data[i];
				nimln_(130, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
				{
					if (!!(((NU8)(c) == (NU8)(32)))) goto LA6_;
					str = addChar(str, c);
				}
				LA6_: ;
				nimln_(221, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
				if (nimAddInt(i, ((NI) 1), &TM__jIupzeCA9b9b1r5qjBNmoFLw_64)) { raiseOverflow(); };
				i = (NI)(TM__jIupzeCA9b9b1r5qjBNmoFLw_64);
				nimln_(222, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
				{
					if (!!(((line ? line->Sup.len : 0) == L))) goto LA10_;
					failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_55));
				}
				LA10_: ;
			} LA3: ;
		}
	}
	nimln_(131, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	result = copyString(str);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*, openBlockQuote__JEoUK0L3egmZksVMj51ikQ_4)(tySequence__ysZ0yvYJsxyGumT80SPhXQ* mdast) {
	tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* result;
	tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* T1_;
	nimfr_("openBlockQuote", "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	result = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
	nimln_(197, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	T1_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
	T1_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*) newObj((&NTI__f8fGmzFqIDQtrEPBlkxIhw_), sizeof(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ));
	(*T1_).kind = ((tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q) 0);
	(*T1_)._kind_1.containerType = ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 13);
	genericSeqAssign((&(*T1_)._kind_1.children), mdast, (&NTI__ysZ0yvYJsxyGumT80SPhXQ_));
	result = T1_;
	popFrame();
	return result;
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	nimfr_("nimGCunrefNoCycle", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	nimln_(229, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	T1_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem(p);
	decRef__AT1eRuflKWyTTBdLjEDZbg_2system(T1_);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*, openParagraph__mXQ9a0EmFioyadhr9bs4ZomA)(NimStringDesc* lineBlock) {
	tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* result;
	tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* T1_;
	NimStringDesc* T2_;
	nimfr_("openParagraph", "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	result = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
	nimln_(215, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	T1_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
	T1_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*) newObj((&NTI__f8fGmzFqIDQtrEPBlkxIhw_), sizeof(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ));
	(*T1_).kind = ((tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q) 1);
	(*T1_)._kind_2.leafType = ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 1);
	T2_ = (NimStringDesc*)0;
	T2_ = (*T1_)._kind_2.raw; (*T1_)._kind_2.raw = copyStringRC1(lineBlock);
	if (T2_) nimGCunrefNoCycle(T2_);
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*, openLooseOL__JEoUK0L3egmZksVMj51ikQ_5)(tySequence__ysZ0yvYJsxyGumT80SPhXQ* mdast) {
	tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* result;
	tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* T1_;
	nimfr_("openLooseOL", "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	result = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
	nimln_(209, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	T1_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
	T1_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*) newObj((&NTI__f8fGmzFqIDQtrEPBlkxIhw_), sizeof(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ));
	(*T1_).kind = ((tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q) 0);
	(*T1_)._kind_1.containerType = ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 17);
	genericSeqAssign((&(*T1_)._kind_1.children), mdast, (&NTI__ysZ0yvYJsxyGumT80SPhXQ_));
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*, openTightOL__JEoUK0L3egmZksVMj51ikQ_6)(tySequence__ysZ0yvYJsxyGumT80SPhXQ* mdast) {
	tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* result;
	tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* T1_;
	nimfr_("openTightOL", "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	result = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
	nimln_(212, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	T1_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
	T1_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*) newObj((&NTI__f8fGmzFqIDQtrEPBlkxIhw_), sizeof(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ));
	(*T1_).kind = ((tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q) 0);
	(*T1_)._kind_1.containerType = ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 16);
	genericSeqAssign((&(*T1_)._kind_1.children), mdast, (&NTI__ysZ0yvYJsxyGumT80SPhXQ_));
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*, openCodeBlock__TM0OPt68IQEAcF9av2kpYnw)(tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ blockType, NimStringDesc* codeLines) {
	tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* result;
	tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* T1_;
	NimStringDesc* T2_;
	nimfr_("openCodeBlock", "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
{	result = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
	nimln_(182, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	T1_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
	T1_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*) newObj((&NTI__f8fGmzFqIDQtrEPBlkxIhw_), sizeof(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ));
	(*T1_).kind = ((tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q) 1);
	(*T1_)._kind_2.leafType = blockType;
	T2_ = (NimStringDesc*)0;
	T2_ = (*T1_)._kind_2.raw; (*T1_)._kind_2.raw = copyStringRC1(codeLines);
	if (T2_) nimGCunrefNoCycle(T2_);
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(tySequence__lBgZ7a89beZGYPl8PiANMTA*, filter__3Uw65OIODxq9c01vSfAJhpgsequtils)(NIM_CHAR* s, NI sLen_0, tyProc__SL9a4kwASyzvPJy9bdobKVUw pred) {
	tySequence__lBgZ7a89beZGYPl8PiANMTA* result;
	nimfr_("filter", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/collectio"
"ns/sequtils.nim");
	result = (tySequence__lBgZ7a89beZGYPl8PiANMTA*)0;
	nimln_(479, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/collectio"
"ns/sequtils.nim");
	result = newSeq__3jwSUBwo3nEjaheBcZzckg(((NI) 0));
	{
		NI i;
		NI colontmp_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(480, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/collectio"
"ns/sequtils.nim");
		colontmp_ = sLen_0;
		nimln_(106, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs_1.nim");
		i_2 = ((NI) 0);
		{
			nimln_(107, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs_1.nim");
			while (1) {
				NI TM__jIupzeCA9b9b1r5qjBNmoFLw_66;
				if (!(i_2 < colontmp_)) goto LA3;
				nimln_(480, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/collectio"
"ns/sequtils.nim");
				i = i_2;
				nimln_(481, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/collectio"
"ns/sequtils.nim");
				{
					NIM_BOOL T6_;
					NI T9_;
					if ((NU)(i) >= (NU)(sLen_0)){ raiseIndexError2(i,sLen_0-1); }
					T6_ = (NIM_BOOL)0;
					T6_ = pred.ClE_0? pred.ClP_0(s[i], pred.ClE_0):((TM__jIupzeCA9b9b1r5qjBNmoFLw_65)(pred.ClP_0))(s[i]);
					if (!T6_) goto LA7_;
					nimln_(482, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/collectio"
"ns/sequtils.nim");
					if ((NU)(i) >= (NU)(sLen_0)){ raiseIndexError2(i,sLen_0-1); }
					result = (tySequence__lBgZ7a89beZGYPl8PiANMTA*) incrSeqV3((TGenericSeq*)(result), (&NTI__lBgZ7a89beZGYPl8PiANMTA_));
					T9_ = result->Sup.len++;
					result->data[T9_] = s[i];
				}
				LA7_: ;
				nimln_(109, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs_1.nim");
				if (nimAddInt(i_2, ((NI) 1), &TM__jIupzeCA9b9b1r5qjBNmoFLw_66)) { raiseOverflow(); };
				i_2 = (NI)(TM__jIupzeCA9b9b1r5qjBNmoFLw_66);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, colonanonymous___Hhd0KV9cyGTuKcEOHJRGTww)(NIM_CHAR x) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_(":anonymous", "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	result = (NIM_BOOL)0;
	nimln_(140, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = ((NU8)(x) == (NU8)(96));
	if (T1_) goto LA2_;
	T1_ = ((NU8)(x) == (NU8)(126));
	LA2_: ;
	result = T1_;
	popFrame();
	return result;
}
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory(p, ((int) 0), size);
}
N_LIB_PRIVATE N_NIMCALL(NI, countBacktick__wRjxHGnOkqhHD1hzudpzOA_2)(NimStringDesc* line) {
	NI result;
	tyProc__SL9a4kwASyzvPJy9bdobKVUw T1_;
	tySequence__lBgZ7a89beZGYPl8PiANMTA* T2_;
	NI T3_;
	nimfr_("countBacktick", "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	result = (NI)0;
	nimln_(140, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	nimZeroMem((void*)(&T1_), sizeof(tyProc__SL9a4kwASyzvPJy9bdobKVUw));
	T1_.ClP_0 = ((TM__jIupzeCA9b9b1r5qjBNmoFLw_67) (colonanonymous___Hhd0KV9cyGTuKcEOHJRGTww)); T1_.ClE_0 = NIM_NIL;
	T2_ = (tySequence__lBgZ7a89beZGYPl8PiANMTA*)0;
	T2_ = filter__3Uw65OIODxq9c01vSfAJhpgsequtils(line->data, (line ? line->Sup.len : 0), T1_);
	T3_ = (T2_ ? T2_->Sup.len : 0);
	result = T3_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*, openHtmlBlock__mXQ9a0EmFioyadhr9bs4ZomA_2)(NimStringDesc* lineBlock) {
	tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* result;
	tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* T1_;
	NimStringDesc* T2_;
	nimfr_("openHtmlBlock", "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
{	result = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
	nimln_(191, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	T1_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
	T1_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*) newObj((&NTI__f8fGmzFqIDQtrEPBlkxIhw_), sizeof(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ));
	(*T1_).kind = ((tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q) 1);
	(*T1_)._kind_2.leafType = ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 11);
	T2_ = (NimStringDesc*)0;
	T2_ = (*T1_)._kind_2.raw; (*T1_)._kind_2.raw = copyStringRC1(lineBlock);
	if (T2_) nimGCunrefNoCycle(T2_);
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*, openLinkReference__mXQ9a0EmFioyadhr9bs4ZomA_3)(NimStringDesc* lineBlock) {
	tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* result;
	tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* T1_;
	NimStringDesc* T2_;
	nimfr_("openLinkReference", "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
{	result = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
	nimln_(194, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	T1_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
	T1_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*) newObj((&NTI__f8fGmzFqIDQtrEPBlkxIhw_), sizeof(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ));
	(*T1_).kind = ((tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q) 1);
	(*T1_)._kind_2.leafType = ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 12);
	T2_ = (NimStringDesc*)0;
	T2_ = (*T1_)._kind_2.raw; (*T1_)._kind_2.raw = copyStringRC1(lineBlock);
	if (T2_) nimGCunrefNoCycle(T2_);
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size) {
	int result;
	result = (int)0;
	result = memcmp(a, b, ((size_t) (size)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__9bGgqEk7RXXl6eqM9c1HdELAsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = nimCmpMem(a, b, size);
	result = (T1_ == ((NI32) 0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NI alen;
	NI blen;
	nimfr_("eqStrings", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/strmant"
"le.nim");
{	result = (NIM_BOOL)0;
	nimln_(24, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/strmant"
"le.nim");
	alen = (a ? a->Sup.len : 0);
	nimln_(25, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/strmant"
"le.nim");
	blen = (b ? b->Sup.len : 0);
	nimln_(26, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/strmant"
"le.nim");
	{
		if (!(alen == blen)) goto LA3_;
		nimln_(27, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/strmant"
"le.nim");
		{
			if (!(alen == ((NI) 0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
		LA7_: ;
		nimln_(28, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/strmant"
"le.nim");
		result = equalMem__9bGgqEk7RXXl6eqM9c1HdELAsystem(((void*) ((&a->data[((NI) 0)]))), ((void*) ((&b->data[((NI) 0)]))), ((NI) (alen)));
		goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*, openAtxHeader__2uvzgTmpkSS3Xj9aMqYww3w)(NimStringDesc* line) {
	tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* result;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ* T1_;
	nimfr_("openAtxHeader", "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
{	result = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
	nimln_(143, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	T1_ = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ*)0;
	T1_ = nsuSplitWhitespace(line, ((NI) -1));
	if ((NU)(((NI) 0)) >= (NU)(T1_ ? T1_->Sup.len : 0)){ raiseIndexError2(((NI) 0),(T1_ ? T1_->Sup.len : 0)-1); }
	if (eqStrings(T1_->data[((NI) 0)], ((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_68))) goto LA2_;
	if (eqStrings(T1_->data[((NI) 0)], ((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_69))) goto LA3_;
	if (eqStrings(T1_->data[((NI) 0)], ((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_70))) goto LA4_;
	if (eqStrings(T1_->data[((NI) 0)], ((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_71))) goto LA5_;
	if (eqStrings(T1_->data[((NI) 0)], ((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_72))) goto LA6_;
	if (eqStrings(T1_->data[((NI) 0)], ((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_73))) goto LA7_;
	goto LA8_;
	LA2_: ;
	{
		NimStringDesc* str;
		tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* T11_;
		NimStringDesc* T12_;
		nimln_(145, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
		str = nsuStrip(line, NIM_TRUE, NIM_TRUE, TM__jIupzeCA9b9b1r5qjBNmoFLw_74);
		nimln_(146, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
		T11_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
		T11_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*) newObj((&NTI__f8fGmzFqIDQtrEPBlkxIhw_), sizeof(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ));
		(*T11_).kind = ((tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q) 1);
		(*T11_)._kind_2.leafType = ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 2);
		T12_ = (NimStringDesc*)0;
		T12_ = (*T11_)._kind_2.raw; (*T11_)._kind_2.raw = copyStringRC1(str);
		if (T12_) nimGCunrefNoCycle(T12_);
		result = T11_;
		goto BeforeRet_;
	}
	goto LA9_;
	LA3_: ;
	{
		NimStringDesc* str_2;
		tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* T14_;
		NimStringDesc* T15_;
		nimln_(148, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
		str_2 = nsuStrip(line, NIM_TRUE, NIM_TRUE, TM__jIupzeCA9b9b1r5qjBNmoFLw_74);
		nimln_(149, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
		T14_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
		T14_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*) newObj((&NTI__f8fGmzFqIDQtrEPBlkxIhw_), sizeof(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ));
		(*T14_).kind = ((tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q) 1);
		(*T14_)._kind_2.leafType = ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 3);
		T15_ = (NimStringDesc*)0;
		T15_ = (*T14_)._kind_2.raw; (*T14_)._kind_2.raw = copyStringRC1(str_2);
		if (T15_) nimGCunrefNoCycle(T15_);
		result = T14_;
		goto BeforeRet_;
	}
	goto LA9_;
	LA4_: ;
	{
		NimStringDesc* str_3;
		tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* T17_;
		NimStringDesc* T18_;
		nimln_(151, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
		str_3 = nsuStrip(line, NIM_TRUE, NIM_TRUE, TM__jIupzeCA9b9b1r5qjBNmoFLw_74);
		nimln_(152, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
		T17_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
		T17_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*) newObj((&NTI__f8fGmzFqIDQtrEPBlkxIhw_), sizeof(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ));
		(*T17_).kind = ((tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q) 1);
		(*T17_)._kind_2.leafType = ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 4);
		T18_ = (NimStringDesc*)0;
		T18_ = (*T17_)._kind_2.raw; (*T17_)._kind_2.raw = copyStringRC1(str_3);
		if (T18_) nimGCunrefNoCycle(T18_);
		result = T17_;
		goto BeforeRet_;
	}
	goto LA9_;
	LA5_: ;
	{
		NimStringDesc* str_4;
		tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* T20_;
		NimStringDesc* T21_;
		nimln_(154, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
		str_4 = nsuStrip(line, NIM_TRUE, NIM_TRUE, TM__jIupzeCA9b9b1r5qjBNmoFLw_74);
		nimln_(155, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
		T20_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
		T20_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*) newObj((&NTI__f8fGmzFqIDQtrEPBlkxIhw_), sizeof(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ));
		(*T20_).kind = ((tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q) 1);
		(*T20_)._kind_2.leafType = ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 5);
		T21_ = (NimStringDesc*)0;
		T21_ = (*T20_)._kind_2.raw; (*T20_)._kind_2.raw = copyStringRC1(str_4);
		if (T21_) nimGCunrefNoCycle(T21_);
		result = T20_;
		goto BeforeRet_;
	}
	goto LA9_;
	LA6_: ;
	{
		NimStringDesc* str_5;
		tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* T23_;
		NimStringDesc* T24_;
		nimln_(157, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
		str_5 = nsuStrip(line, NIM_TRUE, NIM_TRUE, TM__jIupzeCA9b9b1r5qjBNmoFLw_74);
		nimln_(158, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
		T23_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
		T23_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*) newObj((&NTI__f8fGmzFqIDQtrEPBlkxIhw_), sizeof(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ));
		(*T23_).kind = ((tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q) 1);
		(*T23_)._kind_2.leafType = ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 6);
		T24_ = (NimStringDesc*)0;
		T24_ = (*T23_)._kind_2.raw; (*T23_)._kind_2.raw = copyStringRC1(str_5);
		if (T24_) nimGCunrefNoCycle(T24_);
		result = T23_;
		goto BeforeRet_;
	}
	goto LA9_;
	LA7_: ;
	{
		NimStringDesc* str_6;
		tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* T26_;
		NimStringDesc* T27_;
		nimln_(160, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
		str_6 = nsuStrip(line, NIM_TRUE, NIM_TRUE, TM__jIupzeCA9b9b1r5qjBNmoFLw_74);
		nimln_(161, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
		T26_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
		T26_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*) newObj((&NTI__f8fGmzFqIDQtrEPBlkxIhw_), sizeof(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ));
		(*T26_).kind = ((tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q) 1);
		(*T26_)._kind_2.leafType = ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 7);
		T27_ = (NimStringDesc*)0;
		T27_ = (*T26_)._kind_2.raw; (*T26_)._kind_2.raw = copyStringRC1(str_6);
		if (T27_) nimGCunrefNoCycle(T27_);
		result = T26_;
		goto BeforeRet_;
	}
	goto LA9_;
	LA8_: ;
	{
	}
	LA9_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*, openSetextHeader__MAYRBdrQlxkLXj9aI9aP2nAg)(tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ blockType, NimStringDesc* lineBlock) {
	tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* result;
	tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* T1_;
	NimStringDesc* T2_;
	nimfr_("openSetextHeader", "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
{	result = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
	nimln_(185, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	T1_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
	T1_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*) newObj((&NTI__f8fGmzFqIDQtrEPBlkxIhw_), sizeof(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ));
	(*T1_).kind = ((tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q) 1);
	(*T1_)._kind_2.leafType = blockType;
	T2_ = (NimStringDesc*)0;
	T2_ = (*T1_)._kind_2.raw; (*T1_)._kind_2.raw = copyStringRC1(lineBlock);
	if (T2_) nimGCunrefNoCycle(T2_);
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*, openThemanticBreak__bI9cF2FoUcg4Of2vbbWms9aw)(void) {
	tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* result;
	tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* T1_;
	nimfr_("openThemanticBreak", "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
{	result = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
	nimln_(188, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	T1_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
	T1_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*) newObj((&NTI__f8fGmzFqIDQtrEPBlkxIhw_), sizeof(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ));
	(*T1_).kind = ((tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q) 1);
	(*T1_)._kind_2.leafType = ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 8);
	asgnRef((void**) (&(*T1_)._kind_2.raw), ((NimStringDesc*) NIM_NIL));
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*, openContainerBlock__q9cdL13hHzOAAcNbFhueNEQ)(tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ blockType, tySequence__ysZ0yvYJsxyGumT80SPhXQ* mdast) {
	tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* result;
	tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* T1_;
	nimfr_("openContainerBlock", "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
{	result = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
	nimln_(179, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	T1_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*)0;
	T1_ = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*) newObj((&NTI__f8fGmzFqIDQtrEPBlkxIhw_), sizeof(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ));
	(*T1_).kind = ((tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q) 0);
	(*T1_)._kind_1.containerType = blockType;
	genericSeqAssign((&(*T1_)._kind_1.children), mdast, (&NTI__ysZ0yvYJsxyGumT80SPhXQ_));
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nmark_defBlockInit000)(void) {
{
	TFrame FR_; FR_.len = 0;

	nimRegisterGlobalMarker(TM__jIupzeCA9b9b1r5qjBNmoFLw_2);


	nimRegisterGlobalMarker(TM__jIupzeCA9b9b1r5qjBNmoFLw_4);


	nimRegisterGlobalMarker(TM__jIupzeCA9b9b1r5qjBNmoFLw_6);


	nimRegisterGlobalMarker(TM__jIupzeCA9b9b1r5qjBNmoFLw_8);


	nimRegisterGlobalMarker(TM__jIupzeCA9b9b1r5qjBNmoFLw_10);


	nimRegisterGlobalMarker(TM__jIupzeCA9b9b1r5qjBNmoFLw_12);


	nimRegisterGlobalMarker(TM__jIupzeCA9b9b1r5qjBNmoFLw_14);


	nimRegisterGlobalMarker(TM__jIupzeCA9b9b1r5qjBNmoFLw_16);


	nimRegisterGlobalMarker(TM__jIupzeCA9b9b1r5qjBNmoFLw_18);


	nimRegisterGlobalMarker(TM__jIupzeCA9b9b1r5qjBNmoFLw_20);


	nimRegisterGlobalMarker(TM__jIupzeCA9b9b1r5qjBNmoFLw_22);


	nimRegisterGlobalMarker(TM__jIupzeCA9b9b1r5qjBNmoFLw_24);


	nimRegisterGlobalMarker(TM__jIupzeCA9b9b1r5qjBNmoFLw_26);


	nimRegisterGlobalMarker(TM__jIupzeCA9b9b1r5qjBNmoFLw_28);


	nimRegisterGlobalMarker(TM__jIupzeCA9b9b1r5qjBNmoFLw_30);


	nimRegisterGlobalMarker(TM__jIupzeCA9b9b1r5qjBNmoFLw_32);


	nimRegisterGlobalMarker(TM__jIupzeCA9b9b1r5qjBNmoFLw_34);


	nimRegisterGlobalMarker(TM__jIupzeCA9b9b1r5qjBNmoFLw_36);


	nimRegisterGlobalMarker(TM__jIupzeCA9b9b1r5qjBNmoFLw_38);


	nimRegisterGlobalMarker(TM__jIupzeCA9b9b1r5qjBNmoFLw_40);


	nimRegisterGlobalMarker(TM__jIupzeCA9b9b1r5qjBNmoFLw_42);


	nimRegisterGlobalMarker(TM__jIupzeCA9b9b1r5qjBNmoFLw_44);


	nimRegisterGlobalMarker(TM__jIupzeCA9b9b1r5qjBNmoFLw_46);


	nimRegisterGlobalMarker(TM__jIupzeCA9b9b1r5qjBNmoFLw_48);


	nimRegisterGlobalMarker(TM__jIupzeCA9b9b1r5qjBNmoFLw_50);

}/* preInitProc end */
{
	nimfr_("defBlock", "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	nimln_(96, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	asgnRef((void**) (&reThematicBreak__exGX706CkNVB7PBj71hg8Q), re__BHdoI8AriYxT9bGXrX9c7EhQ(((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_3), 16));
	nimln_(97, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	asgnRef((void**) (&reSetextHeader1__jT0jZW9aoPJMKKxZ9a8luXNA), re__BHdoI8AriYxT9bGXrX9c7EhQ(((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_5), 16));
	nimln_(98, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	asgnRef((void**) (&reBreakOrHeader__4bZZeaPoLKeXUaSS8KnqYw), re__BHdoI8AriYxT9bGXrX9c7EhQ(((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_7), 16));
	nimln_(99, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	asgnRef((void**) (&reAtxHeader__GEr9bOIeUjEh09bzJD5FNvbw), re__BHdoI8AriYxT9bGXrX9c7EhQ(((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_9), 16));
	nimln_(100, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	asgnRef((void**) (&reAnotherAtxHeader__ANfVU9bSju6anGNZNzSNUpA), re__BHdoI8AriYxT9bGXrX9c7EhQ(((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_11), 16));
	nimln_(101, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	asgnRef((void**) (&reBlockQuote__JSbt8gQbosjOEdEj3Yz6qA), re__BHdoI8AriYxT9bGXrX9c7EhQ(((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_13), 16));
	nimln_(102, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	asgnRef((void**) (&reUnorderedList__gnzB2GavH0mSSo4dnS9bJgQ), re__BHdoI8AriYxT9bGXrX9c7EhQ(((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_15), 16));
	nimln_(103, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	asgnRef((void**) (&reOrderedList__OkYoHIkPoNM9bQjLi0h9ck5w), re__BHdoI8AriYxT9bGXrX9c7EhQ(((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_17), 16));
	nimln_(104, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	asgnRef((void**) (&reIndentedCodeBlock__lgsdCjdVvq5rkUZ0oA4gxw), re__BHdoI8AriYxT9bGXrX9c7EhQ(((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_19), 16));
	nimln_(105, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	asgnRef((void**) (&reBreakIndentedCode__M9bs8fT9cKQgQccoWZepAGZw), re__BHdoI8AriYxT9bGXrX9c7EhQ(((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_21), 16));
	nimln_(106, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	asgnRef((void**) (&reFencedCodeBlockChar__qY9b0H3XeBMX9cBVHo7lMWeQ), re__BHdoI8AriYxT9bGXrX9c7EhQ(((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_23), 16));
	nimln_(107, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	asgnRef((void**) (&reFencedCodeBlockTild__drHzwdPzIUdhxrgV2t0CZQ), re__BHdoI8AriYxT9bGXrX9c7EhQ(((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_25), 16));
	nimln_(109, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	asgnRef((void**) (&reHtmlBlock1Begins__F0gzXWGKKtRyRjghcFi9b9bA), re__BHdoI8AriYxT9bGXrX9c7EhQ(((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_27), 16));
	nimln_(110, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	asgnRef((void**) (&reHtmlBlock1Ends__DXwyl5igweZ9bPfP7H9c51zA), re__BHdoI8AriYxT9bGXrX9c7EhQ(((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_29), 16));
	nimln_(111, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	asgnRef((void**) (&reHtmlBlock2Begins__ULdIaxWu22t25A9ciqyg2yg), re__BHdoI8AriYxT9bGXrX9c7EhQ(((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_31), 16));
	nimln_(112, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	asgnRef((void**) (&reHtmlBlock2Ends__VDsIOHZCk3SoRk9acLtHIyQ), re__BHdoI8AriYxT9bGXrX9c7EhQ(((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_33), 16));
	nimln_(113, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	asgnRef((void**) (&reHtmlBlock3Begins__pt9afGK6sTWS9b9cMAArUkljA), re__BHdoI8AriYxT9bGXrX9c7EhQ(((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_35), 16));
	nimln_(114, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	asgnRef((void**) (&reHtmlBlock3Ends__VGcPVYopHc6DDK1hCUXrfQ), re__BHdoI8AriYxT9bGXrX9c7EhQ(((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_37), 16));
	nimln_(115, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	asgnRef((void**) (&reHtmlBlock4Begins__e5VtUseEsuWaYCsA1wVvzA), re__BHdoI8AriYxT9bGXrX9c7EhQ(((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_39), 16));
	nimln_(116, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	asgnRef((void**) (&reHtmlBlock4Ends__T7N0cyb7wE2J5t5UiJTemQ), re__BHdoI8AriYxT9bGXrX9c7EhQ(((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_41), 16));
	nimln_(117, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	asgnRef((void**) (&reHtmlBlock5Begins__CmcKmVUi4Wn8CtIQXkYoQg), re__BHdoI8AriYxT9bGXrX9c7EhQ(((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_43), 16));
	nimln_(118, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	asgnRef((void**) (&reHtmlBlock5Ends__3bR6i0nYCARckeg2FvxbhA), re__BHdoI8AriYxT9bGXrX9c7EhQ(((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_45), 16));
	nimln_(119, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	asgnRef((void**) (&reHtmlBlock6Begins__SpfOp30e4hcOVn3aGXtApQ), re__BHdoI8AriYxT9bGXrX9c7EhQ(((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_47), 16));
	nimln_(120, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	asgnRef((void**) (&reHtmlBlock7Begins__f0K9budy9bkRZHtiN2zjdA9cQ), re__BHdoI8AriYxT9bGXrX9c7EhQ(((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_49), 16));
	nimln_(122, "/home/kyohei/nim/nmark/src/nmarkpkg/private/defBlock.nim");
	asgnRef((void**) (&reEntity__85u1ODpkOOUfYR1n113FPw), re__BHdoI8AriYxT9bGXrX9c7EhQ(((NimStringDesc*) &TM__jIupzeCA9b9b1r5qjBNmoFLw_51), 16));
	popFrame();
}
}

N_LIB_PRIVATE N_NIMCALL(void, nmark_defBlockDatInit000)(void) {

/* section: NIM_merge_TYPE_INIT1 */
static TNimNode* TM__jIupzeCA9b9b1r5qjBNmoFLw_52_25[25];
static TNimNode* TM__jIupzeCA9b9b1r5qjBNmoFLw_56_2[2];
NI TM__jIupzeCA9b9b1r5qjBNmoFLw_58;
static char* NIM_CONST TM__jIupzeCA9b9b1r5qjBNmoFLw_57[2] = {
"containerBlock", 
"leafBlock"};
static TNimNode* TM__jIupzeCA9b9b1r5qjBNmoFLw_59_2[2];
static TNimNode* TM__jIupzeCA9b9b1r5qjBNmoFLw_60_19[19];
NI TM__jIupzeCA9b9b1r5qjBNmoFLw_62;
static char* NIM_CONST TM__jIupzeCA9b9b1r5qjBNmoFLw_61[19] = {
"undefinedBlock", 
"paragraph", 
"header1", 
"header2", 
"header3", 
"header4", 
"header5", 
"header6", 
"themanticBreak", 
"indentedCodeBlock", 
"fencedCodeBlock", 
"htmlBlock", 
"linkReference", 
"blockQuote", 
"unOrderedTightList", 
"unOrderedLooseList", 
"orderedTightList", 
"orderedLooseList", 
"list"};
static TNimNode* TM__jIupzeCA9b9b1r5qjBNmoFLw_63_2[2];
static TNimNode TM__jIupzeCA9b9b1r5qjBNmoFLw_0[56];

/* section: NIM_merge_TYPE_INIT3 */
NTI__QNb1YaizAryqcc2cKZsuyw_.size = sizeof(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw);
NTI__QNb1YaizAryqcc2cKZsuyw_.align = NIM_ALIGNOF(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw);
NTI__QNb1YaizAryqcc2cKZsuyw_.kind = 18;
NTI__QNb1YaizAryqcc2cKZsuyw_.base = 0;
NTI__QNb1YaizAryqcc2cKZsuyw_.flags = 3;
TM__jIupzeCA9b9b1r5qjBNmoFLw_52_25[0] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[1];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[1].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[1].offset = offsetof(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw, flagBlockQuote);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[1].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[1].name = "flagBlockQuote";
TM__jIupzeCA9b9b1r5qjBNmoFLw_52_25[1] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[2];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[2].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[2].offset = offsetof(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw, flagIndentedCodeBlock);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[2].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[2].name = "flagIndentedCodeBlock";
TM__jIupzeCA9b9b1r5qjBNmoFLw_52_25[2] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[3];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[3].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[3].offset = offsetof(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw, indentedCodeBlockDepth);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[3].typ = (&NTI__rR5Bzr1D5krxoo1NcNyeMA_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[3].name = "indentedCodeBlockDepth";
TM__jIupzeCA9b9b1r5qjBNmoFLw_52_25[3] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[4];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[4].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[4].offset = offsetof(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw, flagFencedCodeBlockChar);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[4].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[4].name = "flagFencedCodeBlockChar";
TM__jIupzeCA9b9b1r5qjBNmoFLw_52_25[4] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[5];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[5].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[5].offset = offsetof(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw, flagFencedCodeBlockTild);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[5].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[5].name = "flagFencedCodeBlockTild";
TM__jIupzeCA9b9b1r5qjBNmoFLw_52_25[5] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[6];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[6].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[6].offset = offsetof(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw, openingFenceLength);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[6].typ = (&NTI__rR5Bzr1D5krxoo1NcNyeMA_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[6].name = "openingFenceLength";
TM__jIupzeCA9b9b1r5qjBNmoFLw_52_25[6] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[7];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[7].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[7].offset = offsetof(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw, fencedCodeBlocksdepth);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[7].typ = (&NTI__rR5Bzr1D5krxoo1NcNyeMA_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[7].name = "fencedCodeBlocksdepth";
TM__jIupzeCA9b9b1r5qjBNmoFLw_52_25[7] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[8];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[8].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[8].offset = offsetof(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw, flagHtmlBlock1);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[8].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[8].name = "flagHtmlBlock1";
TM__jIupzeCA9b9b1r5qjBNmoFLw_52_25[8] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[9];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[9].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[9].offset = offsetof(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw, flagHtmlBlock2);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[9].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[9].name = "flagHtmlBlock2";
TM__jIupzeCA9b9b1r5qjBNmoFLw_52_25[9] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[10];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[10].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[10].offset = offsetof(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw, flagHtmlBlock3);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[10].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[10].name = "flagHtmlBlock3";
TM__jIupzeCA9b9b1r5qjBNmoFLw_52_25[10] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[11];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[11].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[11].offset = offsetof(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw, flagHtmlBlock4);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[11].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[11].name = "flagHtmlBlock4";
TM__jIupzeCA9b9b1r5qjBNmoFLw_52_25[11] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[12];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[12].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[12].offset = offsetof(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw, flagHtmlBlock5);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[12].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[12].name = "flagHtmlBlock5";
TM__jIupzeCA9b9b1r5qjBNmoFLw_52_25[12] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[13];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[13].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[13].offset = offsetof(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw, flagHtmlBlock6);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[13].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[13].name = "flagHtmlBlock6";
TM__jIupzeCA9b9b1r5qjBNmoFLw_52_25[13] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[14];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[14].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[14].offset = offsetof(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw, flagHtmlBlock7);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[14].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[14].name = "flagHtmlBlock7";
TM__jIupzeCA9b9b1r5qjBNmoFLw_52_25[14] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[15];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[15].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[15].offset = offsetof(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw, flagLinkReference);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[15].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[15].name = "flagLinkReference";
TM__jIupzeCA9b9b1r5qjBNmoFLw_52_25[15] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[16];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[16].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[16].offset = offsetof(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw, flagUnorderedList);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[16].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[16].name = "flagUnorderedList";
TM__jIupzeCA9b9b1r5qjBNmoFLw_52_25[16] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[17];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[17].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[17].offset = offsetof(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw, flagUnorderedListMarker);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[17].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[17].name = "flagUnorderedListMarker";
TM__jIupzeCA9b9b1r5qjBNmoFLw_52_25[17] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[18];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[18].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[18].offset = offsetof(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw, uldepth);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[18].typ = (&NTI__rR5Bzr1D5krxoo1NcNyeMA_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[18].name = "uldepth";
TM__jIupzeCA9b9b1r5qjBNmoFLw_52_25[18] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[19];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[19].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[19].offset = offsetof(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw, flagOrderedList);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[19].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[19].name = "flagOrderedList";
TM__jIupzeCA9b9b1r5qjBNmoFLw_52_25[19] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[20];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[20].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[20].offset = offsetof(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw, flagOrderedListMarker);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[20].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[20].name = "flagOrderedListMarker";
TM__jIupzeCA9b9b1r5qjBNmoFLw_52_25[20] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[21];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[21].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[21].offset = offsetof(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw, oldepth);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[21].typ = (&NTI__rR5Bzr1D5krxoo1NcNyeMA_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[21].name = "oldepth";
TM__jIupzeCA9b9b1r5qjBNmoFLw_52_25[21] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[22];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[22].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[22].offset = offsetof(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw, hasEmptyLine);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[22].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[22].name = "hasEmptyLine";
TM__jIupzeCA9b9b1r5qjBNmoFLw_52_25[22] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[23];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[23].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[23].offset = offsetof(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw, afterEmptyLine);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[23].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[23].name = "afterEmptyLine";
TM__jIupzeCA9b9b1r5qjBNmoFLw_52_25[23] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[24];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[24].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[24].offset = offsetof(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw, looseUnordered);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[24].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[24].name = "looseUnordered";
TM__jIupzeCA9b9b1r5qjBNmoFLw_52_25[24] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[25];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[25].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[25].offset = offsetof(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw, looseOrdered);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[25].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[25].name = "looseOrdered";
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[0].len = 25; TM__jIupzeCA9b9b1r5qjBNmoFLw_0[0].kind = 2; TM__jIupzeCA9b9b1r5qjBNmoFLw_0[0].sons = &TM__jIupzeCA9b9b1r5qjBNmoFLw_52_25[0];
NTI__QNb1YaizAryqcc2cKZsuyw_.node = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[0];
NTI__QKxGI1JtsfnFT0BOgq4LIA_.size = sizeof(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw*);
NTI__QKxGI1JtsfnFT0BOgq4LIA_.align = NIM_ALIGNOF(tyObject_FlagObj__QNb1YaizAryqcc2cKZsuyw*);
NTI__QKxGI1JtsfnFT0BOgq4LIA_.kind = 22;
NTI__QKxGI1JtsfnFT0BOgq4LIA_.base = (&NTI__QNb1YaizAryqcc2cKZsuyw_);
NTI__QKxGI1JtsfnFT0BOgq4LIA_.flags = 2;
NTI__QKxGI1JtsfnFT0BOgq4LIA_.marker = Marker_tyRef__QKxGI1JtsfnFT0BOgq4LIA;
NTI__Aao0goirPrklcSrQBcoeNQ_.size = sizeof(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ);
NTI__Aao0goirPrklcSrQBcoeNQ_.align = NIM_ALIGNOF(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ);
NTI__Aao0goirPrklcSrQBcoeNQ_.kind = 18;
NTI__Aao0goirPrklcSrQBcoeNQ_.base = 0;
NTI__ipIjlgDkqbVTHr4JvmL47Q_.size = sizeof(tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q);
NTI__ipIjlgDkqbVTHr4JvmL47Q_.align = NIM_ALIGNOF(tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q);
NTI__ipIjlgDkqbVTHr4JvmL47Q_.kind = 14;
NTI__ipIjlgDkqbVTHr4JvmL47Q_.base = 0;
NTI__ipIjlgDkqbVTHr4JvmL47Q_.flags = 3;
for (TM__jIupzeCA9b9b1r5qjBNmoFLw_58 = 0; TM__jIupzeCA9b9b1r5qjBNmoFLw_58 < 2; TM__jIupzeCA9b9b1r5qjBNmoFLw_58++) {
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[TM__jIupzeCA9b9b1r5qjBNmoFLw_58+27].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[TM__jIupzeCA9b9b1r5qjBNmoFLw_58+27].offset = TM__jIupzeCA9b9b1r5qjBNmoFLw_58;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[TM__jIupzeCA9b9b1r5qjBNmoFLw_58+27].name = TM__jIupzeCA9b9b1r5qjBNmoFLw_57[TM__jIupzeCA9b9b1r5qjBNmoFLw_58];
TM__jIupzeCA9b9b1r5qjBNmoFLw_56_2[TM__jIupzeCA9b9b1r5qjBNmoFLw_58] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[TM__jIupzeCA9b9b1r5qjBNmoFLw_58+27];
}
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[29].len = 2; TM__jIupzeCA9b9b1r5qjBNmoFLw_0[29].kind = 2; TM__jIupzeCA9b9b1r5qjBNmoFLw_0[29].sons = &TM__jIupzeCA9b9b1r5qjBNmoFLw_56_2[0];
NTI__ipIjlgDkqbVTHr4JvmL47Q_.node = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[29];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[26].kind = 3;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[26].offset = offsetof(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ, kind);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[26].typ = (&NTI__ipIjlgDkqbVTHr4JvmL47Q_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[26].name = "kind";
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[26].sons = &NimDT___Aao0goirPrklcSrQBcoeNQ_kind[0];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[26].len = 2;
TM__jIupzeCA9b9b1r5qjBNmoFLw_59_2[0] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[31];
NTI__f0C73Dxca1VbNsCJ9bxzvzQ_.size = sizeof(tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ);
NTI__f0C73Dxca1VbNsCJ9bxzvzQ_.align = NIM_ALIGNOF(tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ);
NTI__f0C73Dxca1VbNsCJ9bxzvzQ_.kind = 14;
NTI__f0C73Dxca1VbNsCJ9bxzvzQ_.base = 0;
NTI__f0C73Dxca1VbNsCJ9bxzvzQ_.flags = 3;
for (TM__jIupzeCA9b9b1r5qjBNmoFLw_62 = 0; TM__jIupzeCA9b9b1r5qjBNmoFLw_62 < 19; TM__jIupzeCA9b9b1r5qjBNmoFLw_62++) {
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[TM__jIupzeCA9b9b1r5qjBNmoFLw_62+32].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[TM__jIupzeCA9b9b1r5qjBNmoFLw_62+32].offset = TM__jIupzeCA9b9b1r5qjBNmoFLw_62;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[TM__jIupzeCA9b9b1r5qjBNmoFLw_62+32].name = TM__jIupzeCA9b9b1r5qjBNmoFLw_61[TM__jIupzeCA9b9b1r5qjBNmoFLw_62];
TM__jIupzeCA9b9b1r5qjBNmoFLw_60_19[TM__jIupzeCA9b9b1r5qjBNmoFLw_62] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[TM__jIupzeCA9b9b1r5qjBNmoFLw_62+32];
}
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[51].len = 19; TM__jIupzeCA9b9b1r5qjBNmoFLw_0[51].kind = 2; TM__jIupzeCA9b9b1r5qjBNmoFLw_0[51].sons = &TM__jIupzeCA9b9b1r5qjBNmoFLw_60_19[0];
NTI__f0C73Dxca1VbNsCJ9bxzvzQ_.node = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[51];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[31].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[31].offset = offsetof(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ, _kind_1.containerType);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[31].typ = (&NTI__f0C73Dxca1VbNsCJ9bxzvzQ_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[31].name = "containerType";
TM__jIupzeCA9b9b1r5qjBNmoFLw_59_2[1] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[52];
NTI__ysZ0yvYJsxyGumT80SPhXQ_.size = sizeof(tySequence__ysZ0yvYJsxyGumT80SPhXQ*);
NTI__ysZ0yvYJsxyGumT80SPhXQ_.align = NIM_ALIGNOF(tySequence__ysZ0yvYJsxyGumT80SPhXQ*);
NTI__ysZ0yvYJsxyGumT80SPhXQ_.kind = 24;
NTI__ysZ0yvYJsxyGumT80SPhXQ_.base = (&NTI__f8fGmzFqIDQtrEPBlkxIhw_);
NTI__ysZ0yvYJsxyGumT80SPhXQ_.marker = Marker_tySequence__ysZ0yvYJsxyGumT80SPhXQ;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[52].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[52].offset = offsetof(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ, _kind_1.children);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[52].typ = (&NTI__ysZ0yvYJsxyGumT80SPhXQ_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[52].name = "children";
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[30].len = 2; TM__jIupzeCA9b9b1r5qjBNmoFLw_0[30].kind = 2; TM__jIupzeCA9b9b1r5qjBNmoFLw_0[30].sons = &TM__jIupzeCA9b9b1r5qjBNmoFLw_59_2[0];
NimDT___Aao0goirPrklcSrQBcoeNQ_kind[0] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[30];
TM__jIupzeCA9b9b1r5qjBNmoFLw_63_2[0] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[54];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[54].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[54].offset = offsetof(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ, _kind_2.leafType);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[54].typ = (&NTI__f0C73Dxca1VbNsCJ9bxzvzQ_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[54].name = "leafType";
TM__jIupzeCA9b9b1r5qjBNmoFLw_63_2[1] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[55];
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[55].kind = 1;
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[55].offset = offsetof(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ, _kind_2.raw);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[55].typ = (&NTI__77mFvmsOLKik79ci2hXkHEg_);
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[55].name = "raw";
TM__jIupzeCA9b9b1r5qjBNmoFLw_0[53].len = 2; TM__jIupzeCA9b9b1r5qjBNmoFLw_0[53].kind = 2; TM__jIupzeCA9b9b1r5qjBNmoFLw_0[53].sons = &TM__jIupzeCA9b9b1r5qjBNmoFLw_63_2[0];
NimDT___Aao0goirPrklcSrQBcoeNQ_kind[1] = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[53];
NTI__Aao0goirPrklcSrQBcoeNQ_.node = &TM__jIupzeCA9b9b1r5qjBNmoFLw_0[26];
NTI__f8fGmzFqIDQtrEPBlkxIhw_.size = sizeof(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*);
NTI__f8fGmzFqIDQtrEPBlkxIhw_.align = NIM_ALIGNOF(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ*);
NTI__f8fGmzFqIDQtrEPBlkxIhw_.kind = 22;
NTI__f8fGmzFqIDQtrEPBlkxIhw_.base = (&NTI__Aao0goirPrklcSrQBcoeNQ_);
NTI__f8fGmzFqIDQtrEPBlkxIhw_.marker = Marker_tyRef__f8fGmzFqIDQtrEPBlkxIhw;
}

