/* Generated by Nim Compiler v1.4.4 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3   -I/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib -I/home/kyohei/nim/nmark/tests -o /home/kyohei/nim/nmark/nimcache/tests/testRegular.nim_0d61f8370cad1d412f80b84d143e1257/@m..@ssrc@snmarkpkg@sprivate@sastToHtml.nim.c.o /home/kyohei/nim/nmark/nimcache/tests/testRegular.nim_0d61f8370cad1d412f80b84d143e1257/@m..@ssrc@snmarkpkg@sprivate@sastToHtml.nim.c */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ;
typedef struct tySequence__ysZ0yvYJsxyGumT80SPhXQ tySequence__ysZ0yvYJsxyGumT80SPhXQ;

/* section: NIM_merge_TYPES */
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q;
typedef NU8 tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ;
struct tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ {
tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q kind;
union{
struct {tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ containerType;
tySequence__ysZ0yvYJsxyGumT80SPhXQ* children;
} _kind_1;
struct {tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ leafType;
NimStringDesc* raw;
} _kind_2;
};
};

/* section: NIM_merge_SEQ_TYPES */
struct tySequence__ysZ0yvYJsxyGumT80SPhXQ {
  TGenericSeq Sup;
  tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* data[SEQ_DECL_SIZE];
};

/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NOINLINE(void, raiseFieldError)(NimStringDesc* f);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, insertInline__OXLJw0MpExHpZqglZbqvqQ)(NimStringDesc* line);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, tagToLiteral__OXLJw0MpExHpZqglZbqvqQ_2)(NimStringDesc* line);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, astToHtml__H0wjxOIgsXdEfhsSU9aap6Q)(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* mdast, NIM_BOOL* isTight);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A)(NimStringDesc* msg);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);

/* section: NIM_merge_DATA */
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_2, "\'leafType\' is not accessible using discriminant \'kind\' of type "
"\'BlockObj\'", 73);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_3, "<hr />\012", 7);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_4, "\'raw\' is not accessible using discriminant \'kind\' of type \'Bloc"
"kObj\'", 68);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_5, "<p>", 3);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_6, "</p>\012", 5);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_7, "<h1>", 4);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_8, "</h1>\012", 6);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_9, "<h2>", 4);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_10, "</h2>\012", 6);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_11, "<h3>", 4);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_12, "</h3>\012", 6);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_13, "<h4>", 4);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_14, "</h4>\012", 6);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_15, "<h5>", 4);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_16, "</h5>\012", 6);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_17, "<h6>", 4);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_18, "</h6>\012", 6);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_19, "\012", 1);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_20, "<pre><code>", 11);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_21, "\012</code></pre>\012", 15);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_22, "</code></pre>\012", 14);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_23, "\'containerType\' is not accessible using discriminant \'kind\' of "
"type \'BlockObj\'", 78);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_24, "\'children\' is not accessible using discriminant \'kind\' of type "
"\'BlockObj\'", 73);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_26, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim(204, 11) `len(a) == L` the length of the seq changed whil"
"e iterating over it", 146);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_27, "<blockquote>\012", 13);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_28, "</blockquote>\012", 14);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_30, "<li>", 4);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_31, "</li>\012", 6);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_33, "<ul>\012", 5);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_34, "</ul>\012", 6);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_37, "<ol>\012", 5);
STRING_LITERAL(TM__kGjlnpr1nHrV9aiehPuIx2A_38, "</ol>\012", 6);

/* section: NIM_merge_VARS */
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;

/* section: NIM_merge_PROCS */
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__i80o3k0SgEI5gTRCzYdyWAsystem(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, astToHtml__H0wjxOIgsXdEfhsSU9aap6Q)(tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ* mdast, NIM_BOOL* isTight) {
	NimStringDesc* result;
	nimfr_("astToHtml", "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
{	result = (NimStringDesc*)0;
	nimln_(6, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
	switch ((*mdast).kind) {
	case ((tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q) 1):
	{
		nimln_(9, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
		if (!(((2 &((NU8)1<<((NU)((*mdast).kind)&7U)))!=0))){ raiseFieldError(((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_2)); }
		switch ((*mdast)._kind_2.leafType) {
		case ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 8):
		{
			nimln_(11, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
			result = copyString(((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_3));
			goto BeforeRet_;
		}
		break;
		case ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 1):
		{
			NimStringDesc* value;
			nimln_(14, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
			if (!(((2 &((NU8)1<<((NU)((*mdast).kind)&7U)))!=0))){ raiseFieldError(((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_4)); }
			value = insertInline__OXLJw0MpExHpZqglZbqvqQ((*mdast)._kind_2.raw);
			nimln_(15, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
			{
				if (!(*isTight)) goto LA6_;
				result = copyString(value);
				goto BeforeRet_;
			}
			goto LA4_;
			LA6_: ;
			{
				NimStringDesc* T9_;
				nimln_(16, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
				T9_ = (NimStringDesc*)0;
				T9_ = rawNewString((value ? value->Sup.len : 0) + 8);
appendString(T9_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_5));
appendString(T9_, value);
appendString(T9_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_6));
				result = T9_;
				goto BeforeRet_;
			}
			LA4_: ;
		}
		break;
		case ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 2):
		{
			NimStringDesc* T11_;
			NimStringDesc* T12_;
			nimln_(18, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
			T11_ = (NimStringDesc*)0;
			if (!(((2 &((NU8)1<<((NU)((*mdast).kind)&7U)))!=0))){ raiseFieldError(((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_4)); }
			T12_ = (NimStringDesc*)0;
			T12_ = insertInline__OXLJw0MpExHpZqglZbqvqQ((*mdast)._kind_2.raw);
			T11_ = rawNewString((T12_ ? T12_->Sup.len : 0) + 10);
appendString(T11_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_7));
appendString(T11_, T12_);
appendString(T11_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_8));
			result = T11_;
			goto BeforeRet_;
		}
		break;
		case ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 3):
		{
			NimStringDesc* T14_;
			NimStringDesc* T15_;
			nimln_(20, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
			T14_ = (NimStringDesc*)0;
			if (!(((2 &((NU8)1<<((NU)((*mdast).kind)&7U)))!=0))){ raiseFieldError(((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_4)); }
			T15_ = (NimStringDesc*)0;
			T15_ = insertInline__OXLJw0MpExHpZqglZbqvqQ((*mdast)._kind_2.raw);
			T14_ = rawNewString((T15_ ? T15_->Sup.len : 0) + 10);
appendString(T14_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_9));
appendString(T14_, T15_);
appendString(T14_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_10));
			result = T14_;
			goto BeforeRet_;
		}
		break;
		case ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 4):
		{
			NimStringDesc* T17_;
			NimStringDesc* T18_;
			nimln_(22, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
			T17_ = (NimStringDesc*)0;
			if (!(((2 &((NU8)1<<((NU)((*mdast).kind)&7U)))!=0))){ raiseFieldError(((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_4)); }
			T18_ = (NimStringDesc*)0;
			T18_ = insertInline__OXLJw0MpExHpZqglZbqvqQ((*mdast)._kind_2.raw);
			T17_ = rawNewString((T18_ ? T18_->Sup.len : 0) + 10);
appendString(T17_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_11));
appendString(T17_, T18_);
appendString(T17_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_12));
			result = T17_;
			goto BeforeRet_;
		}
		break;
		case ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 5):
		{
			NimStringDesc* T20_;
			NimStringDesc* T21_;
			nimln_(24, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
			T20_ = (NimStringDesc*)0;
			if (!(((2 &((NU8)1<<((NU)((*mdast).kind)&7U)))!=0))){ raiseFieldError(((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_4)); }
			T21_ = (NimStringDesc*)0;
			T21_ = insertInline__OXLJw0MpExHpZqglZbqvqQ((*mdast)._kind_2.raw);
			T20_ = rawNewString((T21_ ? T21_->Sup.len : 0) + 10);
appendString(T20_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_13));
appendString(T20_, T21_);
appendString(T20_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_14));
			result = T20_;
			goto BeforeRet_;
		}
		break;
		case ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 6):
		{
			NimStringDesc* T23_;
			NimStringDesc* T24_;
			nimln_(26, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
			T23_ = (NimStringDesc*)0;
			if (!(((2 &((NU8)1<<((NU)((*mdast).kind)&7U)))!=0))){ raiseFieldError(((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_4)); }
			T24_ = (NimStringDesc*)0;
			T24_ = insertInline__OXLJw0MpExHpZqglZbqvqQ((*mdast)._kind_2.raw);
			T23_ = rawNewString((T24_ ? T24_->Sup.len : 0) + 10);
appendString(T23_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_15));
appendString(T23_, T24_);
appendString(T23_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_16));
			result = T23_;
			goto BeforeRet_;
		}
		break;
		case ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 7):
		{
			NimStringDesc* T26_;
			NimStringDesc* T27_;
			nimln_(28, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
			T26_ = (NimStringDesc*)0;
			if (!(((2 &((NU8)1<<((NU)((*mdast).kind)&7U)))!=0))){ raiseFieldError(((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_4)); }
			T27_ = (NimStringDesc*)0;
			T27_ = insertInline__OXLJw0MpExHpZqglZbqvqQ((*mdast)._kind_2.raw);
			T26_ = rawNewString((T27_ ? T27_->Sup.len : 0) + 10);
appendString(T26_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_17));
appendString(T26_, T27_);
appendString(T26_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_18));
			result = T26_;
			goto BeforeRet_;
		}
		break;
		case ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 11):
		{
			NimStringDesc* T29_;
			nimln_(30, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
			T29_ = (NimStringDesc*)0;
			if (!(((2 &((NU8)1<<((NU)((*mdast).kind)&7U)))!=0))){ raiseFieldError(((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_4)); }
			T29_ = rawNewString(((*mdast)._kind_2.raw ? (*mdast)._kind_2.raw->Sup.len : 0) + 1);
appendString(T29_, (*mdast)._kind_2.raw);
appendString(T29_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_19));
			result = T29_;
			goto BeforeRet_;
		}
		break;
		case ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 9):
		{
			NimStringDesc* T31_;
			NimStringDesc* T32_;
			nimln_(32, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
			T31_ = (NimStringDesc*)0;
			if (!(((2 &((NU8)1<<((NU)((*mdast).kind)&7U)))!=0))){ raiseFieldError(((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_4)); }
			T32_ = (NimStringDesc*)0;
			T32_ = tagToLiteral__OXLJw0MpExHpZqglZbqvqQ_2((*mdast)._kind_2.raw);
			T31_ = rawNewString((T32_ ? T32_->Sup.len : 0) + 26);
appendString(T31_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_20));
appendString(T31_, T32_);
appendString(T31_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_21));
			result = T31_;
			goto BeforeRet_;
		}
		break;
		case ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 10):
		{
			nimln_(35, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
			{
				NimStringDesc* T38_;
				NimStringDesc* T39_;
				if (!(((2 &((NU8)1<<((NU)((*mdast).kind)&7U)))!=0))){ raiseFieldError(((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_4)); }
				if (!(((*mdast)._kind_2.raw ? (*mdast)._kind_2.raw->Sup.len : 0) == 0)) goto LA36_;
				nimln_(36, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
				T38_ = (NimStringDesc*)0;
				if (!(((2 &((NU8)1<<((NU)((*mdast).kind)&7U)))!=0))){ raiseFieldError(((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_4)); }
				T39_ = (NimStringDesc*)0;
				T39_ = tagToLiteral__OXLJw0MpExHpZqglZbqvqQ_2((*mdast)._kind_2.raw);
				T38_ = rawNewString((T39_ ? T39_->Sup.len : 0) + 25);
appendString(T38_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_20));
appendString(T38_, T39_);
appendString(T38_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_22));
				result = T38_;
				goto BeforeRet_;
			}
			goto LA34_;
			LA36_: ;
			{
				NimStringDesc* T41_;
				NimStringDesc* T42_;
				nimln_(38, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
				T41_ = (NimStringDesc*)0;
				if (!(((2 &((NU8)1<<((NU)((*mdast).kind)&7U)))!=0))){ raiseFieldError(((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_4)); }
				T42_ = (NimStringDesc*)0;
				T42_ = tagToLiteral__OXLJw0MpExHpZqglZbqvqQ_2((*mdast)._kind_2.raw);
				T41_ = rawNewString((T42_ ? T42_->Sup.len : 0) + 26);
appendString(T41_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_20));
appendString(T41_, T42_);
appendString(T41_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_21));
				result = T41_;
				goto BeforeRet_;
			}
			LA34_: ;
		}
		break;
		default:
		{
			nimln_(40, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
			goto BeforeRet_;
		}
		break;
		}
	}
	break;
	case ((tyEnum_BlockKind__ipIjlgDkqbVTHr4JvmL47Q) 0):
	{
		nimln_(44, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
		if (!(((1 &((NU8)1<<((NU)((*mdast).kind)&7U)))!=0))){ raiseFieldError(((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_23)); }
		switch ((*mdast)._kind_1.containerType) {
		case ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 13):
		{
			NimStringDesc* blockQuoteContainer;
			NimStringDesc* T56_;
			blockQuoteContainer = (NimStringDesc*)0;
			{
				tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ** child;
				tySequence__ysZ0yvYJsxyGumT80SPhXQ* colontmp_;
				NI i;
				NI L;
				NI T47_;
				child = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ**)0;
				colontmp_ = (tySequence__ysZ0yvYJsxyGumT80SPhXQ*)0;
				nimln_(49, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
				if (!(((1 &((NU8)1<<((NU)((*mdast).kind)&7U)))!=0))){ raiseFieldError(((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_24)); }
				colontmp_ = (*mdast)._kind_1.children;
				nimln_(199, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
				i = ((NI) 0);
				nimln_(200, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
				T47_ = (colontmp_ ? colontmp_->Sup.len : 0);
				L = T47_;
				{
					nimln_(201, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
					while (1) {
						NimStringDesc* T50_;
						NI TM__kGjlnpr1nHrV9aiehPuIx2A_25;
						if (!(i < L)) goto LA49;
						nimln_(49, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
						if ((NU)(i) >= (NU)(colontmp_ ? colontmp_->Sup.len : 0)){ raiseIndexError2(i,(colontmp_ ? colontmp_->Sup.len : 0)-1); }
						child = &colontmp_->data[i];
						nimln_(50, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
						T50_ = (NimStringDesc*)0;
						T50_ = astToHtml__H0wjxOIgsXdEfhsSU9aap6Q((*child), isTight);
						blockQuoteContainer = resizeString(blockQuoteContainer, (T50_ ? T50_->Sup.len : 0) + 0);
appendString(blockQuoteContainer, T50_);
						nimln_(203, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
						if (nimAddInt(i, ((NI) 1), &TM__kGjlnpr1nHrV9aiehPuIx2A_25)) { raiseOverflow(); };
						i = (NI)(TM__kGjlnpr1nHrV9aiehPuIx2A_25);
						nimln_(204, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
						{
							NI T53_;
							T53_ = (colontmp_ ? colontmp_->Sup.len : 0);
							if (!!((T53_ == L))) goto LA54_;
							failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_26));
						}
						LA54_: ;
					} LA49: ;
				}
			}
			nimln_(51, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
			T56_ = (NimStringDesc*)0;
			T56_ = rawNewString((blockQuoteContainer ? blockQuoteContainer->Sup.len : 0) + 27);
appendString(T56_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_27));
appendString(T56_, blockQuoteContainer);
appendString(T56_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_28));
			result = T56_;
			goto BeforeRet_;
		}
		break;
		case ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 18):
		{
			NimStringDesc* listContainer;
			NimStringDesc* T68_;
			listContainer = (NimStringDesc*)0;
			{
				tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ** child_2;
				tySequence__ysZ0yvYJsxyGumT80SPhXQ* colontmp__2;
				NI i_2;
				NI L_2;
				NI T59_;
				child_2 = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ**)0;
				colontmp__2 = (tySequence__ysZ0yvYJsxyGumT80SPhXQ*)0;
				nimln_(56, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
				if (!(((1 &((NU8)1<<((NU)((*mdast).kind)&7U)))!=0))){ raiseFieldError(((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_24)); }
				colontmp__2 = (*mdast)._kind_1.children;
				nimln_(199, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
				i_2 = ((NI) 0);
				nimln_(200, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
				T59_ = (colontmp__2 ? colontmp__2->Sup.len : 0);
				L_2 = T59_;
				{
					nimln_(201, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
					while (1) {
						NimStringDesc* T62_;
						NI TM__kGjlnpr1nHrV9aiehPuIx2A_29;
						if (!(i_2 < L_2)) goto LA61;
						nimln_(56, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
						if ((NU)(i_2) >= (NU)(colontmp__2 ? colontmp__2->Sup.len : 0)){ raiseIndexError2(i_2,(colontmp__2 ? colontmp__2->Sup.len : 0)-1); }
						child_2 = &colontmp__2->data[i_2];
						nimln_(57, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
						T62_ = (NimStringDesc*)0;
						T62_ = astToHtml__H0wjxOIgsXdEfhsSU9aap6Q((*child_2), isTight);
						listContainer = resizeString(listContainer, (T62_ ? T62_->Sup.len : 0) + 0);
appendString(listContainer, T62_);
						nimln_(203, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
						if (nimAddInt(i_2, ((NI) 1), &TM__kGjlnpr1nHrV9aiehPuIx2A_29)) { raiseOverflow(); };
						i_2 = (NI)(TM__kGjlnpr1nHrV9aiehPuIx2A_29);
						nimln_(204, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
						{
							NI T65_;
							T65_ = (colontmp__2 ? colontmp__2->Sup.len : 0);
							if (!!((T65_ == L_2))) goto LA66_;
							failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_26));
						}
						LA66_: ;
					} LA61: ;
				}
			}
			nimln_(58, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
			T68_ = (NimStringDesc*)0;
			T68_ = rawNewString((listContainer ? listContainer->Sup.len : 0) + 10);
appendString(T68_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_30));
appendString(T68_, listContainer);
appendString(T68_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_31));
			result = T68_;
			goto BeforeRet_;
		}
		break;
		case ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 15):
		{
			NimStringDesc* unOrderedListContainer;
			NimStringDesc* T80_;
			nimln_(62, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
			(*isTight) = NIM_FALSE;
			unOrderedListContainer = (NimStringDesc*)0;
			{
				tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ** child_3;
				tySequence__ysZ0yvYJsxyGumT80SPhXQ* colontmp__3;
				NI i_3;
				NI L_3;
				NI T71_;
				child_3 = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ**)0;
				colontmp__3 = (tySequence__ysZ0yvYJsxyGumT80SPhXQ*)0;
				nimln_(64, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
				if (!(((1 &((NU8)1<<((NU)((*mdast).kind)&7U)))!=0))){ raiseFieldError(((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_24)); }
				colontmp__3 = (*mdast)._kind_1.children;
				nimln_(199, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
				i_3 = ((NI) 0);
				nimln_(200, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
				T71_ = (colontmp__3 ? colontmp__3->Sup.len : 0);
				L_3 = T71_;
				{
					nimln_(201, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
					while (1) {
						NimStringDesc* T74_;
						NI TM__kGjlnpr1nHrV9aiehPuIx2A_32;
						if (!(i_3 < L_3)) goto LA73;
						nimln_(64, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
						if ((NU)(i_3) >= (NU)(colontmp__3 ? colontmp__3->Sup.len : 0)){ raiseIndexError2(i_3,(colontmp__3 ? colontmp__3->Sup.len : 0)-1); }
						child_3 = &colontmp__3->data[i_3];
						nimln_(65, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
						T74_ = (NimStringDesc*)0;
						T74_ = astToHtml__H0wjxOIgsXdEfhsSU9aap6Q((*child_3), isTight);
						unOrderedListContainer = resizeString(unOrderedListContainer, (T74_ ? T74_->Sup.len : 0) + 0);
appendString(unOrderedListContainer, T74_);
						nimln_(203, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
						if (nimAddInt(i_3, ((NI) 1), &TM__kGjlnpr1nHrV9aiehPuIx2A_32)) { raiseOverflow(); };
						i_3 = (NI)(TM__kGjlnpr1nHrV9aiehPuIx2A_32);
						nimln_(204, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
						{
							NI T77_;
							T77_ = (colontmp__3 ? colontmp__3->Sup.len : 0);
							if (!!((T77_ == L_3))) goto LA78_;
							failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_26));
						}
						LA78_: ;
					} LA73: ;
				}
			}
			nimln_(66, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
			T80_ = (NimStringDesc*)0;
			T80_ = rawNewString((unOrderedListContainer ? unOrderedListContainer->Sup.len : 0) + 11);
appendString(T80_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_33));
appendString(T80_, unOrderedListContainer);
appendString(T80_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_34));
			result = T80_;
			goto BeforeRet_;
		}
		break;
		case ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 14):
		{
			NimStringDesc* unOrderedListContainer_2;
			NimStringDesc* T92_;
			nimln_(70, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
			(*isTight) = NIM_TRUE;
			unOrderedListContainer_2 = (NimStringDesc*)0;
			{
				tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ** child_4;
				tySequence__ysZ0yvYJsxyGumT80SPhXQ* colontmp__4;
				NI i_4;
				NI L_4;
				NI T83_;
				child_4 = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ**)0;
				colontmp__4 = (tySequence__ysZ0yvYJsxyGumT80SPhXQ*)0;
				nimln_(72, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
				if (!(((1 &((NU8)1<<((NU)((*mdast).kind)&7U)))!=0))){ raiseFieldError(((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_24)); }
				colontmp__4 = (*mdast)._kind_1.children;
				nimln_(199, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
				i_4 = ((NI) 0);
				nimln_(200, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
				T83_ = (colontmp__4 ? colontmp__4->Sup.len : 0);
				L_4 = T83_;
				{
					nimln_(201, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
					while (1) {
						NimStringDesc* T86_;
						NI TM__kGjlnpr1nHrV9aiehPuIx2A_35;
						if (!(i_4 < L_4)) goto LA85;
						nimln_(72, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
						if ((NU)(i_4) >= (NU)(colontmp__4 ? colontmp__4->Sup.len : 0)){ raiseIndexError2(i_4,(colontmp__4 ? colontmp__4->Sup.len : 0)-1); }
						child_4 = &colontmp__4->data[i_4];
						nimln_(73, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
						T86_ = (NimStringDesc*)0;
						T86_ = astToHtml__H0wjxOIgsXdEfhsSU9aap6Q((*child_4), isTight);
						unOrderedListContainer_2 = resizeString(unOrderedListContainer_2, (T86_ ? T86_->Sup.len : 0) + 0);
appendString(unOrderedListContainer_2, T86_);
						nimln_(203, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
						if (nimAddInt(i_4, ((NI) 1), &TM__kGjlnpr1nHrV9aiehPuIx2A_35)) { raiseOverflow(); };
						i_4 = (NI)(TM__kGjlnpr1nHrV9aiehPuIx2A_35);
						nimln_(204, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
						{
							NI T89_;
							T89_ = (colontmp__4 ? colontmp__4->Sup.len : 0);
							if (!!((T89_ == L_4))) goto LA90_;
							failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_26));
						}
						LA90_: ;
					} LA85: ;
				}
			}
			nimln_(74, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
			(*isTight) = NIM_FALSE;
			nimln_(75, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
			T92_ = (NimStringDesc*)0;
			T92_ = rawNewString((unOrderedListContainer_2 ? unOrderedListContainer_2->Sup.len : 0) + 11);
appendString(T92_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_33));
appendString(T92_, unOrderedListContainer_2);
appendString(T92_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_34));
			result = T92_;
			goto BeforeRet_;
		}
		break;
		case ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 17):
		{
			NimStringDesc* orderedListContainer;
			NimStringDesc* T104_;
			nimln_(79, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
			(*isTight) = NIM_FALSE;
			orderedListContainer = (NimStringDesc*)0;
			{
				tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ** child_5;
				tySequence__ysZ0yvYJsxyGumT80SPhXQ* colontmp__5;
				NI i_5;
				NI L_5;
				NI T95_;
				child_5 = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ**)0;
				colontmp__5 = (tySequence__ysZ0yvYJsxyGumT80SPhXQ*)0;
				nimln_(81, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
				if (!(((1 &((NU8)1<<((NU)((*mdast).kind)&7U)))!=0))){ raiseFieldError(((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_24)); }
				colontmp__5 = (*mdast)._kind_1.children;
				nimln_(199, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
				i_5 = ((NI) 0);
				nimln_(200, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
				T95_ = (colontmp__5 ? colontmp__5->Sup.len : 0);
				L_5 = T95_;
				{
					nimln_(201, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
					while (1) {
						NimStringDesc* T98_;
						NI TM__kGjlnpr1nHrV9aiehPuIx2A_36;
						if (!(i_5 < L_5)) goto LA97;
						nimln_(81, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
						if ((NU)(i_5) >= (NU)(colontmp__5 ? colontmp__5->Sup.len : 0)){ raiseIndexError2(i_5,(colontmp__5 ? colontmp__5->Sup.len : 0)-1); }
						child_5 = &colontmp__5->data[i_5];
						nimln_(82, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
						T98_ = (NimStringDesc*)0;
						T98_ = astToHtml__H0wjxOIgsXdEfhsSU9aap6Q((*child_5), isTight);
						orderedListContainer = resizeString(orderedListContainer, (T98_ ? T98_->Sup.len : 0) + 0);
appendString(orderedListContainer, T98_);
						nimln_(203, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
						if (nimAddInt(i_5, ((NI) 1), &TM__kGjlnpr1nHrV9aiehPuIx2A_36)) { raiseOverflow(); };
						i_5 = (NI)(TM__kGjlnpr1nHrV9aiehPuIx2A_36);
						nimln_(204, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
						{
							NI T101_;
							T101_ = (colontmp__5 ? colontmp__5->Sup.len : 0);
							if (!!((T101_ == L_5))) goto LA102_;
							failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_26));
						}
						LA102_: ;
					} LA97: ;
				}
			}
			nimln_(83, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
			T104_ = (NimStringDesc*)0;
			T104_ = rawNewString((orderedListContainer ? orderedListContainer->Sup.len : 0) + 11);
appendString(T104_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_37));
appendString(T104_, orderedListContainer);
appendString(T104_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_38));
			result = T104_;
			goto BeforeRet_;
		}
		break;
		case ((tyEnum_BlockType__f0C73Dxca1VbNsCJ9bxzvzQ) 16):
		{
			NimStringDesc* orderedListContainer_2;
			NimStringDesc* T116_;
			nimln_(87, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
			(*isTight) = NIM_TRUE;
			orderedListContainer_2 = (NimStringDesc*)0;
			{
				tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ** child_6;
				tySequence__ysZ0yvYJsxyGumT80SPhXQ* colontmp__6;
				NI i_6;
				NI L_6;
				NI T107_;
				child_6 = (tyObject_BlockObj__Aao0goirPrklcSrQBcoeNQ**)0;
				colontmp__6 = (tySequence__ysZ0yvYJsxyGumT80SPhXQ*)0;
				nimln_(89, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
				if (!(((1 &((NU8)1<<((NU)((*mdast).kind)&7U)))!=0))){ raiseFieldError(((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_24)); }
				colontmp__6 = (*mdast)._kind_1.children;
				nimln_(199, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
				i_6 = ((NI) 0);
				nimln_(200, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
				T107_ = (colontmp__6 ? colontmp__6->Sup.len : 0);
				L_6 = T107_;
				{
					nimln_(201, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
					while (1) {
						NimStringDesc* T110_;
						NI TM__kGjlnpr1nHrV9aiehPuIx2A_39;
						if (!(i_6 < L_6)) goto LA109;
						nimln_(89, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
						if ((NU)(i_6) >= (NU)(colontmp__6 ? colontmp__6->Sup.len : 0)){ raiseIndexError2(i_6,(colontmp__6 ? colontmp__6->Sup.len : 0)-1); }
						child_6 = &colontmp__6->data[i_6];
						nimln_(90, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
						T110_ = (NimStringDesc*)0;
						T110_ = astToHtml__H0wjxOIgsXdEfhsSU9aap6Q((*child_6), isTight);
						orderedListContainer_2 = resizeString(orderedListContainer_2, (T110_ ? T110_->Sup.len : 0) + 0);
appendString(orderedListContainer_2, T110_);
						nimln_(203, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
						if (nimAddInt(i_6, ((NI) 1), &TM__kGjlnpr1nHrV9aiehPuIx2A_39)) { raiseOverflow(); };
						i_6 = (NI)(TM__kGjlnpr1nHrV9aiehPuIx2A_39);
						nimln_(204, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
						{
							NI T113_;
							T113_ = (colontmp__6 ? colontmp__6->Sup.len : 0);
							if (!!((T113_ == L_6))) goto LA114_;
							failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_26));
						}
						LA114_: ;
					} LA109: ;
				}
			}
			nimln_(91, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
			(*isTight) = NIM_FALSE;
			nimln_(92, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
			T116_ = (NimStringDesc*)0;
			T116_ = rawNewString((orderedListContainer_2 ? orderedListContainer_2->Sup.len : 0) + 11);
appendString(T116_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_37));
appendString(T116_, orderedListContainer_2);
appendString(T116_, ((NimStringDesc*) &TM__kGjlnpr1nHrV9aiehPuIx2A_38));
			result = T116_;
			goto BeforeRet_;
		}
		break;
		default:
		{
			nimln_(94, "/home/kyohei/nim/nmark/src/nmarkpkg/private/astToHtml.nim");
			goto BeforeRet_;
		}
		break;
		}
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
