/* Generated by Nim Compiler v1.4.4 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3   -I/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib -I/home/kyohei/nim/nmark/tests -o /home/kyohei/nim/nmark/nimcache/tests/testRegular.nim_0d61f8370cad1d412f80b84d143e1257/stdlib_parseutils.nim.c.o /home/kyohei/nim/nmark/nimcache/tests/testRegular.nim_0d61f8370cad1d412f80b84d143e1257/stdlib_parseutils.nim.c */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;

/* section: NIM_merge_TYPES */
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {
  Exception Sup;
};
struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw {
  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};

/* section: NIM_merge_SEQ_TYPES */
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};

/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NIM_BOOL, nimDivInt)(NI a, NI b, NI* res);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NI, npuParseBiggestInt)(NimStringDesc* s, NI64* number, NI start);
N_LIB_PRIVATE N_NIMCALL(NI, rawParseInt__oz568vhg7PZ19ak9aiwQxGYw)(NimStringDesc* s, NI64* b, NI start);
static N_INLINE(NIM_BOOL, nimDivInt64)(NI64 a, NI64 b, NI64* res);
N_LIB_PRIVATE N_NOINLINE(void, integerOutOfRangeError__urgsblG9a8f3sSX4FE53fig)(void);
N_LIB_PRIVATE N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(void, decRef__AT1eRuflKWyTTBdLjEDZbg_2system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y);
static N_INLINE(NIM_BOOL, ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_3system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__Y66tOYFjgwJ0k4aLz4bc0Q)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem)(void* usr);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__AT1eRuflKWyTTBdLjEDZbgsystem)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___dgYAo7RfdUVVpvkfKDym8w_2system)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);

/* section: NIM_merge_DATA */
extern TNimType NTI__Ie1m0dv1ZHg72IgPRr1cDw_;
extern TNimType NTI__yoNlBGx0D2tRizIdhQuENw_;
STRING_LITERAL(TM__vI9aZNKIcImom6dDyKXW1ZA_18, "Parsed integer outside of valid range", 37);

/* section: NIM_merge_VARS */
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__IcYaEuuWivYAS86vFMTS3Q;

/* section: NIM_merge_PROCS */
static N_INLINE(NIM_BOOL, nimDivInt)(NI a, NI b, NI* res) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T3_)) goto LA4_;
		T3_ = (b == ((NI) -1));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = NIM_TRUE;
	}
	goto LA1_;
	LA5_: ;
	{
		(*res) = (NI)(a / b);
	}
	LA1_: ;
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
N_LIB_PRIVATE N_NIMCALL(NI, parseSaturatedNatural__hGWFPKYRsDcYFCjZLM9acZw)(NimStringDesc* s, NI* b, NI start) {
	NI result;
	NI i;
	nimfr_("parseSaturatedNatural", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
	result = (NI)0;
	nimln_(490, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
	i = start;
	nimln_(491, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
	{
		NIM_BOOL T3_;
		NI TM__vI9aZNKIcImom6dDyKXW1ZA_2;
		T3_ = (NIM_BOOL)0;
		T3_ = (i < (s ? s->Sup.len : 0));
		if (!(T3_)) goto LA4_;
		if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
		T3_ = ((NU8)(s->data[i]) == (NU8)(43));
		LA4_: ;
		if (!T3_) goto LA5_;
		if (nimAddInt(i, ((NI) 1), &TM__vI9aZNKIcImom6dDyKXW1ZA_2)) { raiseOverflow(); };
		i = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_2);
	}
	LA5_: ;
	nimln_(492, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
	{
		NIM_BOOL T9_;
		NI TM__vI9aZNKIcImom6dDyKXW1ZA_10;
		T9_ = (NIM_BOOL)0;
		T9_ = (i < (s ? s->Sup.len : 0));
		if (!(T9_)) goto LA10_;
		if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
		T9_ = (((NU8)(s->data[i])) >= ((NU8)(48)) && ((NU8)(s->data[i])) <= ((NU8)(57)));
		LA10_: ;
		if (!T9_) goto LA11_;
		nimln_(493, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
		(*b) = ((NI) 0);
		{
			nimln_(494, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
			while (1) {
				NIM_BOOL T15_;
				NI c;
				NI TM__vI9aZNKIcImom6dDyKXW1ZA_3;
				NI TM__vI9aZNKIcImom6dDyKXW1ZA_8;
				T15_ = (NIM_BOOL)0;
				T15_ = (i < (s ? s->Sup.len : 0));
				if (!(T15_)) goto LA16_;
				if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
				T15_ = (((NU8)(s->data[i])) >= ((NU8)(48)) && ((NU8)(s->data[i])) <= ((NU8)(57)));
				LA16_: ;
				if (!T15_) goto LA14;
				nimln_(495, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
				if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
				if (nimSubInt(((NU8)(s->data[i])), ((NI) 48), &TM__vI9aZNKIcImom6dDyKXW1ZA_3)) { raiseOverflow(); };
				c = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_3);
				nimln_(496, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
				{
					NI TM__vI9aZNKIcImom6dDyKXW1ZA_4;
					NI TM__vI9aZNKIcImom6dDyKXW1ZA_5;
					NI TM__vI9aZNKIcImom6dDyKXW1ZA_6;
					NI TM__vI9aZNKIcImom6dDyKXW1ZA_7;
					if (nimSubInt(((NI) IL64(9223372036854775807)), c, &TM__vI9aZNKIcImom6dDyKXW1ZA_4)) { raiseOverflow(); };
					if (((NI) 10) == 0){ raiseDivByZero(); }
					if (nimDivInt((NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_4), ((NI) 10), &TM__vI9aZNKIcImom6dDyKXW1ZA_5)) { raiseOverflow(); };
					if (!((*b) <= (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_5))) goto LA19_;
					nimln_(497, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
					if (nimMulInt((*b), ((NI) 10), &TM__vI9aZNKIcImom6dDyKXW1ZA_6)) { raiseOverflow(); };
					if (nimAddInt((NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_6), c, &TM__vI9aZNKIcImom6dDyKXW1ZA_7)) { raiseOverflow(); };
					(*b) = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_7);
				}
				goto LA17_;
				LA19_: ;
				{
					nimln_(499, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
					(*b) = ((NI) IL64(9223372036854775807));
				}
				LA17_: ;
				nimln_(500, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
				if (nimAddInt(i, ((NI) 1), &TM__vI9aZNKIcImom6dDyKXW1ZA_8)) { raiseOverflow(); };
				i = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_8);
				{
					nimln_(501, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
					while (1) {
						NIM_BOOL T24_;
						NI TM__vI9aZNKIcImom6dDyKXW1ZA_9;
						T24_ = (NIM_BOOL)0;
						T24_ = (i < (s ? s->Sup.len : 0));
						if (!(T24_)) goto LA25_;
						if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
						T24_ = ((NU8)(s->data[i]) == (NU8)(95));
						LA25_: ;
						if (!T24_) goto LA23;
						if (nimAddInt(i, ((NI) 1), &TM__vI9aZNKIcImom6dDyKXW1ZA_9)) { raiseOverflow(); };
						i = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_9);
					} LA23: ;
				}
			} LA14: ;
		}
		nimln_(502, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
		if (nimSubInt(i, start, &TM__vI9aZNKIcImom6dDyKXW1ZA_10)) { raiseOverflow(); };
		result = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_10);
	}
	LA11_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDivInt64)(NI64 a, NI64 b, NI64* res) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a == (IL64(-9223372036854775807) - IL64(1)));
		if (!(T3_)) goto LA4_;
		T3_ = (b == IL64(-1));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = NIM_TRUE;
	}
	goto LA1_;
	LA5_: ;
	{
		(*res) = (NI64)(a / b);
	}
	LA1_: ;
	return result;
}
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y) {
	NI result;
	nimfr_("-%", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/arithme"
"tics.nim");
	result = (NI)0;
	nimln_(437, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/arithme"
"tics.nim");
	nimln_(441, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/arithme"
"tics.nim");
	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem)(NI x, NI y) {
	NIM_BOOL result;
	nimfr_("<%", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/compari"
"sons.nim");
	result = (NIM_BOOL)0;
	nimln_(188, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/compari"
"sons.nim");
	nimln_(190, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/compari"
"sons.nim");
	result = ((NU64)(((NU) (x))) < (NU64)(((NU) (y))));
	popFrame();
	return result;
}
static N_INLINE(void, rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_3system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	nimln_(196, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	addZCT__Y66tOYFjgwJ0k4aLz4bc0Q((&gch__IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}
static N_INLINE(void, decRef__AT1eRuflKWyTTBdLjEDZbg_2system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	nimln_(201, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	(*c).refcount = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem((*c).refcount, ((NI) 8));
	nimln_(202, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		nimln_(203, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
		rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_3system(c);
	}
	LA4_: ;
	popFrame();
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	nimfr_("usrToCell", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(130, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	T1_ = (NI)0;
	T1_ = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (usr)), ((NI) 16));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	popFrame();
	return result;
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	nimfr_("nimGCunrefNoCycle", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	nimln_(229, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	T1_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem(p);
	decRef__AT1eRuflKWyTTBdLjEDZbg_2system(T1_);
	popFrame();
}
static N_INLINE(NI, pluspercent___dgYAo7RfdUVVpvkfKDym8w_2system)(NI x, NI y) {
	NI result;
	nimfr_("+%", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/arithme"
"tics.nim");
	result = (NI)0;
	nimln_(426, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/arithme"
"tics.nim");
	nimln_(430, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/arithme"
"tics.nim");
	result = ((NI) ((NU)((NU64)(((NU) (x))) + (NU64)(((NU) (y))))));
	popFrame();
	return result;
}
static N_INLINE(void, incRef__AT1eRuflKWyTTBdLjEDZbgsystem)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	nimln_(184, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	(*c).refcount = pluspercent___dgYAo7RfdUVVpvkfKDym8w_2system((*c).refcount, ((NI) 8));
	popFrame();
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	nimln_(239, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem(src);
		incRef__AT1eRuflKWyTTBdLjEDZbgsystem(T5_);
	}
	LA3_: ;
	nimln_(240, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem((*dest));
		decRef__AT1eRuflKWyTTBdLjEDZbg_2system(T10_);
	}
	LA8_: ;
	nimln_(241, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	(*dest) = src;
	popFrame();
}
N_LIB_PRIVATE N_NOINLINE(void, integerOutOfRangeError__urgsblG9a8f3sSX4FE53fig)(void) {
	tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw* T1_;
	NimStringDesc* T2_;
	nimfr_("integerOutOfRangeError", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
	T1_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*)0;
	T1_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*) newObj((&NTI__Ie1m0dv1ZHg72IgPRr1cDw_), sizeof(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw));
	(*T1_).Sup.Sup.Sup.m_type = (&NTI__yoNlBGx0D2tRizIdhQuENw_);
	(*T1_).Sup.Sup.name = "ValueError";
	T2_ = (NimStringDesc*)0;
	T2_ = (*T1_).Sup.Sup.message; (*T1_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__vI9aZNKIcImom6dDyKXW1ZA_18));
	if (T2_) nimGCunrefNoCycle(T2_);
	asgnRef((void**) (&(*T1_).Sup.Sup.parent), ((Exception*) NIM_NIL));
	nimln_(411, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
	raiseExceptionEx((Exception*)T1_, "ValueError", "integerOutOfRangeError", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim", 411);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NI, rawParseInt__oz568vhg7PZ19ak9aiwQxGYw)(NimStringDesc* s, NI64* b, NI start) {
	NI result;
	NI64 sign;
	NI i;
	nimfr_("rawParseInt", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
	result = (NI)0;
	nimln_(419, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
	sign = IL64(-1);
	nimln_(420, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
	i = start;
	nimln_(421, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
	{
		if (!(i < (s ? s->Sup.len : 0))) goto LA3_;
		nimln_(422, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
		{
			NI TM__vI9aZNKIcImom6dDyKXW1ZA_11;
			if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
			if (!((NU8)(s->data[i]) == (NU8)(43))) goto LA7_;
			if (nimAddInt(i, ((NI) 1), &TM__vI9aZNKIcImom6dDyKXW1ZA_11)) { raiseOverflow(); };
			i = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_11);
		}
		goto LA5_;
		LA7_: ;
		{
			NI TM__vI9aZNKIcImom6dDyKXW1ZA_12;
			nimln_(423, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
			if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
			if (!((NU8)(s->data[i]) == (NU8)(45))) goto LA10_;
			nimln_(424, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
			if (nimAddInt(i, ((NI) 1), &TM__vI9aZNKIcImom6dDyKXW1ZA_12)) { raiseOverflow(); };
			i = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_12);
			nimln_(425, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
			sign = IL64(1);
		}
		goto LA5_;
		LA10_: ;
		LA5_: ;
	}
	LA3_: ;
	nimln_(426, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
	{
		NIM_BOOL T14_;
		T14_ = (NIM_BOOL)0;
		T14_ = (i < (s ? s->Sup.len : 0));
		if (!(T14_)) goto LA15_;
		if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
		T14_ = (((NU8)(s->data[i])) >= ((NU8)(48)) && ((NU8)(s->data[i])) <= ((NU8)(57)));
		LA15_: ;
		if (!T14_) goto LA16_;
		nimln_(427, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
		(*b) = IL64(0);
		{
			nimln_(428, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
			while (1) {
				NIM_BOOL T20_;
				NI c;
				NI TM__vI9aZNKIcImom6dDyKXW1ZA_13;
				NI TM__vI9aZNKIcImom6dDyKXW1ZA_19;
				T20_ = (NIM_BOOL)0;
				T20_ = (i < (s ? s->Sup.len : 0));
				if (!(T20_)) goto LA21_;
				if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
				T20_ = (((NU8)(s->data[i])) >= ((NU8)(48)) && ((NU8)(s->data[i])) <= ((NU8)(57)));
				LA21_: ;
				if (!T20_) goto LA19;
				nimln_(429, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
				if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
				if (nimSubInt(((NU8)(s->data[i])), ((NI) 48), &TM__vI9aZNKIcImom6dDyKXW1ZA_13)) { raiseOverflow(); };
				c = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_13);
				nimln_(430, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
				{
					NI64 TM__vI9aZNKIcImom6dDyKXW1ZA_14;
					NI64 TM__vI9aZNKIcImom6dDyKXW1ZA_15;
					NI64 TM__vI9aZNKIcImom6dDyKXW1ZA_16;
					NI64 TM__vI9aZNKIcImom6dDyKXW1ZA_17;
					if (nimAddInt64((IL64(-9223372036854775807) - IL64(1)), ((NI64) (c)), &TM__vI9aZNKIcImom6dDyKXW1ZA_14)) { raiseOverflow(); };
					if (IL64(10) == 0){ raiseDivByZero(); }
					if (nimDivInt64((NI64)(TM__vI9aZNKIcImom6dDyKXW1ZA_14), IL64(10), &TM__vI9aZNKIcImom6dDyKXW1ZA_15)) { raiseOverflow(); };
					if (!((NI64)(TM__vI9aZNKIcImom6dDyKXW1ZA_15) <= (*b))) goto LA24_;
					nimln_(431, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
					if (nimMulInt64((*b), IL64(10), &TM__vI9aZNKIcImom6dDyKXW1ZA_16)) { raiseOverflow(); };
					if (nimSubInt64((NI64)(TM__vI9aZNKIcImom6dDyKXW1ZA_16), ((NI64) (c)), &TM__vI9aZNKIcImom6dDyKXW1ZA_17)) { raiseOverflow(); };
					(*b) = (NI64)(TM__vI9aZNKIcImom6dDyKXW1ZA_17);
				}
				goto LA22_;
				LA24_: ;
				{
					nimln_(433, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
					integerOutOfRangeError__urgsblG9a8f3sSX4FE53fig();
				}
				LA22_: ;
				nimln_(434, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
				if (nimAddInt(i, ((NI) 1), &TM__vI9aZNKIcImom6dDyKXW1ZA_19)) { raiseOverflow(); };
				i = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_19);
				{
					nimln_(435, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
					while (1) {
						NIM_BOOL T29_;
						NI TM__vI9aZNKIcImom6dDyKXW1ZA_20;
						T29_ = (NIM_BOOL)0;
						T29_ = (i < (s ? s->Sup.len : 0));
						if (!(T29_)) goto LA30_;
						if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
						T29_ = ((NU8)(s->data[i]) == (NU8)(95));
						LA30_: ;
						if (!T29_) goto LA28;
						if (nimAddInt(i, ((NI) 1), &TM__vI9aZNKIcImom6dDyKXW1ZA_20)) { raiseOverflow(); };
						i = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_20);
					} LA28: ;
				}
			} LA19: ;
		}
		nimln_(436, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
		{
			NIM_BOOL T33_;
			T33_ = (NIM_BOOL)0;
			T33_ = (sign == IL64(-1));
			if (!(T33_)) goto LA34_;
			T33_ = ((*b) == (IL64(-9223372036854775807) - IL64(1)));
			LA34_: ;
			if (!T33_) goto LA35_;
			nimln_(437, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
			integerOutOfRangeError__urgsblG9a8f3sSX4FE53fig();
		}
		goto LA31_;
		LA35_: ;
		{
			NI64 TM__vI9aZNKIcImom6dDyKXW1ZA_21;
			NI TM__vI9aZNKIcImom6dDyKXW1ZA_22;
			nimln_(439, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
			if (nimMulInt64((*b), sign, &TM__vI9aZNKIcImom6dDyKXW1ZA_21)) { raiseOverflow(); };
			(*b) = (NI64)(TM__vI9aZNKIcImom6dDyKXW1ZA_21);
			nimln_(440, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
			if (nimSubInt(i, start, &TM__vI9aZNKIcImom6dDyKXW1ZA_22)) { raiseOverflow(); };
			result = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_22);
		}
		LA31_: ;
	}
	LA16_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, npuParseBiggestInt)(NimStringDesc* s, NI64* number, NI start) {
	NI result;
	NI64 res;
	nimfr_("parseBiggestInt", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
	result = (NI)0;
	nimln_(454, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
	res = IL64(0);
	nimln_(457, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
	result = rawParseInt__oz568vhg7PZ19ak9aiwQxGYw(s, (&res), start);
	nimln_(458, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
	{
		if (!!((result == ((NI) 0)))) goto LA3_;
		nimln_(459, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
		(*number) = res;
	}
	LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, npuParseInt)(NimStringDesc* s, NI* number, NI start) {
	NI result;
	NI64 res;
	nimfr_("parseInt", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
	result = (NI)0;
	nimln_(472, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
	res = IL64(0);
	nimln_(473, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
	result = npuParseBiggestInt(s, (&res), start);
	nimln_(477, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
	{
		if (!!((result == ((NI) 0)))) goto LA3_;
		nimln_(478, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
		(*number) = ((NI) (res));
	}
	LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, parseHex__5URmSDed0NZg9au720T3U9aA)(NimStringDesc* s, NI* number, NI start, NI maxLen) {
	NI result;
	NI i;
	NI output;
	NIM_BOOL foundDigit;
	NI last;
	NI T1_;
	nimfr_("parseHex", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
	result = (NI)0;
	nimln_(187, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
	i = start;
	nimln_(188, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
	output = ((NI) 0);
	nimln_(189, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
	foundDigit = NIM_FALSE;
	nimln_(190, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
	T1_ = (NI)0;
	{
		if (!(maxLen == ((NI) 0))) goto LA4_;
		T1_ = (s ? s->Sup.len : 0);
	}
	goto LA2_;
	LA4_: ;
	{
		NI TM__vI9aZNKIcImom6dDyKXW1ZA_23;
		if (nimAddInt(i, maxLen, &TM__vI9aZNKIcImom6dDyKXW1ZA_23)) { raiseOverflow(); };
		T1_ = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_23);
	}
	LA2_: ;
	last = (((s ? s->Sup.len : 0) <= T1_) ? (s ? s->Sup.len : 0) : T1_);
	nimln_(191, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
	{
		NIM_BOOL T9_;
		NIM_BOOL T10_;
		NI TM__vI9aZNKIcImom6dDyKXW1ZA_24;
		NI TM__vI9aZNKIcImom6dDyKXW1ZA_25;
		NI TM__vI9aZNKIcImom6dDyKXW1ZA_26;
		T9_ = (NIM_BOOL)0;
		T10_ = (NIM_BOOL)0;
		if (nimAddInt(i, ((NI) 1), &TM__vI9aZNKIcImom6dDyKXW1ZA_24)) { raiseOverflow(); };
		T10_ = ((NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_24) < last);
		if (!(T10_)) goto LA11_;
		if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
		T10_ = ((NU8)(s->data[i]) == (NU8)(48));
		LA11_: ;
		T9_ = T10_;
		if (!(T9_)) goto LA12_;
		if (nimAddInt(i, ((NI) 1), &TM__vI9aZNKIcImom6dDyKXW1ZA_25)) { raiseOverflow(); };
		if ((NU)((NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_25)) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2((NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_25),(s ? s->Sup.len : 0)-1); }
		T9_ = (((NU8)(s->data[(NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_25)])) == ((NU8)(120)) || ((NU8)(s->data[(NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_25)])) == ((NU8)(88)));
		LA12_: ;
		if (!T9_) goto LA13_;
		if (nimAddInt(i, ((NI) 2), &TM__vI9aZNKIcImom6dDyKXW1ZA_26)) { raiseOverflow(); };
		i = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_26);
	}
	goto LA7_;
	LA13_: ;
	{
		NIM_BOOL T16_;
		NI TM__vI9aZNKIcImom6dDyKXW1ZA_27;
		nimln_(192, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
		T16_ = (NIM_BOOL)0;
		T16_ = (i < last);
		if (!(T16_)) goto LA17_;
		if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
		T16_ = ((NU8)(s->data[i]) == (NU8)(35));
		LA17_: ;
		if (!T16_) goto LA18_;
		if (nimAddInt(i, ((NI) 1), &TM__vI9aZNKIcImom6dDyKXW1ZA_27)) { raiseOverflow(); };
		i = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_27);
	}
	goto LA7_;
	LA18_: ;
	LA7_: ;
	{
		nimln_(193, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
		while (1) {
			NI TM__vI9aZNKIcImom6dDyKXW1ZA_33;
			if (!(i < last)) goto LA21;
			nimln_(194, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
			if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
			switch (((NU8)(s->data[i]))) {
			case 95:
			{
			}
			break;
			case 48 ... 57:
			{
				NI TM__vI9aZNKIcImom6dDyKXW1ZA_28;
				nimln_(197, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
				if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
				if (nimSubInt(((NU8)(s->data[i])), ((NI) 48), &TM__vI9aZNKIcImom6dDyKXW1ZA_28)) { raiseOverflow(); };
				output = (NI)((NI)((NU64)(output) << (NU64)(((NI) 4))) | (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_28));
				nimln_(198, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
				foundDigit = NIM_TRUE;
			}
			break;
			case 97 ... 102:
			{
				NI TM__vI9aZNKIcImom6dDyKXW1ZA_29;
				NI TM__vI9aZNKIcImom6dDyKXW1ZA_30;
				nimln_(200, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
				if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
				if (nimSubInt(((NU8)(s->data[i])), ((NI) 97), &TM__vI9aZNKIcImom6dDyKXW1ZA_29)) { raiseOverflow(); };
				if (nimAddInt((NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_29), ((NI) 10), &TM__vI9aZNKIcImom6dDyKXW1ZA_30)) { raiseOverflow(); };
				output = (NI)((NI)((NU64)(output) << (NU64)(((NI) 4))) | (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_30));
				nimln_(201, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
				foundDigit = NIM_TRUE;
			}
			break;
			case 65 ... 70:
			{
				NI TM__vI9aZNKIcImom6dDyKXW1ZA_31;
				NI TM__vI9aZNKIcImom6dDyKXW1ZA_32;
				nimln_(203, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
				if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
				if (nimSubInt(((NU8)(s->data[i])), ((NI) 65), &TM__vI9aZNKIcImom6dDyKXW1ZA_31)) { raiseOverflow(); };
				if (nimAddInt((NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_31), ((NI) 10), &TM__vI9aZNKIcImom6dDyKXW1ZA_32)) { raiseOverflow(); };
				output = (NI)((NI)((NU64)(output) << (NU64)(((NI) 4))) | (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_32));
				nimln_(204, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
				foundDigit = NIM_TRUE;
			}
			break;
			default:
			{
				nimln_(205, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
				goto LA20;
			}
			break;
			}
			nimln_(206, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
			if (nimAddInt(i, ((NI) 1), &TM__vI9aZNKIcImom6dDyKXW1ZA_33)) { raiseOverflow(); };
			i = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_33);
		} LA21: ;
	} LA20: ;
	nimln_(207, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
	{
		NI TM__vI9aZNKIcImom6dDyKXW1ZA_34;
		if (!foundDigit) goto LA29_;
		nimln_(208, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
		(*number) = output;
		nimln_(209, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/parseutil"
"s.nim");
		if (nimSubInt(i, start, &TM__vI9aZNKIcImom6dDyKXW1ZA_34)) { raiseOverflow(); };
		result = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_34);
	}
	LA29_: ;
	popFrame();
	return result;
}
