/* Generated by Nim Compiler v1.4.4 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3   -I/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib -I/home/kyohei/nim/nmark/tests -o /home/kyohei/nim/nmark/nimcache/tests/testRegular.nim_0d61f8370cad1d412f80b84d143e1257/stdlib_re.nim.c.o /home/kyohei/nim/nmark/nimcache/tests/testRegular.nim_0d61f8370cad1d412f80b84d143e1257/stdlib_re.nim.c */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw;
typedef struct tyObject_Pcre__bGVj3RgRlNY6kwJpiYI9b3A tyObject_Pcre__bGVj3RgRlNY6kwJpiYI9b3A;
typedef struct tyObject_ExtraData__aRbi7557vgG4KV47nk1CWQ tyObject_ExtraData__aRbi7557vgG4KV47nk1CWQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_RegexError__eXUKe0yimErFvWt9bGtwijw tyObject_RegexError__eXUKe0yimErFvWt9bGtwijw;
typedef struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_RtArray__3dAfOhmMnD56kQD3eeo0Lg tyObject_RtArray__3dAfOhmMnD56kQD3eeo0Lg;
typedef struct tySequence__9apztJSmgERYU8fZOjI4pOg tySequence__9apztJSmgERYU8fZOjI4pOg;
typedef struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;

/* section: NIM_merge_TYPES */
struct tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw {
tyObject_Pcre__bGVj3RgRlNY6kwJpiYI9b3A* h;
tyObject_ExtraData__aRbi7557vgG4KV47nk1CWQ* e;
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tySet_tyEnum_RegexFlag__gA189bEOtGhLt2cCHGW4ywg;
typedef N_CDECL_PTR(void, tyProc__5cp59bim9aJ4WupX5aVaD1Sg) (NCSTRING stringptr);
typedef N_CDECL_PTR(void, tyProc__hMR3nXvmHGbyZzcDul78bg) (tyObject_ExtraData__aRbi7557vgG4KV47nk1CWQ* extra);
struct tyObject_Pcre__bGVj3RgRlNY6kwJpiYI9b3A {
char dummy;
};
typedef N_CDECL_PTR(tyObject_Pcre__bGVj3RgRlNY6kwJpiYI9b3A*, tyProc__OMNNRjh8IIE9bAc9btZcg0NA) (NCSTRING pattern, int options, NCSTRING* errptr, int* erroffset, void* tableptr);
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {
  Exception Sup;
};
struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw {
  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;
};
struct tyObject_RegexError__eXUKe0yimErFvWt9bGtwijw {
  tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw Sup;
};
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NU8 tyEnum_RegexFlag__gA189bEOtGhLt2cCHGW4ywg;
typedef N_CDECL_PTR(int, tyProc__KqPl2ltkjnSoyb04zAVCAQ) (int what, void* where);
struct tyObject_ExtraData__aRbi7557vgG4KV47nk1CWQ {
long flags;
void* study_data;
long match_limit;
void* callout_data;
void* tables;
long match_limit_recursion;
void* mark;
void* executable_jit;
};
typedef N_CDECL_PTR(tyObject_ExtraData__aRbi7557vgG4KV47nk1CWQ*, tyProc__qU2uMIyWirSwn1Nd4hJjDw) (tyObject_Pcre__bGVj3RgRlNY6kwJpiYI9b3A* code, int options, NCSTRING* errptr);
typedef int tyArray__hlIpJIfs8ECqDyETXoMStg[10];
struct tyObject_RtArray__3dAfOhmMnD56kQD3eeo0Lg {
NI L;
tySequence__9apztJSmgERYU8fZOjI4pOg* spart;
tyArray__hlIpJIfs8ECqDyETXoMStg apart;
};
typedef N_CDECL_PTR(int, tyProc__y4Iy0gL1MDnSGVt43uUAgQ) (tyObject_Pcre__bGVj3RgRlNY6kwJpiYI9b3A* code, tyObject_ExtraData__aRbi7557vgG4KV47nk1CWQ* extra, NCSTRING subject, int length, int startoffset, int options, int* ovector, int ovecsize);
struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};

/* section: NIM_merge_SEQ_TYPES */
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
struct tySequence__9apztJSmgERYU8fZOjI4pOg {
  TGenericSeq Sup;
  int data[SEQ_DECL_SIZE];
};

/* section: NIM_merge_PROC_HEADERS */
static N_NIMCALL(void, Marker_tyRef__dkhOdInu11QXB2HnNpgmJQ)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void, finalizeRegEx__4SdnqaehCmfUiW6zxHfMFw)(tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* x);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(tyObject_Pcre__bGVj3RgRlNY6kwJpiYI9b3A*, rawCompile__rlKpWhYxks9aCWeSwmjOpCA)(NimStringDesc* pattern, int flags);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s);
N_LIB_PRIVATE N_NOINLINE(void, raiseInvalidRegex__TdB6gTnZgnp1MW3lpWDu3w)(NimStringDesc* msg) __attribute__((noreturn));
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef__9aOkmtaUNuD5bHWcVuLdIoQ)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(void, decRef__AT1eRuflKWyTTBdLjEDZbg_2system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y);
static N_INLINE(NIM_BOOL, ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_3system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__Y66tOYFjgwJ0k4aLz4bc0Q)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem)(void* usr);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
static N_INLINE(NimStringDesc*, spaces__rssDy7zs9cDeoYTeCoIy0Wgstrutils)(NI n);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NIM_CHAR c, NI count);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(void, initRtArray__dgRhxurJYSkIc9bzLmhcMfQ)(NI len, tyObject_RtArray__3dAfOhmMnD56kQD3eeo0Lg* Result);
N_LIB_PRIVATE N_NIMCALL(int*, getRawData__P13NCPA0zhaXrvo9bVrTd9bw)(tyObject_RtArray__3dAfOhmMnD56kQD3eeo0Lg* x);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ, findBounds__ZvBW7oBQW0AL9bVNHeQYhIQre)(NimStringDesc* s, tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start);
N_LIB_PRIVATE N_NIMCALL(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ, findBounds__h9bDVC3slPvpTdoiuHp3Q2A)(NCSTRING buf, tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start, NI bufSize);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, substr__2yh9cer0ymNRHlOOg8P7IuA)(NimStringDesc* s, NI first, NI last);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, substr__iGg0RIKceRvsmvq8FUHOEw)(NimStringDesc* s, NI first);

/* section: NIM_merge_DATA */
N_LIB_PRIVATE TNimType NTI__jxMAPyr9aBYX9b0g7iZ2E8zw_;
extern TNimType NTI__WH9aVfHDhtZbU6Y5QgauqZQ_;
extern TNimType NTI__z1uZWlkSdiDfd9ahW9a6Ibug_;
N_LIB_PRIVATE TNimType NTI__dkhOdInu11QXB2HnNpgmJQ_;
extern TNimType NTI__yoNlBGx0D2tRizIdhQuENw_;
N_LIB_PRIVATE TNimType NTI__eXUKe0yimErFvWt9bGtwijw_;
N_LIB_PRIVATE TNimType NTI__9aOkmtaUNuD5bHWcVuLdIoQ_;
STRING_LITERAL(TM__EFUBs0zJOEvQ2SEKsixA2w_3, "\012", 1);
STRING_LITERAL(TM__EFUBs0zJOEvQ2SEKsixA2w_4, "^\012", 2);

/* section: NIM_merge_VARS */
extern tyProc__5cp59bim9aJ4WupX5aVaD1Sg Dl_17912304_;
extern tyProc__hMR3nXvmHGbyZzcDul78bg Dl_17912371_;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyProc__OMNNRjh8IIE9bAc9btZcg0NA Dl_17912214_;
extern tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__IcYaEuuWivYAS86vFMTS3Q;
extern tyProc__KqPl2ltkjnSoyb04zAVCAQ Dl_17912236_;
extern tyProc__qU2uMIyWirSwn1Nd4hJjDw Dl_17912363_;
extern tyProc__y4Iy0gL1MDnSGVt43uUAgQ Dl_17912276_;

/* section: NIM_merge_PROCS */
static N_NIMCALL(void, Marker_tyRef__dkhOdInu11QXB2HnNpgmJQ)(void* p, NI op) {
	tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* a;
	a = (tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw*)p;
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, finalizeRegEx__4SdnqaehCmfUiW6zxHfMFw)(tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* x) {
	nimfr_("finalizeRegEx", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	nimln_(84, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	Dl_17912304_(((NCSTRING) ((*x).h)));
	nimln_(85, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	{
		if (!!(((*x).e == 0))) goto LA3_;
		nimln_(86, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
		Dl_17912371_((*x).e);
	}
	LA3_: ;
	popFrame();
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (s == ((NimStringDesc*) NIM_NIL));
		if (T3_) goto LA4_;
		T3_ = ((*s).Sup.len == ((NI) 0));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = "";
	}
	goto LA1_;
	LA5_: ;
	{
		result = ((NCSTRING) ((*s).data));
	}
	LA1_: ;
	return result;
}
static N_NIMCALL(void, Marker_tyRef__9aOkmtaUNuD5bHWcVuLdIoQ)(void* p, NI op) {
	tyObject_RegexError__eXUKe0yimErFvWt9bGtwijw* a;
	a = (tyObject_RegexError__eXUKe0yimErFvWt9bGtwijw*)p;
	nimGCvisit((void*)(*a).Sup.Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.up, op);
}
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y) {
	NI result;
	nimfr_("-%", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/arithme"
"tics.nim");
	result = (NI)0;
	nimln_(437, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/arithme"
"tics.nim");
	nimln_(441, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/arithme"
"tics.nim");
	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem)(NI x, NI y) {
	NIM_BOOL result;
	nimfr_("<%", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/compari"
"sons.nim");
	result = (NIM_BOOL)0;
	nimln_(188, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/compari"
"sons.nim");
	nimln_(190, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/compari"
"sons.nim");
	result = ((NU64)(((NU) (x))) < (NU64)(((NU) (y))));
	popFrame();
	return result;
}
static N_INLINE(void, rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_3system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	nimln_(196, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	addZCT__Y66tOYFjgwJ0k4aLz4bc0Q((&gch__IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}
static N_INLINE(void, decRef__AT1eRuflKWyTTBdLjEDZbg_2system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	nimln_(201, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	(*c).refcount = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem((*c).refcount, ((NI) 8));
	nimln_(202, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		nimln_(203, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
		rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_3system(c);
	}
	LA4_: ;
	popFrame();
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	nimfr_("usrToCell", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(130, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	T1_ = (NI)0;
	T1_ = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (usr)), ((NI) 16));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	popFrame();
	return result;
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	nimfr_("nimGCunrefNoCycle", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	nimln_(229, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	T1_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem(p);
	decRef__AT1eRuflKWyTTBdLjEDZbg_2system(T1_);
	popFrame();
}
N_LIB_PRIVATE N_NOINLINE(void, raiseInvalidRegex__TdB6gTnZgnp1MW3lpWDu3w)(NimStringDesc* msg) {
	tyObject_RegexError__eXUKe0yimErFvWt9bGtwijw* e;
	NimStringDesc* T1_;
	nimfr_("raiseInvalidRegex", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	e = (tyObject_RegexError__eXUKe0yimErFvWt9bGtwijw*)0;
	nimln_(68, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	e = (tyObject_RegexError__eXUKe0yimErFvWt9bGtwijw*) newObj((&NTI__9aOkmtaUNuD5bHWcVuLdIoQ_), sizeof(tyObject_RegexError__eXUKe0yimErFvWt9bGtwijw));
	(*e).Sup.Sup.Sup.Sup.m_type = (&NTI__eXUKe0yimErFvWt9bGtwijw_);
	(*e).Sup.Sup.Sup.name = "RegexError";
	nimln_(69, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = (*e).Sup.Sup.Sup.message; (*e).Sup.Sup.Sup.message = copyStringRC1(msg);
	if (T1_) nimGCunrefNoCycle(T1_);
	nimln_(70, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	raiseExceptionEx((Exception*)e, "RegexError", "raiseInvalidRegex", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim", 70);
	popFrame();
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__i80o3k0SgEI5gTRCzYdyWAsystem(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
static N_INLINE(NimStringDesc*, spaces__rssDy7zs9cDeoYTeCoIy0Wgstrutils)(NI n) {
	NimStringDesc* result;
	nimfr_("spaces", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/strutils."
"nim");
	result = (NimStringDesc*)0;
	nimln_(1381, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/strutils."
"nim");
	nimln_(1398, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/strutils."
"nim");
	result = nsuRepeatChar(32, n);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Pcre__bGVj3RgRlNY6kwJpiYI9b3A*, rawCompile__rlKpWhYxks9aCWeSwmjOpCA)(NimStringDesc* pattern, int flags) {
	tyObject_Pcre__bGVj3RgRlNY6kwJpiYI9b3A* result;
	NCSTRING msg;
	int offset;
	nimfr_("rawCompile", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	result = (tyObject_Pcre__bGVj3RgRlNY6kwJpiYI9b3A*)0;
	nimln_(74, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	msg = "";
	nimln_(75, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	offset = ((int) 0);
	nimln_(76, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	result = Dl_17912214_(nimToCStringConv(pattern), flags, (&msg), (&offset), NIM_NIL);
	nimln_(77, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	{
		NimStringDesc* T5_;
		NimStringDesc* T6_;
		NimStringDesc* T7_;
		if (!(result == ((tyObject_Pcre__bGVj3RgRlNY6kwJpiYI9b3A*) NIM_NIL))) goto LA3_;
		nimln_(78, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
		T5_ = (NimStringDesc*)0;
		T6_ = (NimStringDesc*)0;
		T6_ = cstrToNimstr(msg);
		if ((offset) < ((NI) 0) || (offset) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(offset, ((NI) 0), ((NI) IL64(9223372036854775807))); }
		T7_ = (NimStringDesc*)0;
		T7_ = spaces__rssDy7zs9cDeoYTeCoIy0Wgstrutils(((NI) (offset)));
		T5_ = rawNewString((T6_ ? T6_->Sup.len : 0) + (pattern ? pattern->Sup.len : 0) + (T7_ ? T7_->Sup.len : 0) + 4);
appendString(T5_, T6_);
appendString(T5_, ((NimStringDesc*) &TM__EFUBs0zJOEvQ2SEKsixA2w_3));
appendString(T5_, pattern);
appendString(T5_, ((NimStringDesc*) &TM__EFUBs0zJOEvQ2SEKsixA2w_3));
appendString(T5_, T7_);
appendString(T5_, ((NimStringDesc*) &TM__EFUBs0zJOEvQ2SEKsixA2w_4));
		raiseInvalidRegex__TdB6gTnZgnp1MW3lpWDu3w(T5_);
	}
	LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw*, re__BHdoI8AriYxT9bGXrX9c7EhQ)(NimStringDesc* s, tySet_tyEnum_RegexFlag__gA189bEOtGhLt2cCHGW4ywg flags) {
	tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* result;
	nimfr_("re", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	result = (tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw*)0;
	nimln_(101, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	result = (tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw*) newObj((&NTI__dkhOdInu11QXB2HnNpgmJQ_), sizeof(tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw));
	nimln_(102, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	(*result).h = rawCompile__rlKpWhYxks9aCWeSwmjOpCA(s, ((int) ((flags & ~ 16))));
	nimln_(103, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	{
		NCSTRING msg;
		int options;
		int hasJit;
		if (!((flags &((NU8)1<<((NU)(((tyEnum_RegexFlag__gA189bEOtGhLt2cCHGW4ywg) 4))&7U)))!=0)) goto LA3_;
		nimln_(104, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
		msg = "";
		nimln_(105, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
		options = ((int) 0);
		nimln_(106, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
		hasJit = ((int) 0);
		nimln_(107, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
		{
			int T7_;
			T7_ = (int)0;
			T7_ = Dl_17912236_(((int) 9), ((void*) ((&hasJit))));
			if (!(T7_ == ((NI32) 0))) goto LA8_;
			nimln_(108, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
			{
				if (!(hasJit == ((NI32) 1))) goto LA12_;
				nimln_(109, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
				options = ((int) 1);
			}
			LA12_: ;
		}
		LA8_: ;
		nimln_(110, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
		(*result).e = Dl_17912363_((*result).h, options, (&msg));
		nimln_(111, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
		{
			NimStringDesc* T18_;
			if (!!((msg == 0))) goto LA16_;
			T18_ = (NimStringDesc*)0;
			T18_ = cstrToNimstr(msg);
			raiseInvalidRegex__TdB6gTnZgnp1MW3lpWDu3w(T18_);
		}
		LA16_: ;
	}
	LA3_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory(p, ((int) 0), size);
}
N_LIB_PRIVATE N_NIMCALL(int, matchOrFind__jpcUBS27e6bot0QabDwvkw)(NCSTRING buf, tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start, NI bufSize, int flags) {
	int result;
	tyObject_RtArray__3dAfOhmMnD56kQD3eeo0Lg rtarray;
	int* rawMatches;
	nimfr_("matchOrFind", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	result = (int)0;
	nimZeroMem((void*)(&rtarray), sizeof(tyObject_RtArray__3dAfOhmMnD56kQD3eeo0Lg));
	nimln_(227, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	initRtArray__dgRhxurJYSkIc9bzLmhcMfQ(((NI) 3), (&rtarray));
	nimln_(228, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	rawMatches = getRawData__P13NCPA0zhaXrvo9bVrTd9bw((&rtarray));
	nimln_(229, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	if ((bufSize) < ((int) (-2147483647 -1)) || (bufSize) > ((int) 2147483647)){ raiseRangeErrorI(bufSize, ((int) (-2147483647 -1)), ((int) 2147483647)); }
	if ((start) < ((int) (-2147483647 -1)) || (start) > ((int) 2147483647)){ raiseRangeErrorI(start, ((int) (-2147483647 -1)), ((int) 2147483647)); }
	result = Dl_17912276_((*pattern).h, (*pattern).e, buf, ((int) (bufSize)), ((int) (start)), flags, ((int*) (rawMatches)), ((int) 3));
	nimln_(231, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	{
		NI TM__EFUBs0zJOEvQ2SEKsixA2w_5;
		if (!(((NI32) 0) <= result)) goto LA3_;
		nimln_(232, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
		if (nimSubInt(rawMatches[((NI) 1)], rawMatches[((NI) 0)], &TM__EFUBs0zJOEvQ2SEKsixA2w_5)) { raiseOverflow(); };
		if (TM__EFUBs0zJOEvQ2SEKsixA2w_5 < (-2147483647 -1) || TM__EFUBs0zJOEvQ2SEKsixA2w_5 > 2147483647){ raiseOverflow(); }
		result = (NI32)(TM__EFUBs0zJOEvQ2SEKsixA2w_5);
	}
	LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ, findBounds__h9bDVC3slPvpTdoiuHp3Q2A)(NCSTRING buf, tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start, NI bufSize) {
	tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ result;
	tyObject_RtArray__3dAfOhmMnD56kQD3eeo0Lg rtarray;
	int* rawMatches;
	int res;
	NI colontmp__3;
	NI colontmp__4;
	NI TM__EFUBs0zJOEvQ2SEKsixA2w_6;
	nimfr_("findBounds", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
{	nimZeroMem((void*)(&result), sizeof(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ));
	nimZeroMem((void*)(&rtarray), sizeof(tyObject_RtArray__3dAfOhmMnD56kQD3eeo0Lg));
	nimln_(208, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	initRtArray__dgRhxurJYSkIc9bzLmhcMfQ(((NI) 3), (&rtarray));
	nimln_(209, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	rawMatches = getRawData__P13NCPA0zhaXrvo9bVrTd9bw((&rtarray));
	nimln_(210, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	if ((bufSize) < ((int) (-2147483647 -1)) || (bufSize) > ((int) 2147483647)){ raiseRangeErrorI(bufSize, ((int) (-2147483647 -1)), ((int) 2147483647)); }
	if ((start) < ((int) (-2147483647 -1)) || (start) > ((int) 2147483647)){ raiseRangeErrorI(start, ((int) (-2147483647 -1)), ((int) 2147483647)); }
	res = Dl_17912276_((*pattern).h, (*pattern).e, buf, ((int) (bufSize)), ((int) (start)), ((NI32) 0), ((int*) (rawMatches)), ((int) 3));
	nimln_(212, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	{
		NI colontmp_;
		NI colontmp__2;
		if (!(res < ((NI32) 0))) goto LA3_;
		colontmp_ = ((NI) (res));
		colontmp__2 = ((NI) 0);
		result.Field0 = colontmp_;
		result.Field1 = colontmp__2;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(213, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	colontmp__3 = ((NI) (rawMatches[((NI) 0)]));
	if (nimSubInt(rawMatches[((NI) 1)], ((NI32) 1), &TM__EFUBs0zJOEvQ2SEKsixA2w_6)) { raiseOverflow(); };
	if (TM__EFUBs0zJOEvQ2SEKsixA2w_6 < (-2147483647 -1) || TM__EFUBs0zJOEvQ2SEKsixA2w_6 > 2147483647){ raiseOverflow(); }
	colontmp__4 = ((NI) ((NI32)(TM__EFUBs0zJOEvQ2SEKsixA2w_6)));
	result.Field0 = colontmp__3;
	result.Field1 = colontmp__4;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ, findBounds__ZvBW7oBQW0AL9bVNHeQYhIQre)(NimStringDesc* s, tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start) {
	tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ result;
	nimfr_("findBounds", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	nimZeroMem((void*)(&result), sizeof(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ));
	nimln_(223, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	result = findBounds__h9bDVC3slPvpTdoiuHp3Q2A(nimToCStringConv(s), pattern, start, (s ? s->Sup.len : 0));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, replace__xph9cKzqe9aWKZ0mnKnfmGHg)(NimStringDesc* s, tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw* sub, NimStringDesc* by) {
	NimStringDesc* result;
	NI prev;
	NimStringDesc* T12_;
	nimfr_("replace", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	result = (NimStringDesc*)0;
	nimln_(437, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	result = ((NimStringDesc*) NIM_NIL);
	nimln_(438, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	prev = ((NI) 0);
	{
		nimln_(439, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
		while (1) {
			tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ match;
			NI TM__EFUBs0zJOEvQ2SEKsixA2w_7;
			NimStringDesc* T7_;
			NI TM__EFUBs0zJOEvQ2SEKsixA2w_9;
			if (!(prev < (s ? s->Sup.len : 0))) goto LA2;
			nimln_(440, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
			match = findBounds__ZvBW7oBQW0AL9bVNHeQYhIQre(s, sub, prev);
			nimln_(441, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
			{
				if (!(match.Field0 < ((NI) 0))) goto LA5_;
				goto LA1;
			}
			LA5_: ;
			nimln_(442, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
			if (nimSubInt(match.Field0, ((NI) 1), &TM__EFUBs0zJOEvQ2SEKsixA2w_7)) { raiseOverflow(); };
			T7_ = (NimStringDesc*)0;
			T7_ = substr__2yh9cer0ymNRHlOOg8P7IuA(s, prev, (NI)(TM__EFUBs0zJOEvQ2SEKsixA2w_7));
			result = resizeString(result, (T7_ ? T7_->Sup.len : 0) + 0);
appendString(result, T7_);
			nimln_(443, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
			result = resizeString(result, (by ? by->Sup.len : 0) + 0);
appendString(result, by);
			nimln_(444, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
			{
				NI TM__EFUBs0zJOEvQ2SEKsixA2w_8;
				if (nimAddInt(match.Field1, ((NI) 1), &TM__EFUBs0zJOEvQ2SEKsixA2w_8)) { raiseOverflow(); };
				if (!((NI)(TM__EFUBs0zJOEvQ2SEKsixA2w_8) == prev)) goto LA10_;
				goto LA1;
			}
			LA10_: ;
			nimln_(445, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
			if (nimAddInt(match.Field1, ((NI) 1), &TM__EFUBs0zJOEvQ2SEKsixA2w_9)) { raiseOverflow(); };
			prev = (NI)(TM__EFUBs0zJOEvQ2SEKsixA2w_9);
		} LA2: ;
	} LA1: ;
	nimln_(446, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/impure/re.nim");
	T12_ = (NimStringDesc*)0;
	T12_ = substr__iGg0RIKceRvsmvq8FUHOEw(s, prev);
	result = resizeString(result, (T12_ ? T12_->Sup.len : 0) + 0);
appendString(result, T12_);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_reDatInit000)(void) {

/* section: NIM_merge_TYPE_INIT1 */
static TNimNode* TM__EFUBs0zJOEvQ2SEKsixA2w_2_2[2];
static TNimNode TM__EFUBs0zJOEvQ2SEKsixA2w_0[4];

/* section: NIM_merge_TYPE_INIT3 */
NTI__jxMAPyr9aBYX9b0g7iZ2E8zw_.size = sizeof(tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw);
NTI__jxMAPyr9aBYX9b0g7iZ2E8zw_.align = NIM_ALIGNOF(tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw);
NTI__jxMAPyr9aBYX9b0g7iZ2E8zw_.kind = 18;
NTI__jxMAPyr9aBYX9b0g7iZ2E8zw_.base = 0;
NTI__jxMAPyr9aBYX9b0g7iZ2E8zw_.flags = 3;
TM__EFUBs0zJOEvQ2SEKsixA2w_2_2[0] = &TM__EFUBs0zJOEvQ2SEKsixA2w_0[1];
TM__EFUBs0zJOEvQ2SEKsixA2w_0[1].kind = 1;
TM__EFUBs0zJOEvQ2SEKsixA2w_0[1].offset = offsetof(tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw, h);
TM__EFUBs0zJOEvQ2SEKsixA2w_0[1].typ = (&NTI__WH9aVfHDhtZbU6Y5QgauqZQ_);
TM__EFUBs0zJOEvQ2SEKsixA2w_0[1].name = "h";
TM__EFUBs0zJOEvQ2SEKsixA2w_2_2[1] = &TM__EFUBs0zJOEvQ2SEKsixA2w_0[2];
TM__EFUBs0zJOEvQ2SEKsixA2w_0[2].kind = 1;
TM__EFUBs0zJOEvQ2SEKsixA2w_0[2].offset = offsetof(tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw, e);
TM__EFUBs0zJOEvQ2SEKsixA2w_0[2].typ = (&NTI__z1uZWlkSdiDfd9ahW9a6Ibug_);
TM__EFUBs0zJOEvQ2SEKsixA2w_0[2].name = "e";
TM__EFUBs0zJOEvQ2SEKsixA2w_0[0].len = 2; TM__EFUBs0zJOEvQ2SEKsixA2w_0[0].kind = 2; TM__EFUBs0zJOEvQ2SEKsixA2w_0[0].sons = &TM__EFUBs0zJOEvQ2SEKsixA2w_2_2[0];
NTI__jxMAPyr9aBYX9b0g7iZ2E8zw_.node = &TM__EFUBs0zJOEvQ2SEKsixA2w_0[0];
NTI__dkhOdInu11QXB2HnNpgmJQ_.size = sizeof(tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw*);
NTI__dkhOdInu11QXB2HnNpgmJQ_.align = NIM_ALIGNOF(tyObject_RegexDesc__jxMAPyr9aBYX9b0g7iZ2E8zw*);
NTI__dkhOdInu11QXB2HnNpgmJQ_.kind = 22;
NTI__dkhOdInu11QXB2HnNpgmJQ_.base = (&NTI__jxMAPyr9aBYX9b0g7iZ2E8zw_);
NTI__dkhOdInu11QXB2HnNpgmJQ_.flags = 2;
NTI__dkhOdInu11QXB2HnNpgmJQ_.marker = Marker_tyRef__dkhOdInu11QXB2HnNpgmJQ;
(&NTI__dkhOdInu11QXB2HnNpgmJQ_)->finalizer = (void*)finalizeRegEx__4SdnqaehCmfUiW6zxHfMFw;
NTI__eXUKe0yimErFvWt9bGtwijw_.size = sizeof(tyObject_RegexError__eXUKe0yimErFvWt9bGtwijw);
NTI__eXUKe0yimErFvWt9bGtwijw_.align = NIM_ALIGNOF(tyObject_RegexError__eXUKe0yimErFvWt9bGtwijw);
NTI__eXUKe0yimErFvWt9bGtwijw_.kind = 17;
NTI__eXUKe0yimErFvWt9bGtwijw_.base = (&NTI__yoNlBGx0D2tRizIdhQuENw_);
TM__EFUBs0zJOEvQ2SEKsixA2w_0[3].len = 0; TM__EFUBs0zJOEvQ2SEKsixA2w_0[3].kind = 2;
NTI__eXUKe0yimErFvWt9bGtwijw_.node = &TM__EFUBs0zJOEvQ2SEKsixA2w_0[3];
NTI__9aOkmtaUNuD5bHWcVuLdIoQ_.size = sizeof(tyObject_RegexError__eXUKe0yimErFvWt9bGtwijw*);
NTI__9aOkmtaUNuD5bHWcVuLdIoQ_.align = NIM_ALIGNOF(tyObject_RegexError__eXUKe0yimErFvWt9bGtwijw*);
NTI__9aOkmtaUNuD5bHWcVuLdIoQ_.kind = 22;
NTI__9aOkmtaUNuD5bHWcVuLdIoQ_.base = (&NTI__eXUKe0yimErFvWt9bGtwijw_);
NTI__9aOkmtaUNuD5bHWcVuLdIoQ_.marker = Marker_tyRef__9aOkmtaUNuD5bHWcVuLdIoQ;
}

