/* Generated by Nim Compiler v1.4.4 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3   -I/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib -I/home/kyohei/nim/nmark/tests -o /home/kyohei/nim/nmark/nimcache/tests/testRegular.nim_0d61f8370cad1d412f80b84d143e1257/stdlib_streams.nim.c.o /home/kyohei/nim/nmark/nimcache/tests/testRegular.nim_0d61f8370cad1d412f80b84d143e1257/stdlib_streams.nim.c */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA;

/* section: NIM_merge_TYPES */
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
typedef N_NIMCALL_PTR(void, tyProc__JQrsH08b4uPTH9cyFPlVOZg) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__9bmhFrLahRsL2hltfRDVtlQ) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s);
typedef N_NIMCALL_PTR(void, tyProc__3svSoGIUJIsHkaBL7q4DAQ) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, NI pos);
typedef N_NIMCALL_PTR(NI, tyProc__xflqkf2D1uVClg70czEDHA) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s);
typedef N_NIMCALL_PTR(NI, tyProc__c9c0f59ak4YGQ6neEym8LPKw) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, NimStringDesc** buffer, tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA slice);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__7jFfqMk9ajToCz6Hv9atCA4A) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, NimStringDesc** line);
typedef N_NIMCALL_PTR(NI, tyProc__2VVzVL9bOnKhj1eZKkf9cEuA) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, void* buffer, NI bufLen);
typedef N_NIMCALL_PTR(void, tyProc__ki6p1QyfOkJLQJ9aw5NI0AQ) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, void* buffer, NI bufLen);
struct tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ {
  RootObj Sup;
tyProc__JQrsH08b4uPTH9cyFPlVOZg closeImpl;
tyProc__9bmhFrLahRsL2hltfRDVtlQ atEndImpl;
tyProc__3svSoGIUJIsHkaBL7q4DAQ setPositionImpl;
tyProc__xflqkf2D1uVClg70czEDHA getPositionImpl;
tyProc__c9c0f59ak4YGQ6neEym8LPKw readDataStrImpl;
tyProc__7jFfqMk9ajToCz6Hv9atCA4A readLineImpl;
tyProc__2VVzVL9bOnKhj1eZKkf9cEuA readDataImpl;
tyProc__2VVzVL9bOnKhj1eZKkf9cEuA peekDataImpl;
tyProc__ki6p1QyfOkJLQJ9aw5NI0AQ writeDataImpl;
tyProc__JQrsH08b4uPTH9cyFPlVOZg flushImpl;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA {
NI a;
NI b;
};

/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(void, write__egjcKjt8WddLFyjTFl5BAw)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, NimStringDesc* x);
N_LIB_PRIVATE N_NIMCALL(void, writeData__4hIni0uSy3RpPUiO9aB3JUQ)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, void* buffer, NI bufLen);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_NIMCALL(void, Marker_tyRef__1G0jiQbe7KwD5ADza5AZaw)(void* p, NI op);

/* section: NIM_merge_DATA */
STRING_LITERAL(TM__Ue7tnBcsL67VCiRfvt8q0A_3, "\012", 1);
extern TNimType NTI__ytyiCJqK439aF9cIibuRVpAg_;
N_LIB_PRIVATE TNimType NTI__THYguAi9bSgidczZ3ywEIMQ_;
N_LIB_PRIVATE TNimType NTI__JQrsH08b4uPTH9cyFPlVOZg_;
N_LIB_PRIVATE TNimType NTI__9bmhFrLahRsL2hltfRDVtlQ_;
N_LIB_PRIVATE TNimType NTI__3svSoGIUJIsHkaBL7q4DAQ_;
N_LIB_PRIVATE TNimType NTI__xflqkf2D1uVClg70czEDHA_;
N_LIB_PRIVATE TNimType NTI__c9c0f59ak4YGQ6neEym8LPKw_;
N_LIB_PRIVATE TNimType NTI__7jFfqMk9ajToCz6Hv9atCA4A_;
N_LIB_PRIVATE TNimType NTI__2VVzVL9bOnKhj1eZKkf9cEuA_;
N_LIB_PRIVATE TNimType NTI__ki6p1QyfOkJLQJ9aw5NI0AQ_;
N_LIB_PRIVATE TNimType NTI__1G0jiQbe7KwD5ADza5AZaw_;

/* section: NIM_merge_VARS */
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;

/* section: NIM_merge_PROCS */
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, writeData__4hIni0uSy3RpPUiO9aB3JUQ)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, void* buffer, NI bufLen) {
	nimfr_("writeData", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/streams.n"
"im");
	nimln_(328, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/streams.n"
"im");
	(*s).writeDataImpl(s, buffer, bufLen);
	popFrame();
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (s == ((NimStringDesc*) NIM_NIL));
		if (T3_) goto LA4_;
		T3_ = ((*s).Sup.len == ((NI) 0));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = "";
	}
	goto LA1_;
	LA5_: ;
	{
		result = ((NCSTRING) ((*s).data));
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, write__egjcKjt8WddLFyjTFl5BAw)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, NimStringDesc* x) {
	nimfr_("write", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/streams.n"
"im");
	nimln_(361, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/streams.n"
"im");
	{
		if (!(((NI) 0) < (x ? x->Sup.len : 0))) goto LA3_;
		nimln_(366, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/streams.n"
"im");
		writeData__4hIni0uSy3RpPUiO9aB3JUQ(s, ((void*) (nimToCStringConv(x))), (x ? x->Sup.len : 0));
	}
	LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, writeLine__2KoDZXJB4LmoH7PHLGmZ9cg)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, NimStringDesc** args, NI argsLen_0) {
	nimfr_("writeLine", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/streams.n"
"im");
	{
		NimStringDesc** str;
		NI i;
		str = (NimStringDesc**)0;
		nimln_(8, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
		i = ((NI) 0);
		{
			nimln_(9, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
			while (1) {
				NI TM__Ue7tnBcsL67VCiRfvt8q0A_2;
				if (!(i < argsLen_0)) goto LA3;
				nimln_(391, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/streams.n"
"im");
				if ((NU)(i) >= (NU)(argsLen_0)){ raiseIndexError2(i,argsLen_0-1); }
				str = (&args[i]);
				write__egjcKjt8WddLFyjTFl5BAw(s, (*str));
				nimln_(11, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
				if (nimAddInt(i, ((NI) 1), &TM__Ue7tnBcsL67VCiRfvt8q0A_2)) { raiseOverflow(); };
				i = (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_2);
			} LA3: ;
		}
	}
	nimln_(392, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/streams.n"
"im");
	write__egjcKjt8WddLFyjTFl5BAw(s, ((NimStringDesc*) &TM__Ue7tnBcsL67VCiRfvt8q0A_3));
	popFrame();
}
static N_NIMCALL(void, Marker_tyRef__1G0jiQbe7KwD5ADza5AZaw)(void* p, NI op) {
	tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* a;
	a = (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ*)p;
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_streamsDatInit000)(void) {

/* section: NIM_merge_TYPE_INIT1 */
static TNimNode* TM__Ue7tnBcsL67VCiRfvt8q0A_4_10[10];
static TNimNode TM__Ue7tnBcsL67VCiRfvt8q0A_0[11];

/* section: NIM_merge_TYPE_INIT3 */
NTI__THYguAi9bSgidczZ3ywEIMQ_.size = sizeof(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ);
NTI__THYguAi9bSgidczZ3ywEIMQ_.align = NIM_ALIGNOF(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ);
NTI__THYguAi9bSgidczZ3ywEIMQ_.kind = 17;
NTI__THYguAi9bSgidczZ3ywEIMQ_.base = (&NTI__ytyiCJqK439aF9cIibuRVpAg_);
NTI__THYguAi9bSgidczZ3ywEIMQ_.flags = 1;
TM__Ue7tnBcsL67VCiRfvt8q0A_4_10[0] = &TM__Ue7tnBcsL67VCiRfvt8q0A_0[1];
NTI__JQrsH08b4uPTH9cyFPlVOZg_.size = sizeof(tyProc__JQrsH08b4uPTH9cyFPlVOZg);
NTI__JQrsH08b4uPTH9cyFPlVOZg_.align = NIM_ALIGNOF(tyProc__JQrsH08b4uPTH9cyFPlVOZg);
NTI__JQrsH08b4uPTH9cyFPlVOZg_.kind = 25;
NTI__JQrsH08b4uPTH9cyFPlVOZg_.base = 0;
NTI__JQrsH08b4uPTH9cyFPlVOZg_.flags = 3;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[1].kind = 1;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[1].offset = offsetof(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ, closeImpl);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[1].typ = (&NTI__JQrsH08b4uPTH9cyFPlVOZg_);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[1].name = "closeImpl";
TM__Ue7tnBcsL67VCiRfvt8q0A_4_10[1] = &TM__Ue7tnBcsL67VCiRfvt8q0A_0[2];
NTI__9bmhFrLahRsL2hltfRDVtlQ_.size = sizeof(tyProc__9bmhFrLahRsL2hltfRDVtlQ);
NTI__9bmhFrLahRsL2hltfRDVtlQ_.align = NIM_ALIGNOF(tyProc__9bmhFrLahRsL2hltfRDVtlQ);
NTI__9bmhFrLahRsL2hltfRDVtlQ_.kind = 25;
NTI__9bmhFrLahRsL2hltfRDVtlQ_.base = 0;
NTI__9bmhFrLahRsL2hltfRDVtlQ_.flags = 3;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[2].kind = 1;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[2].offset = offsetof(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ, atEndImpl);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[2].typ = (&NTI__9bmhFrLahRsL2hltfRDVtlQ_);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[2].name = "atEndImpl";
TM__Ue7tnBcsL67VCiRfvt8q0A_4_10[2] = &TM__Ue7tnBcsL67VCiRfvt8q0A_0[3];
NTI__3svSoGIUJIsHkaBL7q4DAQ_.size = sizeof(tyProc__3svSoGIUJIsHkaBL7q4DAQ);
NTI__3svSoGIUJIsHkaBL7q4DAQ_.align = NIM_ALIGNOF(tyProc__3svSoGIUJIsHkaBL7q4DAQ);
NTI__3svSoGIUJIsHkaBL7q4DAQ_.kind = 25;
NTI__3svSoGIUJIsHkaBL7q4DAQ_.base = 0;
NTI__3svSoGIUJIsHkaBL7q4DAQ_.flags = 3;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[3].kind = 1;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[3].offset = offsetof(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ, setPositionImpl);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[3].typ = (&NTI__3svSoGIUJIsHkaBL7q4DAQ_);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[3].name = "setPositionImpl";
TM__Ue7tnBcsL67VCiRfvt8q0A_4_10[3] = &TM__Ue7tnBcsL67VCiRfvt8q0A_0[4];
NTI__xflqkf2D1uVClg70czEDHA_.size = sizeof(tyProc__xflqkf2D1uVClg70czEDHA);
NTI__xflqkf2D1uVClg70czEDHA_.align = NIM_ALIGNOF(tyProc__xflqkf2D1uVClg70czEDHA);
NTI__xflqkf2D1uVClg70czEDHA_.kind = 25;
NTI__xflqkf2D1uVClg70czEDHA_.base = 0;
NTI__xflqkf2D1uVClg70czEDHA_.flags = 3;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[4].kind = 1;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[4].offset = offsetof(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ, getPositionImpl);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[4].typ = (&NTI__xflqkf2D1uVClg70czEDHA_);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[4].name = "getPositionImpl";
TM__Ue7tnBcsL67VCiRfvt8q0A_4_10[4] = &TM__Ue7tnBcsL67VCiRfvt8q0A_0[5];
NTI__c9c0f59ak4YGQ6neEym8LPKw_.size = sizeof(tyProc__c9c0f59ak4YGQ6neEym8LPKw);
NTI__c9c0f59ak4YGQ6neEym8LPKw_.align = NIM_ALIGNOF(tyProc__c9c0f59ak4YGQ6neEym8LPKw);
NTI__c9c0f59ak4YGQ6neEym8LPKw_.kind = 25;
NTI__c9c0f59ak4YGQ6neEym8LPKw_.base = 0;
NTI__c9c0f59ak4YGQ6neEym8LPKw_.flags = 3;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[5].kind = 1;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[5].offset = offsetof(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ, readDataStrImpl);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[5].typ = (&NTI__c9c0f59ak4YGQ6neEym8LPKw_);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[5].name = "readDataStrImpl";
TM__Ue7tnBcsL67VCiRfvt8q0A_4_10[5] = &TM__Ue7tnBcsL67VCiRfvt8q0A_0[6];
NTI__7jFfqMk9ajToCz6Hv9atCA4A_.size = sizeof(tyProc__7jFfqMk9ajToCz6Hv9atCA4A);
NTI__7jFfqMk9ajToCz6Hv9atCA4A_.align = NIM_ALIGNOF(tyProc__7jFfqMk9ajToCz6Hv9atCA4A);
NTI__7jFfqMk9ajToCz6Hv9atCA4A_.kind = 25;
NTI__7jFfqMk9ajToCz6Hv9atCA4A_.base = 0;
NTI__7jFfqMk9ajToCz6Hv9atCA4A_.flags = 3;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[6].kind = 1;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[6].offset = offsetof(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ, readLineImpl);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[6].typ = (&NTI__7jFfqMk9ajToCz6Hv9atCA4A_);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[6].name = "readLineImpl";
TM__Ue7tnBcsL67VCiRfvt8q0A_4_10[6] = &TM__Ue7tnBcsL67VCiRfvt8q0A_0[7];
NTI__2VVzVL9bOnKhj1eZKkf9cEuA_.size = sizeof(tyProc__2VVzVL9bOnKhj1eZKkf9cEuA);
NTI__2VVzVL9bOnKhj1eZKkf9cEuA_.align = NIM_ALIGNOF(tyProc__2VVzVL9bOnKhj1eZKkf9cEuA);
NTI__2VVzVL9bOnKhj1eZKkf9cEuA_.kind = 25;
NTI__2VVzVL9bOnKhj1eZKkf9cEuA_.base = 0;
NTI__2VVzVL9bOnKhj1eZKkf9cEuA_.flags = 3;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[7].kind = 1;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[7].offset = offsetof(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ, readDataImpl);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[7].typ = (&NTI__2VVzVL9bOnKhj1eZKkf9cEuA_);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[7].name = "readDataImpl";
TM__Ue7tnBcsL67VCiRfvt8q0A_4_10[7] = &TM__Ue7tnBcsL67VCiRfvt8q0A_0[8];
TM__Ue7tnBcsL67VCiRfvt8q0A_0[8].kind = 1;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[8].offset = offsetof(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ, peekDataImpl);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[8].typ = (&NTI__2VVzVL9bOnKhj1eZKkf9cEuA_);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[8].name = "peekDataImpl";
TM__Ue7tnBcsL67VCiRfvt8q0A_4_10[8] = &TM__Ue7tnBcsL67VCiRfvt8q0A_0[9];
NTI__ki6p1QyfOkJLQJ9aw5NI0AQ_.size = sizeof(tyProc__ki6p1QyfOkJLQJ9aw5NI0AQ);
NTI__ki6p1QyfOkJLQJ9aw5NI0AQ_.align = NIM_ALIGNOF(tyProc__ki6p1QyfOkJLQJ9aw5NI0AQ);
NTI__ki6p1QyfOkJLQJ9aw5NI0AQ_.kind = 25;
NTI__ki6p1QyfOkJLQJ9aw5NI0AQ_.base = 0;
NTI__ki6p1QyfOkJLQJ9aw5NI0AQ_.flags = 3;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[9].kind = 1;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[9].offset = offsetof(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ, writeDataImpl);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[9].typ = (&NTI__ki6p1QyfOkJLQJ9aw5NI0AQ_);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[9].name = "writeDataImpl";
TM__Ue7tnBcsL67VCiRfvt8q0A_4_10[9] = &TM__Ue7tnBcsL67VCiRfvt8q0A_0[10];
TM__Ue7tnBcsL67VCiRfvt8q0A_0[10].kind = 1;
TM__Ue7tnBcsL67VCiRfvt8q0A_0[10].offset = offsetof(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ, flushImpl);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[10].typ = (&NTI__JQrsH08b4uPTH9cyFPlVOZg_);
TM__Ue7tnBcsL67VCiRfvt8q0A_0[10].name = "flushImpl";
TM__Ue7tnBcsL67VCiRfvt8q0A_0[0].len = 10; TM__Ue7tnBcsL67VCiRfvt8q0A_0[0].kind = 2; TM__Ue7tnBcsL67VCiRfvt8q0A_0[0].sons = &TM__Ue7tnBcsL67VCiRfvt8q0A_4_10[0];
NTI__THYguAi9bSgidczZ3ywEIMQ_.node = &TM__Ue7tnBcsL67VCiRfvt8q0A_0[0];
NTI__1G0jiQbe7KwD5ADza5AZaw_.size = sizeof(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ*);
NTI__1G0jiQbe7KwD5ADza5AZaw_.align = NIM_ALIGNOF(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ*);
NTI__1G0jiQbe7KwD5ADza5AZaw_.kind = 22;
NTI__1G0jiQbe7KwD5ADza5AZaw_.base = (&NTI__THYguAi9bSgidczZ3ywEIMQ_);
NTI__1G0jiQbe7KwD5ADza5AZaw_.marker = Marker_tyRef__1G0jiQbe7KwD5ADza5AZaw;
}

