/* Generated by Nim Compiler v1.4.4 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3   -I/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib -I/home/kyohei/nim/nmark/tests -o /home/kyohei/nim/nmark/nimcache/tests/testRegular.nim_0d61f8370cad1d412f80b84d143e1257/stdlib_unittest.nim.c.o /home/kyohei/nim/nmark/nimcache/tests/testRegular.nim_0d61f8370cad1d412f80b84d143e1257/stdlib_unittest.nim.c */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence__shvncLWJZ4vpydQXcCi7CA tySequence__shvncLWJZ4vpydQXcCi7CA;
typedef struct tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg;
typedef struct RootObj RootObj;
typedef struct tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw tySequence__4eRCaZmrYLLw2k30GPTiMw;
typedef struct tyObject_TestResult__GEvSVSxdPWWgMGM48ywEYQ tyObject_TestResult__GEvSVSxdPWWgMGM48ywEYQ;
typedef struct tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ;
typedef struct tyObject_JUnitOutputFormattercolonObjectType___xT2f3fp9bT7rro9bWvoTGQHw tyObject_JUnitOutputFormattercolonObjectType___xT2f3fp9bT7rro9bWvoTGQHw;
typedef struct tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw tyTuple__QeWl6B6ffS4pU6WWrtcrDw;

/* section: NIM_merge_TYPES */
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct RootObj {
TNimType* m_type;
};
struct tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg {
  RootObj Sup;
};
struct tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg {
tySequence__4eRCaZmrYLLw2k30GPTiMw* data;
NI counter;
};
typedef NU8 tyEnum_TestStatus__W9bTUg9c9a7UlIYkKYmd5uasQ;
struct tyObject_TestResult__GEvSVSxdPWWgMGM48ywEYQ {
NimStringDesc* suiteName;
NimStringDesc* testName;
tyEnum_TestStatus__W9bTUg9c9a7UlIYkKYmd5uasQ status;
};
typedef NU8 tyEnum_OutputLevel__7UfTrIPsm9cGDPwH9bpwJDww;
struct tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ {
  tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg Sup;
NIM_BOOL colorOutput;
tyEnum_OutputLevel__7UfTrIPsm9cGDPwH9bpwJDww outputLevel;
NIM_BOOL isInSuite;
NIM_BOOL isInTest;
};
typedef NU16 tySet_tyEnum_Style__NXKayqTLMsAibFwNceBlpA;
typedef NU8 tyEnum_ForegroundColor__ez9ah4IgQc0AbdW68acioDg;
typedef NimStringDesc* tyArray__Re75IspeoxXy2oCZHwcRrA[2];
typedef NimStringDesc* tyArray__nHXaesL0DJZHyVS07ARPRA[1];
typedef NimStringDesc* tyArray__haiLFy0nBviVTKFGuwztzQ[5];
struct tyObject_JUnitOutputFormattercolonObjectType___xT2f3fp9bT7rro9bWvoTGQHw {
  tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg Sup;
tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* stream;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* testErrors;
NF testStartTime;
NimStringDesc* testStackTrace;
};
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NU8 tyEnum_FloatFormatMode__pNvEoaqwoxKyoASD11vSgQ;
struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw {
NI Field0;
NimStringDesc* Field1;
};

/* section: NIM_merge_SEQ_TYPES */
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence__shvncLWJZ4vpydQXcCi7CA {
  TGenericSeq Sup;
  tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg* data[SEQ_DECL_SIZE];
};
struct tySequence__4eRCaZmrYLLw2k30GPTiMw {
  TGenericSeq Sup;
  tyTuple__QeWl6B6ffS4pU6WWrtcrDw data[SEQ_DECL_SIZE];
};

/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM__Um3CQPZ9bILAIolZOsxNIaw_2)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimRegisterThreadLocalMarker)(tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
static N_NIMCALL(void, Marker_tyRef__OdrGHrb6tOjaNa9bJrVe7KA)(void* p, NI op);
static N_NIMCALL(void, Marker_tySequence__shvncLWJZ4vpydQXcCi7CA)(void* p, NI op);
static N_NIMCALL(void, TM__Um3CQPZ9bILAIolZOsxNIaw_3)(void);
static N_NIMCALL(void, TM__Um3CQPZ9bILAIolZOsxNIaw_4)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, existsEnv__HhiDHRQxJ349a6FFxO51gqQ)(NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted__nK9beSbLicfntIGmVZ6WEWA)(tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg* formatter, NimStringDesc* suiteName);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, testStarted__fhO6e9bKNGadYu9bLP5X9a53w)(tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg* formatter, NimStringDesc* testName);
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred__y9agyYRiFuLRsj8cxb7M2aw)(tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg* formatter, tySequence__sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace);
N_LIB_PRIVATE N_NIMCALL(void, testEnded__39adjE9asi6f3uUg4ggiRSww)(tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg* formatter, tyObject_TestResult__GEvSVSxdPWWgMGM48ywEYQ testResult);
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded__IxSFIeAV4sKVuL6uebtiIg)(tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg* formatter);
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted__RmGTSm1l82Zftef3hljKRw)(tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ* formatter, NimStringDesc* suiteName);
N_LIB_PRIVATE N_NIMCALL(void, setStyle__y8lW2LrW2n5ZHaxH9bAf4WA)(FILE* f, tySet_tyEnum_Style__NXKayqTLMsAibFwNceBlpA style);
N_LIB_PRIVATE N_NIMCALL(void, setForegroundColor__vJutklhcnQq9akCXxcuSHAg)(FILE* f, tyEnum_ForegroundColor__ez9ah4IgQc0AbdW68acioDg fg, NIM_BOOL bright);
N_LIB_PRIVATE N_NIMCALL(void, write__PArlm09bKklm2BLsCg6YtaA)(FILE* f, NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(void, resetAttributes__6J8xlU57R8cS9bLzTS89aM5g)(FILE* f);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(void, testStarted__zsOlm9c8uMvIuLHEOGed13w)(tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ* formatter, NimStringDesc* testName);
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred__oAXBZ7YPEZBQDUv6scAxJg)(tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ* formatter, tySequence__sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(void, testEnded__ATioSVJSHfI46B9bskc9aLww)(tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ* formatter, tyObject_TestResult__GEvSVSxdPWWgMGM48ywEYQ testResult);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, reprEnum)(NI e, TNimType* typ);
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded__zBTsK2MPuNZcKY6U6m7dJQ)(tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ* formatter);
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted__sp88Zl8pNky66YAX9aTDe4g)(tyObject_JUnitOutputFormattercolonObjectType___xT2f3fp9bT7rro9bWvoTGQHw* formatter, NimStringDesc* suiteName);
N_LIB_PRIVATE N_NIMCALL(void, writeLine__2KoDZXJB4LmoH7PHLGmZ9cg)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuFormatSingleElem)(NimStringDesc* formatstr, NimStringDesc* a);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, xmlEscape__g2YcY9bwywneeGZViUm72Ng)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(void, testStarted__rOCXlMecpGAbukiW3xEnBA)(tyObject_JUnitOutputFormattercolonObjectType___xT2f3fp9bT7rro9bWvoTGQHw* formatter, NimStringDesc* testName);
N_LIB_PRIVATE N_NIMCALL(TGenericSeq*, setLengthSeqV2)(TGenericSeq* s, TNimType* typ, NI newLen);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__AT1eRuflKWyTTBdLjEDZbgsystem)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___dgYAo7RfdUVVpvkfKDym8w_2system)(NI x, NI y);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem)(void* usr);
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y);
static N_INLINE(void, decRef__AT1eRuflKWyTTBdLjEDZbg_2system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NIM_BOOL, ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_3system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__Y66tOYFjgwJ0k4aLz4bc0Q)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(NF, epochTime__9aodCrWXscOGeNVh2cpuZkw)(void);
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred__6o9bQoLfclkbDZsrcHh9b69cw)(tyObject_JUnitOutputFormattercolonObjectType___xT2f3fp9bT7rro9bWvoTGQHw* formatter, tySequence__sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace);
N_LIB_PRIVATE N_NIMCALL(void, add__IGVMsyxhGfOdjDsdcEGOpA)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ** x, NimStringDesc** y, NI yLen_0);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, testEnded__zLtcJqmjhY5eIZTmyZMGng)(tyObject_JUnitOutputFormattercolonObjectType___xT2f3fp9bT7rro9bWvoTGQHw* formatter, tyObject_TestResult__GEvSVSxdPWWgMGM48ywEYQ testResult);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuformatFloat)(NF f, tyEnum_FloatFormatMode__pNvEoaqwoxKyoASD11vSgQ format, NI precision, NIM_CHAR decimalSep);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen_0);
static N_INLINE(NimStringDesc**, X5BX5D___qAX9aHx35KUFY79aX8PJ3xRgsystem)(NimStringDesc** s, NI sLen_0, NI i);
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded__j47Kbeiu3vfl9brbuQ3zGKg)(tyObject_JUnitOutputFormattercolonObjectType___xT2f3fp9bT7rro9bWvoTGQHw* formatter);
static N_INLINE(void, nimGCunrefRC1)(void* p);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ*, defaultConsoleFormatter__EKaes5nvFgq1idJu8Wb7ew)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getEnv__hhED57tMl0Iaa5bOg9cJaig)(NimStringDesc* key, NimStringDesc* default_0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isatty__N9cWRL9bvOiaeIezt6AEzXqw)(FILE* f);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem__9bGgqEk7RXXl6eqM9c1HdELAsystem)(void* a, void* b, NI size);
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ*, newConsoleOutputFormatter__F1bJtIZPshctBi9bJAr17dQ)(tyEnum_OutputLevel__7UfTrIPsm9cGDPwH9bpwJDww outputLevel, NIM_BOOL colorOutput);
static N_NIMCALL(void, Marker_tyRef__E6s9cEeVHb9b86T9bNZiuvutQ)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(NI, paramCount__LYkRnwMk6UXTCs9c59cPvZsQ)(void);
N_LIB_PRIVATE N_NIMCALL(void, incl__TMNSyv4q8yRKlH5e1bO09cA)(tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg* s, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, paramStr__T0ST6UXXTEqaiXY9akIayng)(NI i);
N_LIB_PRIVATE N_NIMCALL(NI, len__sVMoSv8jxXZJxl8pFcjd4Q)(tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg s);
static N_INLINE(NIM_BOOL, isFilled__uHIMxs9aGYDEfZheaMnN2sQsets)(NI hcode);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, matchFilter__NqIpE4DyesfWHizCjp6lwg)(NimStringDesc* suiteName, NimStringDesc* testName, NimStringDesc* filter);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ*, nsuSplitString)(NimStringDesc* s, NimStringDesc* sep, NI maxsplit);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, glob__4YckL5LRAFTQuXhocCy9bwg)(NimStringDesc* matcher, NimStringDesc* filter);
static N_INLINE(NIM_BOOL, contains__Pa9a8m0kZYH6LC8N1EcZJdQsystem)(NIM_CHAR* a, NI aLen_0, NIM_CHAR item);
static N_INLINE(NI, find__31wM5Ui9c8jnrQ5QD4oPxOQsystem)(NIM_CHAR* a, NI aLen_0, NIM_CHAR item);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ*, nsuSplitChar)(NimStringDesc* s, NIM_CHAR sep, NI maxsplit);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringDesc* s, NimStringDesc* prefix);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuEndsWith)(NimStringDesc* s, NimStringDesc* suffix);
N_LIB_PRIVATE N_NIMCALL(TGenericSeq*, incrSeqV3)(TGenericSeq* s, TNimType* typ);
N_LIB_PRIVATE N_NIMCALL(void, testEnded__31pnpDPCXMA6dr4c0S6y9aw)(tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg* formatter, tyObject_TestResult__GEvSVSxdPWWgMGM48ywEYQ testResult);

/* section: NIM_merge_DATA */
extern TNimType NTI__sM4lkSb7zS6F7OVMvW9cffQ_;
extern TNimType NTI__ytyiCJqK439aF9cIibuRVpAg_;
N_LIB_PRIVATE TNimType NTI__F9cVkVj1qOwgl27pKTy0srg_;
N_LIB_PRIVATE TNimType NTI__OdrGHrb6tOjaNa9bJrVe7KA_;
N_LIB_PRIVATE TNimType NTI__shvncLWJZ4vpydQXcCi7CA_;
extern TNimType NTI__CD8Dpv0WGmASelVaNSo6zg_;
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_5, "NIMTEST_ABORT_ON_ERROR", 22);
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_6, "\012[Suite] ", 9);
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_7, "\012", 1);
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_8, "    ", 4);
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_10, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim(204, 11) `len(a) == L` the length of the seq changed whil"
"e iterating over it", 146);
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_11, "  ", 2);
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_12, "[", 1);
N_LIB_PRIVATE TNimType NTI__W9bTUg9c9a7UlIYkKYmd5uasQ_;
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_16, "] ", 2);
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_17, "\011<testsuite name=\"$1\">", 22);
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_18, "&lt;", 4);
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_19, "&gt;", 4);
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_20, "&amp;", 5);
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_21, "&quot;", 6);
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_22, "&apos;", 6);
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_23, "&#", 2);
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_25, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim(222, 11) `len(a) == L` the length of the string changed w"
"hile iterating over it", 149);
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_26, "\011\011<testcase name=\"$#\" time=\"$#\">", 32);
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_28, "<skipped />", 11);
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__Um3CQPZ9bILAIolZOsxNIaw_27 = {((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_28)}
;
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_30, "The test failed without outputting an error", 43);
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_34, "\011\011\011<error message=\"$#\">$#</error>", 33);
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_35, "\011\011\011<system-err>$#</system-err>", 30);
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_36, "\011\011\011<failure message=\"$#\">$#</failure>", 37);
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_38, "\011\011</testcase>", 13);
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__Um3CQPZ9bILAIolZOsxNIaw_37 = {((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_38)}
;
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_40, "\011</testsuite>", 13);
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__Um3CQPZ9bILAIolZOsxNIaw_39 = {((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_40)}
;
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_41, "NIMTEST_OUTPUT_LVL", 18);
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_42, "NIMTEST_COLOR", 13);
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_43, "never", 5);
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_44, "always", 6);
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_45, "NIMTEST_NO_COLOR", 16);
N_LIB_PRIVATE TNimType NTI__7UfTrIPsm9cGDPwH9bpwJDww_;
N_LIB_PRIVATE TNimType NTI__pWdV1nDlYJumLrx0ueKJFQ_;
extern TNimType NTI__VaVACK0bpYmqIQ0mKcHfQQ_;
N_LIB_PRIVATE TNimType NTI__E6s9cEeVHb9b86T9bNZiuvutQ_;
STRING_LITERAL(TM__Um3CQPZ9bILAIolZOsxNIaw_52, "::", 2);
N_LIB_PRIVATE TNimType NTI__GEvSVSxdPWWgMGM48ywEYQ_;
extern TNimType NTI__77mFvmsOLKik79ci2hXkHEg_;
N_LIB_PRIVATE TNimType NTI__xT2f3fp9bT7rro9bWvoTGQHw_;
extern TNimType NTI__1G0jiQbe7KwD5ADza5AZaw_;
extern TNimType NTI__w9bl9a1ul9ctRJWiMl9cNnIMvg_;

/* section: NIM_merge_VARS */
N_LIB_PRIVATE NIM_BOOL abortOnError__Bte3Uiwc4Q19ago2N4C89cUA;
N_LIB_PRIVATE tySequence__sM4lkSb7zS6F7OVMvW9cffQ* checkpoints__bq5hLRYOyiTcYy29a9akD9c9bQ;
N_LIB_PRIVATE tySequence__shvncLWJZ4vpydQXcCi7CA* formatters__55U7g4zhjHV9bCI6emTgDiA;
N_LIB_PRIVATE tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg testsFilters__Xhcy9bMKRibp73mpqIGgoPA;
N_LIB_PRIVATE NIM_BOOL disabledParamFiltering__9bKIyYrmH1Yr9cIlxYEwYZTg;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__IcYaEuuWivYAS86vFMTS3Q;

/* section: NIM_merge_PROCS */
static N_NIMCALL(void, TM__Um3CQPZ9bILAIolZOsxNIaw_2)(void) {
	nimGCvisit((void*)checkpoints__bq5hLRYOyiTcYy29a9akD9c9bQ, 0);
}
static N_NIMCALL(void, Marker_tyRef__OdrGHrb6tOjaNa9bJrVe7KA)(void* p, NI op) {
	tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg* a;
	a = (tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg*)p;
}
static N_NIMCALL(void, Marker_tySequence__shvncLWJZ4vpydQXcCi7CA)(void* p, NI op) {
	tySequence__shvncLWJZ4vpydQXcCi7CA* a;
	NI T1_;
	a = (tySequence__shvncLWJZ4vpydQXcCi7CA*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < (a ? a->Sup.len : 0); T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}
static N_NIMCALL(void, TM__Um3CQPZ9bILAIolZOsxNIaw_3)(void) {
	nimGCvisit((void*)formatters__55U7g4zhjHV9bCI6emTgDiA, 0);
}
static N_NIMCALL(void, TM__Um3CQPZ9bILAIolZOsxNIaw_4)(void) {
	nimGCvisit((void*)testsFilters__Xhcy9bMKRibp73mpqIGgoPA.data, 0);
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted__nK9beSbLicfntIGmVZ6WEWA)(tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg* formatter, NimStringDesc* suiteName) {
	nimfr_("suiteStarted", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, testStarted__fhO6e9bKNGadYu9bLP5X9a53w)(tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg* formatter, NimStringDesc* testName) {
	nimfr_("testStarted", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred__y9agyYRiFuLRsj8cxb7M2aw)(tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg* formatter, tySequence__sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace) {
	nimfr_("failureOccurred", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, testEnded__39adjE9asi6f3uUg4ggiRSww)(tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg* formatter, tyObject_TestResult__GEvSVSxdPWWgMGM48ywEYQ testResult) {
	nimfr_("testEnded", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded__IxSFIeAV4sKVuL6uebtiIg)(tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg* formatter) {
	nimfr_("suiteEnded", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	popFrame();
}
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory(p, ((int) 0), size);
}
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted__RmGTSm1l82Zftef3hljKRw)(tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ* formatter, NimStringDesc* suiteName) {
	nimfr_("suiteStarted", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	nimln_(239, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	{
		if (!(*formatter).colorOutput) goto LA3_;
		nimln_(728, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/terminal."
"nim");
		setStyle__y8lW2LrW2n5ZHaxH9bAf4WA(stdout, 1);
		setForegroundColor__vJutklhcnQq9akCXxcuSHAg(stdout, ((tyEnum_ForegroundColor__ez9ah4IgQc0AbdW68acioDg) 34), NIM_FALSE);
		nimln_(240, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
		write__PArlm09bKklm2BLsCg6YtaA(stdout, ((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_6));
		nimln_(728, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/terminal."
"nim");
		resetAttributes__6J8xlU57R8cS9bLzTS89aM5g(stdout);
		write__PArlm09bKklm2BLsCg6YtaA(stdout, suiteName);
		nimln_(742, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/terminal."
"nim");
		resetAttributes__6J8xlU57R8cS9bLzTS89aM5g(stdout);
		nimln_(747, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/terminal."
"nim");
		write__PArlm09bKklm2BLsCg6YtaA(stdout, ((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_7));
	}
	goto LA1_;
	LA3_: ;
	{
		tyArray__Re75IspeoxXy2oCZHwcRrA T6_;
		nimln_(241, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
		nimZeroMem((void*)T6_, sizeof(tyArray__Re75IspeoxXy2oCZHwcRrA));
		T6_[0] = copyString(((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_6));
		T6_[1] = copyString(suiteName);
		echoBinSafe(T6_, 2);
	}
	LA1_: ;
	nimln_(243, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	(*formatter).isInSuite = NIM_TRUE;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, testStarted__zsOlm9c8uMvIuLHEOGed13w)(tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ* formatter, NimStringDesc* testName) {
	nimfr_("testStarted", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	nimln_(246, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	(*formatter).isInTest = NIM_TRUE;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred__oAXBZ7YPEZBQDUv6scAxJg)(tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ* formatter, tySequence__sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace) {
	NimStringDesc* prefix;
	nimfr_("failureOccurred", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	nimln_(250, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	{
		tyArray__nHXaesL0DJZHyVS07ARPRA T5_;
		if (!(((NI) 0) < (stackTrace ? stackTrace->Sup.len : 0))) goto LA3_;
		nimln_(251, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
		nimZeroMem((void*)T5_, sizeof(tyArray__nHXaesL0DJZHyVS07ARPRA));
		T5_[0] = copyString(stackTrace);
		echoBinSafe(T5_, 1);
	}
	LA3_: ;
	nimln_(252, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	{
		if (!(*formatter).isInSuite) goto LA8_;
		prefix = copyString(((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_8));
	}
	goto LA6_;
	LA8_: ;
	{
		prefix = ((NimStringDesc*) NIM_NIL);
	}
	LA6_: ;
	{
		NimStringDesc** msg;
		NI i;
		NI L;
		NI T12_;
		msg = (NimStringDesc**)0;
		nimln_(199, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
		i = ((NI) 0);
		nimln_(200, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
		T12_ = (checkpoints ? checkpoints->Sup.len : 0);
		L = T12_;
		{
			nimln_(201, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
			while (1) {
				tyArray__Re75IspeoxXy2oCZHwcRrA T15_;
				NI TM__Um3CQPZ9bILAIolZOsxNIaw_9;
				if (!(i < L)) goto LA14;
				nimln_(253, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
				if ((NU)(i) >= (NU)(checkpoints ? checkpoints->Sup.len : 0)){ raiseIndexError2(i,(checkpoints ? checkpoints->Sup.len : 0)-1); }
				msg = (&checkpoints->data[i]);
				nimln_(254, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
				nimZeroMem((void*)T15_, sizeof(tyArray__Re75IspeoxXy2oCZHwcRrA));
				T15_[0] = copyString(prefix);
				T15_[1] = copyString((*msg));
				echoBinSafe(T15_, 2);
				nimln_(203, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
				if (nimAddInt(i, ((NI) 1), &TM__Um3CQPZ9bILAIolZOsxNIaw_9)) { raiseOverflow(); };
				i = (NI)(TM__Um3CQPZ9bILAIolZOsxNIaw_9);
				nimln_(204, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
				{
					NI T18_;
					T18_ = (checkpoints ? checkpoints->Sup.len : 0);
					if (!!((T18_ == L))) goto LA19_;
					failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_10));
				}
				LA19_: ;
			} LA14: ;
		}
	}
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, testEnded__ATioSVJSHfI46B9bskc9aLww)(tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ* formatter, tyObject_TestResult__GEvSVSxdPWWgMGM48ywEYQ testResult) {
	nimfr_("testEnded", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	nimln_(257, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	(*formatter).isInTest = NIM_FALSE;
	nimln_(259, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	{
		NIM_BOOL T3_;
		NIM_BOOL T5_;
		NimStringDesc* prefix;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*formatter).outputLevel == ((tyEnum_OutputLevel__7UfTrIPsm9cGDPwH9bpwJDww) 2)));
		if (!(T3_)) goto LA4_;
		nimln_(260, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
		T5_ = (NIM_BOOL)0;
		T5_ = ((*formatter).outputLevel == ((tyEnum_OutputLevel__7UfTrIPsm9cGDPwH9bpwJDww) 0));
		if (T5_) goto LA6_;
		T5_ = (testResult.status == ((tyEnum_TestStatus__W9bTUg9c9a7UlIYkKYmd5uasQ) 1));
		LA6_: ;
		T3_ = T5_;
		LA4_: ;
		if (!T3_) goto LA7_;
		nimln_(261, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
		{
			if (!(((NI) 0) < (testResult.suiteName ? testResult.suiteName->Sup.len : 0))) goto LA11_;
			prefix = copyString(((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_11));
		}
		goto LA9_;
		LA11_: ;
		{
			prefix = ((NimStringDesc*) NIM_NIL);
		}
		LA9_: ;
		nimln_(265, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
		{
			tyEnum_ForegroundColor__ez9ah4IgQc0AbdW68acioDg color;
			if (!(*formatter).colorOutput) goto LA16_;
			nimln_(266, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
			switch (testResult.status) {
			case ((tyEnum_TestStatus__W9bTUg9c9a7UlIYkKYmd5uasQ) 0):
			{
				color = ((tyEnum_ForegroundColor__ez9ah4IgQc0AbdW68acioDg) 32);
			}
			break;
			case ((tyEnum_TestStatus__W9bTUg9c9a7UlIYkKYmd5uasQ) 1):
			{
				color = ((tyEnum_ForegroundColor__ez9ah4IgQc0AbdW68acioDg) 31);
			}
			break;
			case ((tyEnum_TestStatus__W9bTUg9c9a7UlIYkKYmd5uasQ) 2):
			{
				color = ((tyEnum_ForegroundColor__ez9ah4IgQc0AbdW68acioDg) 33);
			}
			break;
			}
			nimln_(728, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/terminal."
"nim");
			setStyle__y8lW2LrW2n5ZHaxH9bAf4WA(stdout, 1);
			setForegroundColor__vJutklhcnQq9akCXxcuSHAg(stdout, color, NIM_FALSE);
			write__PArlm09bKklm2BLsCg6YtaA(stdout, prefix);
			nimln_(270, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
			write__PArlm09bKklm2BLsCg6YtaA(stdout, ((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_12));
			nimln_(728, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/terminal."
"nim");
			nimln_(270, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
			nimln_(728, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/terminal."
"nim");
			write__PArlm09bKklm2BLsCg6YtaA(stdout, reprEnum((NI)testResult.status, (&NTI__W9bTUg9c9a7UlIYkKYmd5uasQ_)));
			nimln_(270, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
			write__PArlm09bKklm2BLsCg6YtaA(stdout, ((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_16));
			nimln_(728, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/terminal."
"nim");
			resetAttributes__6J8xlU57R8cS9bLzTS89aM5g(stdout);
			write__PArlm09bKklm2BLsCg6YtaA(stdout, testResult.testName);
			nimln_(742, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/terminal."
"nim");
			resetAttributes__6J8xlU57R8cS9bLzTS89aM5g(stdout);
			nimln_(747, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/terminal."
"nim");
			write__PArlm09bKklm2BLsCg6YtaA(stdout, ((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_7));
		}
		goto LA14_;
		LA16_: ;
		{
			tyArray__haiLFy0nBviVTKFGuwztzQ T22_;
			nimln_(273, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
			nimZeroMem((void*)T22_, sizeof(tyArray__haiLFy0nBviVTKFGuwztzQ));
			T22_[0] = copyString(prefix);
			T22_[1] = copyString(((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_12));
			nimln_(262, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
			T22_[2] = reprEnum((NI)testResult.status, (&NTI__W9bTUg9c9a7UlIYkKYmd5uasQ_));
			T22_[3] = copyString(((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_16));
			T22_[4] = copyString(testResult.testName);
			echoBinSafe(T22_, 5);
		}
		LA14_: ;
	}
	LA7_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded__zBTsK2MPuNZcKY6U6m7dJQ)(tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ* formatter) {
	nimfr_("suiteEnded", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	nimln_(278, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	(*formatter).isInSuite = NIM_FALSE;
	popFrame();
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__i80o3k0SgEI5gTRCzYdyWAsystem(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[(*dest).Sup.len] = c;
	(*dest).data[(NI)((*dest).Sup.len + ((NI) 1))] = 0;
	(*dest).Sup.len += ((NI) 1);
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, xmlEscape__g2YcY9bwywneeGZViUm72Ng)(NimStringDesc* s) {
	NimStringDesc* result;
	nimfr_("xmlEscape", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	result = (NimStringDesc*)0;
	nimln_(281, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	if (((s ? s->Sup.len : 0)) < ((NI) 0) || ((s ? s->Sup.len : 0)) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI((s ? s->Sup.len : 0), ((NI) 0), ((NI) IL64(9223372036854775807))); }
	result = rawNewString(((NI) ((s ? s->Sup.len : 0))));
	{
		NIM_CHAR c;
		NI i;
		NI L;
		c = (NIM_CHAR)0;
		nimln_(217, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
		i = ((NI) 0);
		nimln_(218, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
		L = (s ? s->Sup.len : 0);
		{
			nimln_(219, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
			while (1) {
				NI TM__Um3CQPZ9bILAIolZOsxNIaw_24;
				if (!(i < L)) goto LA3;
				nimln_(282, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
				if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
				c = s->data[i];
				nimln_(283, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
				switch (((NU8)(c))) {
				case 60:
				{
					nimln_(284, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
					result = resizeString(result, 4);
appendString(result, ((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_18));
				}
				break;
				case 62:
				{
					nimln_(285, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
					result = resizeString(result, 4);
appendString(result, ((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_19));
				}
				break;
				case 38:
				{
					nimln_(286, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
					result = resizeString(result, 5);
appendString(result, ((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_20));
				}
				break;
				case 34:
				{
					nimln_(287, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
					result = resizeString(result, 6);
appendString(result, ((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_21));
				}
				break;
				case 39:
				{
					nimln_(288, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
					result = resizeString(result, 6);
appendString(result, ((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_22));
				}
				break;
				default:
				{
					nimln_(290, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
					{
						NimStringDesc* T14_;
						NimStringDesc* T15_;
						if (!(((NU8)(c)) < ((NI) 32))) goto LA12_;
						nimln_(291, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
						T14_ = (NimStringDesc*)0;
						T15_ = (NimStringDesc*)0;
						T15_ = nimIntToStr(((NU8)(c)));
						T14_ = rawNewString((T15_ ? T15_->Sup.len : 0) + 3);
appendString(T14_, ((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_23));
appendString(T14_, T15_);
appendChar(T14_, 59);
						result = resizeString(result, (T14_ ? T14_->Sup.len : 0) + 0);
appendString(result, T14_);
					}
					goto LA10_;
					LA12_: ;
					{
						nimln_(293, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
						result = addChar(result, c);
					}
					LA10_: ;
				}
				break;
				}
				nimln_(221, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
				if (nimAddInt(i, ((NI) 1), &TM__Um3CQPZ9bILAIolZOsxNIaw_24)) { raiseOverflow(); };
				i = (NI)(TM__Um3CQPZ9bILAIolZOsxNIaw_24);
				nimln_(222, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
				{
					if (!!(((s ? s->Sup.len : 0) == L))) goto LA19_;
					failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_25));
				}
				LA19_: ;
			} LA3: ;
		}
	}
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted__sp88Zl8pNky66YAX9aTDe4g)(tyObject_JUnitOutputFormattercolonObjectType___xT2f3fp9bT7rro9bWvoTGQHw* formatter, NimStringDesc* suiteName) {
	tyArray__nHXaesL0DJZHyVS07ARPRA T1_;
	NimStringDesc* T2_;
	nimfr_("suiteStarted", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	nimln_(316, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	nimZeroMem((void*)T1_, sizeof(tyArray__nHXaesL0DJZHyVS07ARPRA));
	T2_ = (NimStringDesc*)0;
	T2_ = xmlEscape__g2YcY9bwywneeGZViUm72Ng(suiteName);
	T1_[0] = nsuFormatSingleElem(((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_17), T2_);
	writeLine__2KoDZXJB4LmoH7PHLGmZ9cg((*formatter).stream, T1_, 1);
	popFrame();
}
static N_INLINE(NI, pluspercent___dgYAo7RfdUVVpvkfKDym8w_2system)(NI x, NI y) {
	NI result;
	nimfr_("+%", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/arithme"
"tics.nim");
	result = (NI)0;
	nimln_(426, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/arithme"
"tics.nim");
	nimln_(430, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/arithme"
"tics.nim");
	result = ((NI) ((NU)((NU64)(((NU) (x))) + (NU64)(((NU) (y))))));
	popFrame();
	return result;
}
static N_INLINE(void, incRef__AT1eRuflKWyTTBdLjEDZbgsystem)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	nimln_(184, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	(*c).refcount = pluspercent___dgYAo7RfdUVVpvkfKDym8w_2system((*c).refcount, ((NI) 8));
	popFrame();
}
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y) {
	NI result;
	nimfr_("-%", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/arithme"
"tics.nim");
	result = (NI)0;
	nimln_(437, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/arithme"
"tics.nim");
	nimln_(441, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/arithme"
"tics.nim");
	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));
	popFrame();
	return result;
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	nimfr_("usrToCell", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(130, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	T1_ = (NI)0;
	T1_ = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (usr)), ((NI) 16));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem)(NI x, NI y) {
	NIM_BOOL result;
	nimfr_("<%", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/compari"
"sons.nim");
	result = (NIM_BOOL)0;
	nimln_(188, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/compari"
"sons.nim");
	nimln_(190, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/compari"
"sons.nim");
	result = ((NU64)(((NU) (x))) < (NU64)(((NU) (y))));
	popFrame();
	return result;
}
static N_INLINE(void, rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_3system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	nimln_(196, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	addZCT__Y66tOYFjgwJ0k4aLz4bc0Q((&gch__IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}
static N_INLINE(void, decRef__AT1eRuflKWyTTBdLjEDZbg_2system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	nimln_(201, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	(*c).refcount = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem((*c).refcount, ((NI) 8));
	nimln_(202, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		nimln_(203, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
		rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_3system(c);
	}
	LA4_: ;
	popFrame();
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	nimln_(239, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem(src);
		incRef__AT1eRuflKWyTTBdLjEDZbgsystem(T5_);
	}
	LA3_: ;
	nimln_(240, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem((*dest));
		decRef__AT1eRuflKWyTTBdLjEDZbg_2system(T10_);
	}
	LA8_: ;
	nimln_(241, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	(*dest) = src;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, testStarted__rOCXlMecpGAbukiW3xEnBA)(tyObject_JUnitOutputFormattercolonObjectType___xT2f3fp9bT7rro9bWvoTGQHw* formatter, NimStringDesc* testName) {
	nimfr_("testStarted", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	nimln_(319, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	asgnRef((void**) (&(*formatter).testErrors), (tySequence__sM4lkSb7zS6F7OVMvW9cffQ*) setLengthSeqV2(&((*formatter).testErrors)->Sup, (&NTI__sM4lkSb7zS6F7OVMvW9cffQ_), ((NI) 0)));
	nimln_(320, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	asgnRef((void**) (&(*formatter).testStackTrace), setLengthStr((*formatter).testStackTrace, ((NI) 0)));
	nimln_(321, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	(*formatter).testStartTime = epochTime__9aodCrWXscOGeNVh2cpuZkw();
	popFrame();
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	nimfr_("nimGCunrefNoCycle", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	nimln_(229, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	T1_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem(p);
	decRef__AT1eRuflKWyTTBdLjEDZbg_2system(T1_);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred__6o9bQoLfclkbDZsrcHh9b69cw)(tyObject_JUnitOutputFormattercolonObjectType___xT2f3fp9bT7rro9bWvoTGQHw* formatter, tySequence__sM4lkSb7zS6F7OVMvW9cffQ* checkpoints, NimStringDesc* stackTrace) {
	nimfr_("failureOccurred", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	nimln_(327, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	add__IGVMsyxhGfOdjDsdcEGOpA((&(*formatter).testErrors), checkpoints->data, (checkpoints ? checkpoints->Sup.len : 0));
	nimln_(328, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	{
		NimStringDesc* T5_;
		if (!(((NI) 0) < (stackTrace ? stackTrace->Sup.len : 0))) goto LA3_;
		nimln_(329, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
		T5_ = (NimStringDesc*)0;
		T5_ = (*formatter).testStackTrace; (*formatter).testStackTrace = copyStringRC1(stackTrace);
		if (T5_) nimGCunrefNoCycle(T5_);
	}
	LA3_: ;
	popFrame();
}
static N_INLINE(NimStringDesc**, X5BX5D___qAX9aHx35KUFY79aX8PJ3xRgsystem)(NimStringDesc** s, NI sLen_0, NI i) {
	NimStringDesc** result;
	NI TM__Um3CQPZ9bILAIolZOsxNIaw_29;
	nimfr_("[]", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system.nim");
	result = (NimStringDesc**)0;
	nimln_(2593, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system.nim");
	if (nimSubInt(sLen_0, i, &TM__Um3CQPZ9bILAIolZOsxNIaw_29)) { raiseOverflow(); };
	if ((NU)((NI)(TM__Um3CQPZ9bILAIolZOsxNIaw_29)) >= (NU)(sLen_0)){ raiseIndexError2((NI)(TM__Um3CQPZ9bILAIolZOsxNIaw_29),sLen_0-1); }
	result = (&s[(NI)(TM__Um3CQPZ9bILAIolZOsxNIaw_29)]);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, testEnded__zLtcJqmjhY5eIZTmyZMGng)(tyObject_JUnitOutputFormattercolonObjectType___xT2f3fp9bT7rro9bWvoTGQHw* formatter, tyObject_TestResult__GEvSVSxdPWWgMGM48ywEYQ testResult) {
	NF time;
	NF T1_;
	NimStringDesc* timeStr;
	tyArray__nHXaesL0DJZHyVS07ARPRA T2_;
	tyArray__Re75IspeoxXy2oCZHwcRrA T3_;
	nimfr_("testEnded", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	nimln_(332, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	T1_ = (NF)0;
	T1_ = epochTime__9aodCrWXscOGeNVh2cpuZkw();
	time = ((NF)(T1_) - (NF)((*formatter).testStartTime));
	nimln_(333, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	timeStr = nsuformatFloat(time, ((tyEnum_FloatFormatMode__pNvEoaqwoxKyoASD11vSgQ) 1), ((NI) 8), 46);
	nimln_(334, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	nimZeroMem((void*)T2_, sizeof(tyArray__nHXaesL0DJZHyVS07ARPRA));
	nimZeroMem((void*)T3_, sizeof(tyArray__Re75IspeoxXy2oCZHwcRrA));
	nimln_(335, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	T3_[0] = xmlEscape__g2YcY9bwywneeGZViUm72Ng(testResult.testName);
	T3_[1] = copyString(timeStr);
	nimln_(334, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	T2_[0] = nsuFormatOpenArray(((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_26), T3_, 2);
	writeLine__2KoDZXJB4LmoH7PHLGmZ9cg((*formatter).stream, T2_, 1);
	nimln_(336, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	switch (testResult.status) {
	case ((tyEnum_TestStatus__W9bTUg9c9a7UlIYkKYmd5uasQ) 0):
	{
	}
	break;
	case ((tyEnum_TestStatus__W9bTUg9c9a7UlIYkKYmd5uasQ) 2):
	{
		nimln_(340, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
		writeLine__2KoDZXJB4LmoH7PHLGmZ9cg((*formatter).stream, TM__Um3CQPZ9bILAIolZOsxNIaw_27, 1);
	}
	break;
	case ((tyEnum_TestStatus__W9bTUg9c9a7UlIYkKYmd5uasQ) 1):
	{
		NimStringDesc* failureMsg;
		NimStringDesc* errs;
		nimln_(342, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
		{
			NIM_BOOL T9_;
			NI T11_;
			NimStringDesc** T14_;
			T9_ = (NIM_BOOL)0;
			T9_ = (((NI) 0) < ((*formatter).testStackTrace ? (*formatter).testStackTrace->Sup.len : 0));
			if (!(T9_)) goto LA10_;
			nimln_(343, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
			T11_ = ((*formatter).testErrors ? (*formatter).testErrors->Sup.len : 0);
			T9_ = (((NI) 0) < T11_);
			LA10_: ;
			if (!T9_) goto LA12_;
			nimln_(344, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
			T14_ = (NimStringDesc**)0;
			T14_ = X5BX5D___qAX9aHx35KUFY79aX8PJ3xRgsystem((*formatter).testErrors->data, ((*formatter).testErrors ? (*formatter).testErrors->Sup.len : 0), ((NI) 1));
			failureMsg = xmlEscape__g2YcY9bwywneeGZViUm72Ng((*T14_));
		}
		goto LA7_;
		LA12_: ;
		{
			NI T16_;
			nimln_(345, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
			T16_ = ((*formatter).testErrors ? (*formatter).testErrors->Sup.len : 0);
			if (!(((NI) 0) < T16_)) goto LA17_;
			nimln_(346, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
			if ((NU)(((NI) 0)) >= (NU)((*formatter).testErrors ? (*formatter).testErrors->Sup.len : 0)){ raiseIndexError2(((NI) 0),((*formatter).testErrors ? (*formatter).testErrors->Sup.len : 0)-1); }
			failureMsg = xmlEscape__g2YcY9bwywneeGZViUm72Ng((*formatter).testErrors->data[((NI) 0)]);
		}
		goto LA7_;
		LA17_: ;
		{
			failureMsg = copyString(((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_30));
		}
		LA7_: ;
		nimln_(349, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
		errs = ((NimStringDesc*) NIM_NIL);
		nimln_(350, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
		{
			NI T22_;
			NI startIdx;
			NI endIdx;
			T22_ = ((*formatter).testErrors ? (*formatter).testErrors->Sup.len : 0);
			if (!(((NI) 1) < T22_)) goto LA23_;
			nimln_(351, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
			{
				if (!(((NI) 0) < ((*formatter).testStackTrace ? (*formatter).testStackTrace->Sup.len : 0))) goto LA27_;
				startIdx = ((NI) 0);
			}
			goto LA25_;
			LA27_: ;
			{
				startIdx = ((NI) 1);
			}
			LA25_: ;
			nimln_(352, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
			{
				NI T34_;
				NI TM__Um3CQPZ9bILAIolZOsxNIaw_31;
				if (!(((NI) 0) < ((*formatter).testStackTrace ? (*formatter).testStackTrace->Sup.len : 0))) goto LA32_;
				nimln_(353, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
				T34_ = ((*formatter).testErrors ? (*formatter).testErrors->Sup.len : 0);
				if (nimSubInt(T34_, ((NI) 2), &TM__Um3CQPZ9bILAIolZOsxNIaw_31)) { raiseOverflow(); };
				endIdx = (NI)(TM__Um3CQPZ9bILAIolZOsxNIaw_31);
			}
			goto LA30_;
			LA32_: ;
			{
				NI T36_;
				NI TM__Um3CQPZ9bILAIolZOsxNIaw_32;
				nimln_(354, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
				T36_ = ((*formatter).testErrors ? (*formatter).testErrors->Sup.len : 0);
				if (nimSubInt(T36_, ((NI) 1), &TM__Um3CQPZ9bILAIolZOsxNIaw_32)) { raiseOverflow(); };
				endIdx = (NI)(TM__Um3CQPZ9bILAIolZOsxNIaw_32);
			}
			LA30_: ;
			{
				NI errIdx;
				NI res;
				errIdx = (NI)0;
				nimln_(77, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs_1.nim");
				res = startIdx;
				{
					nimln_(78, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs_1.nim");
					while (1) {
						NimStringDesc* T44_;
						NI TM__Um3CQPZ9bILAIolZOsxNIaw_33;
						if (!(res <= endIdx)) goto LA39;
						nimln_(356, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
						errIdx = res;
						nimln_(357, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
						{
							if (!(((NI) 0) < (errs ? errs->Sup.len : 0))) goto LA42_;
							nimln_(358, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
							errs = resizeString(errs, 1);
appendString(errs, ((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_7));
						}
						LA42_: ;
						nimln_(359, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
						if ((NU)(errIdx) >= (NU)((*formatter).testErrors ? (*formatter).testErrors->Sup.len : 0)){ raiseIndexError2(errIdx,((*formatter).testErrors ? (*formatter).testErrors->Sup.len : 0)-1); }
						T44_ = (NimStringDesc*)0;
						T44_ = xmlEscape__g2YcY9bwywneeGZViUm72Ng((*formatter).testErrors->data[errIdx]);
						errs = resizeString(errs, (T44_ ? T44_->Sup.len : 0) + 0);
appendString(errs, T44_);
						nimln_(80, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs_1.nim");
						if (nimAddInt(res, ((NI) 1), &TM__Um3CQPZ9bILAIolZOsxNIaw_33)) { raiseOverflow(); };
						res = (NI)(TM__Um3CQPZ9bILAIolZOsxNIaw_33);
					} LA39: ;
				}
			}
		}
		LA23_: ;
		nimln_(361, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
		{
			tyArray__nHXaesL0DJZHyVS07ARPRA T49_;
			tyArray__Re75IspeoxXy2oCZHwcRrA T50_;
			if (!(((NI) 0) < ((*formatter).testStackTrace ? (*formatter).testStackTrace->Sup.len : 0))) goto LA47_;
			nimln_(362, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
			nimZeroMem((void*)T49_, sizeof(tyArray__nHXaesL0DJZHyVS07ARPRA));
			nimZeroMem((void*)T50_, sizeof(tyArray__Re75IspeoxXy2oCZHwcRrA));
			T50_[0] = copyString(failureMsg);
			nimln_(363, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
			T50_[1] = xmlEscape__g2YcY9bwywneeGZViUm72Ng((*formatter).testStackTrace);
			nimln_(362, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
			T49_[0] = nsuFormatOpenArray(((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_34), T50_, 2);
			writeLine__2KoDZXJB4LmoH7PHLGmZ9cg((*formatter).stream, T49_, 1);
			nimln_(364, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
			{
				tyArray__nHXaesL0DJZHyVS07ARPRA T55_;
				if (!(((NI) 0) < (errs ? errs->Sup.len : 0))) goto LA53_;
				nimln_(365, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
				nimZeroMem((void*)T55_, sizeof(tyArray__nHXaesL0DJZHyVS07ARPRA));
				T55_[0] = nsuFormatSingleElem(((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_35), errs);
				writeLine__2KoDZXJB4LmoH7PHLGmZ9cg((*formatter).stream, T55_, 1);
			}
			LA53_: ;
		}
		goto LA45_;
		LA47_: ;
		{
			tyArray__nHXaesL0DJZHyVS07ARPRA T57_;
			tyArray__Re75IspeoxXy2oCZHwcRrA T58_;
			nimln_(367, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
			nimZeroMem((void*)T57_, sizeof(tyArray__nHXaesL0DJZHyVS07ARPRA));
			nimZeroMem((void*)T58_, sizeof(tyArray__Re75IspeoxXy2oCZHwcRrA));
			T58_[0] = copyString(failureMsg);
			T58_[1] = copyString(errs);
			T57_[0] = nsuFormatOpenArray(((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_36), T58_, 2);
			writeLine__2KoDZXJB4LmoH7PHLGmZ9cg((*formatter).stream, T57_, 1);
		}
		LA45_: ;
	}
	break;
	}
	nimln_(370, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	writeLine__2KoDZXJB4LmoH7PHLGmZ9cg((*formatter).stream, TM__Um3CQPZ9bILAIolZOsxNIaw_37, 1);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded__j47Kbeiu3vfl9brbuQ3zGKg)(tyObject_JUnitOutputFormattercolonObjectType___xT2f3fp9bT7rro9bWvoTGQHw* formatter) {
	nimfr_("suiteEnded", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	nimln_(373, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	writeLine__2KoDZXJB4LmoH7PHLGmZ9cg((*formatter).stream, TM__Um3CQPZ9bILAIolZOsxNIaw_39, 1);
	popFrame();
}
static N_INLINE(void, nimGCunrefRC1)(void* p) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	nimfr_("nimGCunrefRC1", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	nimln_(233, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	T1_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem(p);
	decRef__AT1eRuflKWyTTBdLjEDZbg_2system(T1_);
	popFrame();
}
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size) {
	int result;
	result = (int)0;
	result = memcmp(a, b, ((size_t) (size)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__9bGgqEk7RXXl6eqM9c1HdELAsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = nimCmpMem(a, b, size);
	result = (T1_ == ((NI32) 0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NI alen;
	NI blen;
	nimfr_("eqStrings", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/strmant"
"le.nim");
{	result = (NIM_BOOL)0;
	nimln_(24, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/strmant"
"le.nim");
	alen = (a ? a->Sup.len : 0);
	nimln_(25, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/strmant"
"le.nim");
	blen = (b ? b->Sup.len : 0);
	nimln_(26, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/strmant"
"le.nim");
	{
		if (!(alen == blen)) goto LA3_;
		nimln_(27, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/strmant"
"le.nim");
		{
			if (!(alen == ((NI) 0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
		LA7_: ;
		nimln_(28, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/strmant"
"le.nim");
		result = equalMem__9bGgqEk7RXXl6eqM9c1HdELAsystem(((void*) ((&a->data[((NI) 0)]))), ((void*) ((&b->data[((NI) 0)]))), ((NI) (alen)));
		goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef__E6s9cEeVHb9b86T9bNZiuvutQ)(void* p, NI op) {
	tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ* a;
	a = (tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ*)p;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ*, newConsoleOutputFormatter__F1bJtIZPshctBi9bJAr17dQ)(tyEnum_OutputLevel__7UfTrIPsm9cGDPwH9bpwJDww outputLevel, NIM_BOOL colorOutput) {
	tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ* result;
	tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ* T1_;
	nimfr_("newConsoleOutputFormatter", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	result = (tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ*)0;
	nimln_(207, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	T1_ = (tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ*)0;
	T1_ = (tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ*) newObj((&NTI__E6s9cEeVHb9b86T9bNZiuvutQ_), sizeof(tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ));
	(*T1_).Sup.Sup.m_type = (&NTI__pWdV1nDlYJumLrx0ueKJFQ_);
	(*T1_).outputLevel = outputLevel;
	(*T1_).colorOutput = colorOutput;
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ*, defaultConsoleFormatter__EKaes5nvFgq1idJu8Wb7ew)(void) {
	tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ* result;
	NimStringDesc* envOutLvl;
	NIM_BOOL colorOutput;
	tyEnum_OutputLevel__7UfTrIPsm9cGDPwH9bpwJDww outputLevel;
	nimfr_("defaultConsoleFormatter", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	result = (tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ*)0;
	nimln_(216, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	envOutLvl = getEnv__hhED57tMl0Iaa5bOg9cJaig(((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_41), ((NimStringDesc*) NIM_NIL));
	nimln_(217, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	colorOutput = isatty__N9cWRL9bvOiaeIezt6AEzXqw(stdout);
	nimln_(218, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	{
		NIM_BOOL T3_;
		NimStringDesc* colorEnv;
		T3_ = (NIM_BOOL)0;
		T3_ = existsEnv__HhiDHRQxJ349a6FFxO51gqQ(((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_42));
		if (!T3_) goto LA4_;
		nimln_(219, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
		colorEnv = getEnv__hhED57tMl0Iaa5bOg9cJaig(((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_42), ((NimStringDesc*) NIM_NIL));
		nimln_(220, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
		{
			if (!eqStrings(colorEnv, ((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_43))) goto LA8_;
			nimln_(221, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
			colorOutput = NIM_FALSE;
		}
		goto LA6_;
		LA8_: ;
		{
			nimln_(222, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
			if (!eqStrings(colorEnv, ((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_44))) goto LA11_;
			nimln_(223, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
			colorOutput = NIM_TRUE;
		}
		goto LA6_;
		LA11_: ;
		LA6_: ;
	}
	goto LA1_;
	LA4_: ;
	{
		NIM_BOOL T14_;
		nimln_(224, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
		T14_ = (NIM_BOOL)0;
		T14_ = existsEnv__HhiDHRQxJ349a6FFxO51gqQ(((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_45));
		if (!T14_) goto LA15_;
		nimln_(225, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
		colorOutput = NIM_FALSE;
	}
	goto LA1_;
	LA15_: ;
	LA1_: ;
	nimln_(226, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	outputLevel = ((tyEnum_OutputLevel__7UfTrIPsm9cGDPwH9bpwJDww) 0);
	nimln_(227, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	{
		if (!(((NI) 0) < (envOutLvl ? envOutLvl->Sup.len : 0))) goto LA19_;
		{
			tyEnum_OutputLevel__7UfTrIPsm9cGDPwH9bpwJDww opt;
			NI res;
			opt = (tyEnum_OutputLevel__7UfTrIPsm9cGDPwH9bpwJDww)0;
			nimln_(56, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs_1.nim");
			res = ((NI) 0);
			{
				nimln_(57, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs_1.nim");
				while (1) {
					NI TM__Um3CQPZ9bILAIolZOsxNIaw_49;
					if (!(res <= ((NI) 2))) goto LA23;
					nimln_(228, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
					if ((res) < ((tyEnum_OutputLevel__7UfTrIPsm9cGDPwH9bpwJDww) 0) || (res) > ((tyEnum_OutputLevel__7UfTrIPsm9cGDPwH9bpwJDww) 2)){ raiseRangeErrorI(res, ((tyEnum_OutputLevel__7UfTrIPsm9cGDPwH9bpwJDww) 0), ((tyEnum_OutputLevel__7UfTrIPsm9cGDPwH9bpwJDww) 2)); }
					opt = ((tyEnum_OutputLevel__7UfTrIPsm9cGDPwH9bpwJDww) (res));
					nimln_(229, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
					{
						if (!eqStrings(reprEnum((NI)opt, (&NTI__7UfTrIPsm9cGDPwH9bpwJDww_)), envOutLvl)) goto LA26_;
						nimln_(230, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
						outputLevel = opt;
						nimln_(231, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
						goto LA21;
					}
					LA26_: ;
					nimln_(59, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs_1.nim");
					if (nimAddInt(res, ((NI) 1), &TM__Um3CQPZ9bILAIolZOsxNIaw_49)) { raiseOverflow(); };
					res = (NI)(TM__Um3CQPZ9bILAIolZOsxNIaw_49);
				} LA23: ;
			}
		} LA21: ;
	}
	LA19_: ;
	nimln_(232, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	result = newConsoleOutputFormatter__F1bJtIZPshctBi9bJAr17dQ(outputLevel, colorOutput);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, ensureInitialized__PRD4IUUOrtlUkEdtJsvXEg)(void) {
	nimfr_("ensureInitialized", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	nimln_(425, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	{
		NI T3_;
		tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ* T6_;
		T3_ = (formatters__55U7g4zhjHV9bCI6emTgDiA ? formatters__55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
		if (!(T3_ == ((NI) 0))) goto LA4_;
		nimln_(426, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
		if (formatters__55U7g4zhjHV9bCI6emTgDiA) { nimGCunrefRC1(formatters__55U7g4zhjHV9bCI6emTgDiA); formatters__55U7g4zhjHV9bCI6emTgDiA = NIM_NIL; }
		formatters__55U7g4zhjHV9bCI6emTgDiA = (tySequence__shvncLWJZ4vpydQXcCi7CA*) newSeqRC1((&NTI__shvncLWJZ4vpydQXcCi7CA_), 1);
		T6_ = (tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ*)0;
		T6_ = defaultConsoleFormatter__EKaes5nvFgq1idJu8Wb7ew();
		asgnRef((void**) (&formatters__55U7g4zhjHV9bCI6emTgDiA->data[0]), &T6_->Sup);
	}
	LA4_: ;
	nimln_(428, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	{
		if (!!(disabledParamFiltering__9bKIyYrmH1Yr9cIlxYEwYZTg)) goto LA9_;
		{
			NI i;
			NI colontmp_;
			NI res;
			i = (NI)0;
			colontmp_ = (NI)0;
			nimln_(431, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
			colontmp_ = paramCount__LYkRnwMk6UXTCs9c59cPvZsQ();
			nimln_(77, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs_1.nim");
			res = ((NI) 1);
			{
				nimln_(78, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs_1.nim");
				while (1) {
					NimStringDesc* T14_;
					NI TM__Um3CQPZ9bILAIolZOsxNIaw_51;
					if (!(res <= colontmp_)) goto LA13;
					nimln_(431, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
					i = res;
					nimln_(432, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
					T14_ = (NimStringDesc*)0;
					T14_ = paramStr__T0ST6UXXTEqaiXY9akIayng(i);
					incl__TMNSyv4q8yRKlH5e1bO09cA((&testsFilters__Xhcy9bMKRibp73mpqIGgoPA), T14_);
					nimln_(80, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs_1.nim");
					if (nimAddInt(res, ((NI) 1), &TM__Um3CQPZ9bILAIolZOsxNIaw_51)) { raiseOverflow(); };
					res = (NI)(TM__Um3CQPZ9bILAIolZOsxNIaw_51);
				} LA13: ;
			}
		}
	}
	LA9_: ;
	popFrame();
}
static N_INLINE(NIM_BOOL, isFilled__uHIMxs9aGYDEfZheaMnN2sQsets)(NI hcode) {
	NIM_BOOL result;
	nimfr_("isFilled", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/collectio"
"ns/hashcommon.nim");
	result = (NIM_BOOL)0;
	nimln_(27, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/collectio"
"ns/hashcommon.nim");
	result = !((hcode == ((NI) 0)));
	popFrame();
	return result;
}
static N_INLINE(NI, find__31wM5Ui9c8jnrQ5QD4oPxOQsystem)(NIM_CHAR* a, NI aLen_0, NIM_CHAR item) {
	NI result;
	nimfr_("find", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system.nim");
{	result = (NI)0;
	nimln_(1803, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system.nim");
	result = ((NI) 0);
	{
		NIM_CHAR i;
		NI i_2;
		i = (NIM_CHAR)0;
		nimln_(18, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
		i_2 = ((NI) 0);
		{
			nimln_(19, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
			while (1) {
				NI TM__Um3CQPZ9bILAIolZOsxNIaw_53;
				NI TM__Um3CQPZ9bILAIolZOsxNIaw_54;
				if (!(i_2 < aLen_0)) goto LA3;
				nimln_(1804, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system.nim");
				if ((NU)(i_2) >= (NU)(aLen_0)){ raiseIndexError2(i_2,aLen_0-1); }
				i = a[i_2];
				nimln_(1805, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system.nim");
				{
					if (!((NU8)(i) == (NU8)(item))) goto LA6_;
					goto BeforeRet_;
				}
				LA6_: ;
				nimln_(1806, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system.nim");
				if (nimAddInt(result, ((NI) 1), &TM__Um3CQPZ9bILAIolZOsxNIaw_53)) { raiseOverflow(); };
				result = (NI)(TM__Um3CQPZ9bILAIolZOsxNIaw_53);
				nimln_(21, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
				if (nimAddInt(i_2, ((NI) 1), &TM__Um3CQPZ9bILAIolZOsxNIaw_54)) { raiseOverflow(); };
				i_2 = (NI)(TM__Um3CQPZ9bILAIolZOsxNIaw_54);
			} LA3: ;
		}
	}
	nimln_(1807, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system.nim");
	result = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, contains__Pa9a8m0kZYH6LC8N1EcZJdQsystem)(NIM_CHAR* a, NI aLen_0, NIM_CHAR item) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("contains", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system.nim");
{	result = (NIM_BOOL)0;
	nimln_(1821, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system.nim");
	T1_ = (NI)0;
	T1_ = find__31wM5Ui9c8jnrQ5QD4oPxOQsystem(a, aLen_0, item);
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, glob__4YckL5LRAFTQuXhocCy9bwg)(NimStringDesc* matcher, NimStringDesc* filter) {
	NIM_BOOL result;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ* beforeAndAfter;
	NIM_BOOL T19_;
	nimfr_("glob", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
{	result = (NIM_BOOL)0;
	nimln_(377, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	{
		if (!((filter ? filter->Sup.len : 0) == ((NI) 0))) goto LA3_;
		nimln_(378, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(380, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = contains__Pa9a8m0kZYH6LC8N1EcZJdQsystem(filter->data, (filter ? filter->Sup.len : 0), 42);
		if (!!(T7_)) goto LA8_;
		nimln_(381, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
		result = eqStrings(matcher, filter);
		goto BeforeRet_;
	}
	LA8_: ;
	nimln_(383, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	beforeAndAfter = nsuSplitChar(filter, 42, ((NI) 1));
	nimln_(384, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	{
		NI T12_;
		T12_ = (beforeAndAfter ? beforeAndAfter->Sup.len : 0);
		if (!(T12_ == ((NI) 1))) goto LA13_;
		nimln_(386, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
		if ((NU)(((NI) 0)) >= (NU)(beforeAndAfter ? beforeAndAfter->Sup.len : 0)){ raiseIndexError2(((NI) 0),(beforeAndAfter ? beforeAndAfter->Sup.len : 0)-1); }
		result = nsuStartsWith(matcher, beforeAndAfter->data[((NI) 0)]);
		goto BeforeRet_;
	}
	LA13_: ;
	nimln_(388, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	{
		NI TM__Um3CQPZ9bILAIolZOsxNIaw_55;
		if (nimSubInt((filter ? filter->Sup.len : 0), ((NI) 1), &TM__Um3CQPZ9bILAIolZOsxNIaw_55)) { raiseOverflow(); };
		if (!((matcher ? matcher->Sup.len : 0) < (NI)(TM__Um3CQPZ9bILAIolZOsxNIaw_55))) goto LA17_;
		nimln_(389, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA17_: ;
	nimln_(391, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	T19_ = (NIM_BOOL)0;
	if ((NU)(((NI) 0)) >= (NU)(beforeAndAfter ? beforeAndAfter->Sup.len : 0)){ raiseIndexError2(((NI) 0),(beforeAndAfter ? beforeAndAfter->Sup.len : 0)-1); }
	T19_ = nsuStartsWith(matcher, beforeAndAfter->data[((NI) 0)]);
	if (!(T19_)) goto LA20_;
	if ((NU)(((NI) 1)) >= (NU)(beforeAndAfter ? beforeAndAfter->Sup.len : 0)){ raiseIndexError2(((NI) 1),(beforeAndAfter ? beforeAndAfter->Sup.len : 0)-1); }
	T19_ = nsuEndsWith(matcher, beforeAndAfter->data[((NI) 1)]);
	LA20_: ;
	result = T19_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, matchFilter__NqIpE4DyesfWHizCjp6lwg)(NimStringDesc* suiteName, NimStringDesc* testName, NimStringDesc* filter) {
	NIM_BOOL result;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ* suiteAndTestFilters;
	NIM_BOOL T14_;
	nimfr_("matchFilter", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
{	result = (NIM_BOOL)0;
	nimln_(395, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	{
		if (!((filter ? filter->Sup.len : 0) == 0)) goto LA3_;
		nimln_(396, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(397, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	{
		if (!eqStrings(testName, filter)) goto LA7_;
		nimln_(399, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA7_: ;
	nimln_(400, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	suiteAndTestFilters = nsuSplitString(filter, ((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_52), ((NI) 1));
	nimln_(402, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	{
		NI T11_;
		NimStringDesc* testFilter;
		T11_ = (suiteAndTestFilters ? suiteAndTestFilters->Sup.len : 0);
		if (!(T11_ == ((NI) 1))) goto LA12_;
		nimln_(404, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
		if ((NU)(((NI) 0)) >= (NU)(suiteAndTestFilters ? suiteAndTestFilters->Sup.len : 0)){ raiseIndexError2(((NI) 0),(suiteAndTestFilters ? suiteAndTestFilters->Sup.len : 0)-1); }
		testFilter = suiteAndTestFilters->data[((NI) 0)];
		nimln_(405, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
		result = glob__4YckL5LRAFTQuXhocCy9bwg(testName, testFilter);
		goto BeforeRet_;
	}
	LA12_: ;
	nimln_(407, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	T14_ = (NIM_BOOL)0;
	if ((NU)(((NI) 0)) >= (NU)(suiteAndTestFilters ? suiteAndTestFilters->Sup.len : 0)){ raiseIndexError2(((NI) 0),(suiteAndTestFilters ? suiteAndTestFilters->Sup.len : 0)-1); }
	T14_ = glob__4YckL5LRAFTQuXhocCy9bwg(suiteName, suiteAndTestFilters->data[((NI) 0)]);
	if (!(T14_)) goto LA15_;
	nimln_(408, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	if ((NU)(((NI) 1)) >= (NU)(suiteAndTestFilters ? suiteAndTestFilters->Sup.len : 0)){ raiseIndexError2(((NI) 1),(suiteAndTestFilters ? suiteAndTestFilters->Sup.len : 0)-1); }
	T14_ = glob__4YckL5LRAFTQuXhocCy9bwg(testName, suiteAndTestFilters->data[((NI) 1)]);
	LA15_: ;
	result = T14_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, shouldRun__FW0uR9cZPUde1S2WLzSdSZQ)(NimStringDesc* currentSuiteName, NimStringDesc* testName) {
	NIM_BOOL result;
	nimfr_("shouldRun", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
{	result = (NIM_BOOL)0;
	nimln_(415, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	{
		NI T3_;
		T3_ = (NI)0;
		T3_ = len__sVMoSv8jxXZJxl8pFcjd4Q(testsFilters__Xhcy9bMKRibp73mpqIGgoPA);
		if (!(T3_ == ((NI) 0))) goto LA4_;
		nimln_(416, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA4_: ;
	{
		NimStringDesc* f;
		f = (NimStringDesc*)0;
		{
			NI h;
			NI colontmp_;
			NI T8_;
			NI res;
			h = (NI)0;
			colontmp_ = (NI)0;
			nimln_(244, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/collectio"
"ns/sets.nim");
			T8_ = ((testsFilters__Xhcy9bMKRibp73mpqIGgoPA.data ? testsFilters__Xhcy9bMKRibp73mpqIGgoPA.data->Sup.len : 0)-1);
			colontmp_ = T8_;
			nimln_(77, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs_1.nim");
			res = ((NI) 0);
			{
				nimln_(78, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs_1.nim");
				while (1) {
					NI TM__Um3CQPZ9bILAIolZOsxNIaw_56;
					if (!(res <= colontmp_)) goto LA10;
					nimln_(244, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/collectio"
"ns/sets.nim");
					h = res;
					nimln_(245, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/collectio"
"ns/sets.nim");
					{
						NIM_BOOL T13_;
						if ((NU)(h) >= (NU)(testsFilters__Xhcy9bMKRibp73mpqIGgoPA.data ? testsFilters__Xhcy9bMKRibp73mpqIGgoPA.data->Sup.len : 0)){ raiseIndexError2(h,(testsFilters__Xhcy9bMKRibp73mpqIGgoPA.data ? testsFilters__Xhcy9bMKRibp73mpqIGgoPA.data->Sup.len : 0)-1); }
						T13_ = (NIM_BOOL)0;
						T13_ = isFilled__uHIMxs9aGYDEfZheaMnN2sQsets(testsFilters__Xhcy9bMKRibp73mpqIGgoPA.data->data[h].Field0);
						if (!T13_) goto LA14_;
						nimln_(418, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
						if ((NU)(h) >= (NU)(testsFilters__Xhcy9bMKRibp73mpqIGgoPA.data ? testsFilters__Xhcy9bMKRibp73mpqIGgoPA.data->Sup.len : 0)){ raiseIndexError2(h,(testsFilters__Xhcy9bMKRibp73mpqIGgoPA.data ? testsFilters__Xhcy9bMKRibp73mpqIGgoPA.data->Sup.len : 0)-1); }
						f = testsFilters__Xhcy9bMKRibp73mpqIGgoPA.data->data[h].Field1;
						nimln_(419, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
						{
							NIM_BOOL T18_;
							T18_ = (NIM_BOOL)0;
							T18_ = matchFilter__NqIpE4DyesfWHizCjp6lwg(currentSuiteName, testName, f);
							if (!T18_) goto LA19_;
							nimln_(420, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
							result = NIM_TRUE;
							goto BeforeRet_;
						}
						LA19_: ;
					}
					LA14_: ;
					nimln_(80, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs_1.nim");
					if (nimAddInt(res, ((NI) 1), &TM__Um3CQPZ9bILAIolZOsxNIaw_56)) { raiseOverflow(); };
					res = (NI)(TM__Um3CQPZ9bILAIolZOsxNIaw_56);
				} LA10: ;
			}
		}
	}
	nimln_(422, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	result = NIM_FALSE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, checkpoint__GcyHRjPNZ3mrdaHmiIrEXA)(NimStringDesc* msg) {
	NI T1_;
	NimStringDesc* T2_;
	nimfr_("checkpoint", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	nimln_(556, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	asgnRef((void**) (&checkpoints__bq5hLRYOyiTcYy29a9akD9c9bQ), (tySequence__sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV3((TGenericSeq*)(checkpoints__bq5hLRYOyiTcYy29a9akD9c9bQ), (&NTI__sM4lkSb7zS6F7OVMvW9cffQ_)));
	T1_ = checkpoints__bq5hLRYOyiTcYy29a9akD9c9bQ->Sup.len++;
	T2_ = (NimStringDesc*)0;
	T2_ = checkpoints__bq5hLRYOyiTcYy29a9akD9c9bQ->data[T1_]; checkpoints__bq5hLRYOyiTcYy29a9akD9c9bQ->data[T1_] = copyStringRC1(msg);
	if (T2_) nimGCunrefNoCycle(T2_);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, testEnded__ojLWHapKL1jpFxJVjmKgUg)(tyObject_TestResult__GEvSVSxdPWWgMGM48ywEYQ testResult) {
	nimfr_("testEnded", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	{
		tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg** formatter;
		NI i;
		NI L;
		NI T2_;
		formatter = (tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg**)0;
		nimln_(199, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
		i = ((NI) 0);
		nimln_(200, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
		T2_ = (formatters__55U7g4zhjHV9bCI6emTgDiA ? formatters__55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
		L = T2_;
		{
			nimln_(201, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
			while (1) {
				NI TM__Um3CQPZ9bILAIolZOsxNIaw_58;
				if (!(i < L)) goto LA4;
				nimln_(441, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
				if ((NU)(i) >= (NU)(formatters__55U7g4zhjHV9bCI6emTgDiA ? formatters__55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0)){ raiseIndexError2(i,(formatters__55U7g4zhjHV9bCI6emTgDiA ? formatters__55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0)-1); }
				formatter = &formatters__55U7g4zhjHV9bCI6emTgDiA->data[i];
				nimln_(442, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
				testEnded__31pnpDPCXMA6dr4c0S6y9aw((*formatter), testResult);
				nimln_(203, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
				if (nimAddInt(i, ((NI) 1), &TM__Um3CQPZ9bILAIolZOsxNIaw_58)) { raiseOverflow(); };
				i = (NI)(TM__Um3CQPZ9bILAIolZOsxNIaw_58);
				nimln_(204, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs.nim");
				{
					NI T7_;
					T7_ = (formatters__55U7g4zhjHV9bCI6emTgDiA ? formatters__55U7g4zhjHV9bCI6emTgDiA->Sup.len : 0);
					if (!!((T7_ == L))) goto LA8_;
					failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_10));
				}
				LA8_: ;
			} LA4: ;
		}
	}
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_unittestInit000)(void) {
{
	TFrame FR_; FR_.len = 0;

	nimRegisterThreadLocalMarker(TM__Um3CQPZ9bILAIolZOsxNIaw_2);


	nimRegisterThreadLocalMarker(TM__Um3CQPZ9bILAIolZOsxNIaw_3);


	nimRegisterThreadLocalMarker(TM__Um3CQPZ9bILAIolZOsxNIaw_4);

}/* preInitProc end */
{
	nimfr_("unittest", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	nimln_(179, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unittest."
"nim");
	abortOnError__Bte3Uiwc4Q19ago2N4C89cUA = existsEnv__HhiDHRQxJ349a6FFxO51gqQ(((NimStringDesc*) &TM__Um3CQPZ9bILAIolZOsxNIaw_5));
	popFrame();
}
}

N_LIB_PRIVATE N_NIMCALL(void, stdlib_unittestDatInit000)(void) {

/* section: NIM_merge_TYPE_INIT1 */
static TNimNode* TM__Um3CQPZ9bILAIolZOsxNIaw_13_3[3];
NI TM__Um3CQPZ9bILAIolZOsxNIaw_15;
static char* NIM_CONST TM__Um3CQPZ9bILAIolZOsxNIaw_14[3] = {
"OK", 
"FAILED", 
"SKIPPED"};
static TNimNode* TM__Um3CQPZ9bILAIolZOsxNIaw_46_3[3];
NI TM__Um3CQPZ9bILAIolZOsxNIaw_48;
static char* NIM_CONST TM__Um3CQPZ9bILAIolZOsxNIaw_47[3] = {
"PRINT_ALL", 
"PRINT_FAILURES", 
"PRINT_NONE"};
static TNimNode* TM__Um3CQPZ9bILAIolZOsxNIaw_50_4[4];
static TNimNode* TM__Um3CQPZ9bILAIolZOsxNIaw_57_3[3];
static TNimNode* TM__Um3CQPZ9bILAIolZOsxNIaw_59_4[4];
static TNimNode TM__Um3CQPZ9bILAIolZOsxNIaw_0[23];

/* section: NIM_merge_TYPE_INIT3 */
NTI__F9cVkVj1qOwgl27pKTy0srg_.size = sizeof(tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg);
NTI__F9cVkVj1qOwgl27pKTy0srg_.align = NIM_ALIGNOF(tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg);
NTI__F9cVkVj1qOwgl27pKTy0srg_.kind = 17;
NTI__F9cVkVj1qOwgl27pKTy0srg_.base = (&NTI__ytyiCJqK439aF9cIibuRVpAg_);
NTI__F9cVkVj1qOwgl27pKTy0srg_.flags = 1;
TM__Um3CQPZ9bILAIolZOsxNIaw_0[0].len = 0; TM__Um3CQPZ9bILAIolZOsxNIaw_0[0].kind = 2;
NTI__F9cVkVj1qOwgl27pKTy0srg_.node = &TM__Um3CQPZ9bILAIolZOsxNIaw_0[0];
NTI__OdrGHrb6tOjaNa9bJrVe7KA_.size = sizeof(tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg*);
NTI__OdrGHrb6tOjaNa9bJrVe7KA_.align = NIM_ALIGNOF(tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg*);
NTI__OdrGHrb6tOjaNa9bJrVe7KA_.kind = 22;
NTI__OdrGHrb6tOjaNa9bJrVe7KA_.base = (&NTI__F9cVkVj1qOwgl27pKTy0srg_);
NTI__OdrGHrb6tOjaNa9bJrVe7KA_.marker = Marker_tyRef__OdrGHrb6tOjaNa9bJrVe7KA;
NTI__shvncLWJZ4vpydQXcCi7CA_.size = sizeof(tySequence__shvncLWJZ4vpydQXcCi7CA*);
NTI__shvncLWJZ4vpydQXcCi7CA_.align = NIM_ALIGNOF(tySequence__shvncLWJZ4vpydQXcCi7CA*);
NTI__shvncLWJZ4vpydQXcCi7CA_.kind = 24;
NTI__shvncLWJZ4vpydQXcCi7CA_.base = (&NTI__OdrGHrb6tOjaNa9bJrVe7KA_);
NTI__shvncLWJZ4vpydQXcCi7CA_.marker = Marker_tySequence__shvncLWJZ4vpydQXcCi7CA;
NTI__W9bTUg9c9a7UlIYkKYmd5uasQ_.size = sizeof(tyEnum_TestStatus__W9bTUg9c9a7UlIYkKYmd5uasQ);
NTI__W9bTUg9c9a7UlIYkKYmd5uasQ_.align = NIM_ALIGNOF(tyEnum_TestStatus__W9bTUg9c9a7UlIYkKYmd5uasQ);
NTI__W9bTUg9c9a7UlIYkKYmd5uasQ_.kind = 14;
NTI__W9bTUg9c9a7UlIYkKYmd5uasQ_.base = 0;
NTI__W9bTUg9c9a7UlIYkKYmd5uasQ_.flags = 3;
for (TM__Um3CQPZ9bILAIolZOsxNIaw_15 = 0; TM__Um3CQPZ9bILAIolZOsxNIaw_15 < 3; TM__Um3CQPZ9bILAIolZOsxNIaw_15++) {
TM__Um3CQPZ9bILAIolZOsxNIaw_0[TM__Um3CQPZ9bILAIolZOsxNIaw_15+1].kind = 1;
TM__Um3CQPZ9bILAIolZOsxNIaw_0[TM__Um3CQPZ9bILAIolZOsxNIaw_15+1].offset = TM__Um3CQPZ9bILAIolZOsxNIaw_15;
TM__Um3CQPZ9bILAIolZOsxNIaw_0[TM__Um3CQPZ9bILAIolZOsxNIaw_15+1].name = TM__Um3CQPZ9bILAIolZOsxNIaw_14[TM__Um3CQPZ9bILAIolZOsxNIaw_15];
TM__Um3CQPZ9bILAIolZOsxNIaw_13_3[TM__Um3CQPZ9bILAIolZOsxNIaw_15] = &TM__Um3CQPZ9bILAIolZOsxNIaw_0[TM__Um3CQPZ9bILAIolZOsxNIaw_15+1];
}
TM__Um3CQPZ9bILAIolZOsxNIaw_0[4].len = 3; TM__Um3CQPZ9bILAIolZOsxNIaw_0[4].kind = 2; TM__Um3CQPZ9bILAIolZOsxNIaw_0[4].sons = &TM__Um3CQPZ9bILAIolZOsxNIaw_13_3[0];
NTI__W9bTUg9c9a7UlIYkKYmd5uasQ_.node = &TM__Um3CQPZ9bILAIolZOsxNIaw_0[4];
NTI__7UfTrIPsm9cGDPwH9bpwJDww_.size = sizeof(tyEnum_OutputLevel__7UfTrIPsm9cGDPwH9bpwJDww);
NTI__7UfTrIPsm9cGDPwH9bpwJDww_.align = NIM_ALIGNOF(tyEnum_OutputLevel__7UfTrIPsm9cGDPwH9bpwJDww);
NTI__7UfTrIPsm9cGDPwH9bpwJDww_.kind = 14;
NTI__7UfTrIPsm9cGDPwH9bpwJDww_.base = 0;
NTI__7UfTrIPsm9cGDPwH9bpwJDww_.flags = 3;
for (TM__Um3CQPZ9bILAIolZOsxNIaw_48 = 0; TM__Um3CQPZ9bILAIolZOsxNIaw_48 < 3; TM__Um3CQPZ9bILAIolZOsxNIaw_48++) {
TM__Um3CQPZ9bILAIolZOsxNIaw_0[TM__Um3CQPZ9bILAIolZOsxNIaw_48+5].kind = 1;
TM__Um3CQPZ9bILAIolZOsxNIaw_0[TM__Um3CQPZ9bILAIolZOsxNIaw_48+5].offset = TM__Um3CQPZ9bILAIolZOsxNIaw_48;
TM__Um3CQPZ9bILAIolZOsxNIaw_0[TM__Um3CQPZ9bILAIolZOsxNIaw_48+5].name = TM__Um3CQPZ9bILAIolZOsxNIaw_47[TM__Um3CQPZ9bILAIolZOsxNIaw_48];
TM__Um3CQPZ9bILAIolZOsxNIaw_46_3[TM__Um3CQPZ9bILAIolZOsxNIaw_48] = &TM__Um3CQPZ9bILAIolZOsxNIaw_0[TM__Um3CQPZ9bILAIolZOsxNIaw_48+5];
}
TM__Um3CQPZ9bILAIolZOsxNIaw_0[8].len = 3; TM__Um3CQPZ9bILAIolZOsxNIaw_0[8].kind = 2; TM__Um3CQPZ9bILAIolZOsxNIaw_0[8].sons = &TM__Um3CQPZ9bILAIolZOsxNIaw_46_3[0];
NTI__7UfTrIPsm9cGDPwH9bpwJDww_.node = &TM__Um3CQPZ9bILAIolZOsxNIaw_0[8];
NTI__pWdV1nDlYJumLrx0ueKJFQ_.size = sizeof(tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ);
NTI__pWdV1nDlYJumLrx0ueKJFQ_.align = NIM_ALIGNOF(tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ);
NTI__pWdV1nDlYJumLrx0ueKJFQ_.kind = 17;
NTI__pWdV1nDlYJumLrx0ueKJFQ_.base = (&NTI__F9cVkVj1qOwgl27pKTy0srg_);
NTI__pWdV1nDlYJumLrx0ueKJFQ_.flags = 1;
TM__Um3CQPZ9bILAIolZOsxNIaw_50_4[0] = &TM__Um3CQPZ9bILAIolZOsxNIaw_0[10];
TM__Um3CQPZ9bILAIolZOsxNIaw_0[10].kind = 1;
TM__Um3CQPZ9bILAIolZOsxNIaw_0[10].offset = offsetof(tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ, colorOutput);
TM__Um3CQPZ9bILAIolZOsxNIaw_0[10].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__Um3CQPZ9bILAIolZOsxNIaw_0[10].name = "colorOutput";
TM__Um3CQPZ9bILAIolZOsxNIaw_50_4[1] = &TM__Um3CQPZ9bILAIolZOsxNIaw_0[11];
TM__Um3CQPZ9bILAIolZOsxNIaw_0[11].kind = 1;
TM__Um3CQPZ9bILAIolZOsxNIaw_0[11].offset = offsetof(tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ, outputLevel);
TM__Um3CQPZ9bILAIolZOsxNIaw_0[11].typ = (&NTI__7UfTrIPsm9cGDPwH9bpwJDww_);
TM__Um3CQPZ9bILAIolZOsxNIaw_0[11].name = "outputLevel";
TM__Um3CQPZ9bILAIolZOsxNIaw_50_4[2] = &TM__Um3CQPZ9bILAIolZOsxNIaw_0[12];
TM__Um3CQPZ9bILAIolZOsxNIaw_0[12].kind = 1;
TM__Um3CQPZ9bILAIolZOsxNIaw_0[12].offset = offsetof(tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ, isInSuite);
TM__Um3CQPZ9bILAIolZOsxNIaw_0[12].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__Um3CQPZ9bILAIolZOsxNIaw_0[12].name = "isInSuite";
TM__Um3CQPZ9bILAIolZOsxNIaw_50_4[3] = &TM__Um3CQPZ9bILAIolZOsxNIaw_0[13];
TM__Um3CQPZ9bILAIolZOsxNIaw_0[13].kind = 1;
TM__Um3CQPZ9bILAIolZOsxNIaw_0[13].offset = offsetof(tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ, isInTest);
TM__Um3CQPZ9bILAIolZOsxNIaw_0[13].typ = (&NTI__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__Um3CQPZ9bILAIolZOsxNIaw_0[13].name = "isInTest";
TM__Um3CQPZ9bILAIolZOsxNIaw_0[9].len = 4; TM__Um3CQPZ9bILAIolZOsxNIaw_0[9].kind = 2; TM__Um3CQPZ9bILAIolZOsxNIaw_0[9].sons = &TM__Um3CQPZ9bILAIolZOsxNIaw_50_4[0];
NTI__pWdV1nDlYJumLrx0ueKJFQ_.node = &TM__Um3CQPZ9bILAIolZOsxNIaw_0[9];
NTI__E6s9cEeVHb9b86T9bNZiuvutQ_.size = sizeof(tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ*);
NTI__E6s9cEeVHb9b86T9bNZiuvutQ_.align = NIM_ALIGNOF(tyObject_ConsoleOutputFormattercolonObjectType___pWdV1nDlYJumLrx0ueKJFQ*);
NTI__E6s9cEeVHb9b86T9bNZiuvutQ_.kind = 22;
NTI__E6s9cEeVHb9b86T9bNZiuvutQ_.base = (&NTI__pWdV1nDlYJumLrx0ueKJFQ_);
NTI__E6s9cEeVHb9b86T9bNZiuvutQ_.marker = Marker_tyRef__E6s9cEeVHb9b86T9bNZiuvutQ;
NTI__GEvSVSxdPWWgMGM48ywEYQ_.size = sizeof(tyObject_TestResult__GEvSVSxdPWWgMGM48ywEYQ);
NTI__GEvSVSxdPWWgMGM48ywEYQ_.align = NIM_ALIGNOF(tyObject_TestResult__GEvSVSxdPWWgMGM48ywEYQ);
NTI__GEvSVSxdPWWgMGM48ywEYQ_.kind = 18;
NTI__GEvSVSxdPWWgMGM48ywEYQ_.base = 0;
NTI__GEvSVSxdPWWgMGM48ywEYQ_.flags = 2;
TM__Um3CQPZ9bILAIolZOsxNIaw_57_3[0] = &TM__Um3CQPZ9bILAIolZOsxNIaw_0[15];
TM__Um3CQPZ9bILAIolZOsxNIaw_0[15].kind = 1;
TM__Um3CQPZ9bILAIolZOsxNIaw_0[15].offset = offsetof(tyObject_TestResult__GEvSVSxdPWWgMGM48ywEYQ, suiteName);
TM__Um3CQPZ9bILAIolZOsxNIaw_0[15].typ = (&NTI__77mFvmsOLKik79ci2hXkHEg_);
TM__Um3CQPZ9bILAIolZOsxNIaw_0[15].name = "suiteName";
TM__Um3CQPZ9bILAIolZOsxNIaw_57_3[1] = &TM__Um3CQPZ9bILAIolZOsxNIaw_0[16];
TM__Um3CQPZ9bILAIolZOsxNIaw_0[16].kind = 1;
TM__Um3CQPZ9bILAIolZOsxNIaw_0[16].offset = offsetof(tyObject_TestResult__GEvSVSxdPWWgMGM48ywEYQ, testName);
TM__Um3CQPZ9bILAIolZOsxNIaw_0[16].typ = (&NTI__77mFvmsOLKik79ci2hXkHEg_);
TM__Um3CQPZ9bILAIolZOsxNIaw_0[16].name = "testName";
TM__Um3CQPZ9bILAIolZOsxNIaw_57_3[2] = &TM__Um3CQPZ9bILAIolZOsxNIaw_0[17];
TM__Um3CQPZ9bILAIolZOsxNIaw_0[17].kind = 1;
TM__Um3CQPZ9bILAIolZOsxNIaw_0[17].offset = offsetof(tyObject_TestResult__GEvSVSxdPWWgMGM48ywEYQ, status);
TM__Um3CQPZ9bILAIolZOsxNIaw_0[17].typ = (&NTI__W9bTUg9c9a7UlIYkKYmd5uasQ_);
TM__Um3CQPZ9bILAIolZOsxNIaw_0[17].name = "status";
TM__Um3CQPZ9bILAIolZOsxNIaw_0[14].len = 3; TM__Um3CQPZ9bILAIolZOsxNIaw_0[14].kind = 2; TM__Um3CQPZ9bILAIolZOsxNIaw_0[14].sons = &TM__Um3CQPZ9bILAIolZOsxNIaw_57_3[0];
NTI__GEvSVSxdPWWgMGM48ywEYQ_.node = &TM__Um3CQPZ9bILAIolZOsxNIaw_0[14];
NTI__xT2f3fp9bT7rro9bWvoTGQHw_.size = sizeof(tyObject_JUnitOutputFormattercolonObjectType___xT2f3fp9bT7rro9bWvoTGQHw);
NTI__xT2f3fp9bT7rro9bWvoTGQHw_.align = NIM_ALIGNOF(tyObject_JUnitOutputFormattercolonObjectType___xT2f3fp9bT7rro9bWvoTGQHw);
NTI__xT2f3fp9bT7rro9bWvoTGQHw_.kind = 17;
NTI__xT2f3fp9bT7rro9bWvoTGQHw_.base = (&NTI__F9cVkVj1qOwgl27pKTy0srg_);
TM__Um3CQPZ9bILAIolZOsxNIaw_59_4[0] = &TM__Um3CQPZ9bILAIolZOsxNIaw_0[19];
TM__Um3CQPZ9bILAIolZOsxNIaw_0[19].kind = 1;
TM__Um3CQPZ9bILAIolZOsxNIaw_0[19].offset = offsetof(tyObject_JUnitOutputFormattercolonObjectType___xT2f3fp9bT7rro9bWvoTGQHw, stream);
TM__Um3CQPZ9bILAIolZOsxNIaw_0[19].typ = (&NTI__1G0jiQbe7KwD5ADza5AZaw_);
TM__Um3CQPZ9bILAIolZOsxNIaw_0[19].name = "stream";
TM__Um3CQPZ9bILAIolZOsxNIaw_59_4[1] = &TM__Um3CQPZ9bILAIolZOsxNIaw_0[20];
TM__Um3CQPZ9bILAIolZOsxNIaw_0[20].kind = 1;
TM__Um3CQPZ9bILAIolZOsxNIaw_0[20].offset = offsetof(tyObject_JUnitOutputFormattercolonObjectType___xT2f3fp9bT7rro9bWvoTGQHw, testErrors);
TM__Um3CQPZ9bILAIolZOsxNIaw_0[20].typ = (&NTI__sM4lkSb7zS6F7OVMvW9cffQ_);
TM__Um3CQPZ9bILAIolZOsxNIaw_0[20].name = "testErrors";
TM__Um3CQPZ9bILAIolZOsxNIaw_59_4[2] = &TM__Um3CQPZ9bILAIolZOsxNIaw_0[21];
TM__Um3CQPZ9bILAIolZOsxNIaw_0[21].kind = 1;
TM__Um3CQPZ9bILAIolZOsxNIaw_0[21].offset = offsetof(tyObject_JUnitOutputFormattercolonObjectType___xT2f3fp9bT7rro9bWvoTGQHw, testStartTime);
TM__Um3CQPZ9bILAIolZOsxNIaw_0[21].typ = (&NTI__w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM__Um3CQPZ9bILAIolZOsxNIaw_0[21].name = "testStartTime";
TM__Um3CQPZ9bILAIolZOsxNIaw_59_4[3] = &TM__Um3CQPZ9bILAIolZOsxNIaw_0[22];
TM__Um3CQPZ9bILAIolZOsxNIaw_0[22].kind = 1;
TM__Um3CQPZ9bILAIolZOsxNIaw_0[22].offset = offsetof(tyObject_JUnitOutputFormattercolonObjectType___xT2f3fp9bT7rro9bWvoTGQHw, testStackTrace);
TM__Um3CQPZ9bILAIolZOsxNIaw_0[22].typ = (&NTI__77mFvmsOLKik79ci2hXkHEg_);
TM__Um3CQPZ9bILAIolZOsxNIaw_0[22].name = "testStackTrace";
TM__Um3CQPZ9bILAIolZOsxNIaw_0[18].len = 4; TM__Um3CQPZ9bILAIolZOsxNIaw_0[18].kind = 2; TM__Um3CQPZ9bILAIolZOsxNIaw_0[18].sons = &TM__Um3CQPZ9bILAIolZOsxNIaw_59_4[0];
NTI__xT2f3fp9bT7rro9bWvoTGQHw_.node = &TM__Um3CQPZ9bILAIolZOsxNIaw_0[18];
}

