/* Generated by Nim Compiler v1.4.4 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3   -I/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib -I/home/kyohei/nim/nmark/tests -o /home/kyohei/nim/nmark/nimcache/tests/testRegular.nim_0d61f8370cad1d412f80b84d143e1257/stdlib_unicode.nim.c.o /home/kyohei/nim/nmark/nimcache/tests/testRegular.nim_0d61f8370cad1d412f80b84d143e1257/stdlib_unicode.nim.c */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;

/* section: NIM_merge_TYPES */
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};

/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NI, runeLenAt__WMpE2MYPWM1HlcK1wXx02Q)(NimStringDesc* s, NI i);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
static N_INLINE(NIM_BOOL, lteqpercent___x8ObPz55IkLprSyPyqBSRAsystem)(NI32 x, NI32 y);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);

/* section: NIM_merge_VARS */
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;

/* section: NIM_merge_PROCS */
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
N_LIB_PRIVATE N_NIMCALL(NI, nucruneLen)(NimStringDesc* s) {
	NI result;
	NI i;
	nimfr_("runeLen", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
	result = (NI)0;
	nimln_(42, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
	result = ((NI) 0);
	nimln_(43, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
	i = ((NI) 0);
	{
		nimln_(44, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		while (1) {
			NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_9;
			if (!(i < (s ? s->Sup.len : 0))) goto LA2;
			nimln_(45, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
			{
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_2;
				if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
				if (!((NU64)(((NU) (((NU8)(s->data[i]))))) <= (NU64)(((NU) 127)))) goto LA5_;
				if (nimAddInt(i, ((NI) 1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_2)) { raiseOverflow(); };
				i = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_2);
			}
			goto LA3_;
			LA5_: ;
			{
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_3;
				nimln_(46, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
				if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
				if (!((NU)((NU64)(((NU) (((NU8)(s->data[i]))))) >> (NU64)(((NI) 5))) == ((NU) 6))) goto LA8_;
				if (nimAddInt(i, ((NI) 2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_3)) { raiseOverflow(); };
				i = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_3);
			}
			goto LA3_;
			LA8_: ;
			{
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_4;
				nimln_(47, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
				if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
				if (!((NU)((NU64)(((NU) (((NU8)(s->data[i]))))) >> (NU64)(((NI) 4))) == ((NU) 14))) goto LA11_;
				if (nimAddInt(i, ((NI) 3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_4)) { raiseOverflow(); };
				i = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_4);
			}
			goto LA3_;
			LA11_: ;
			{
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_5;
				nimln_(48, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
				if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
				if (!((NU)((NU64)(((NU) (((NU8)(s->data[i]))))) >> (NU64)(((NI) 3))) == ((NU) 30))) goto LA14_;
				if (nimAddInt(i, ((NI) 4), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_5)) { raiseOverflow(); };
				i = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_5);
			}
			goto LA3_;
			LA14_: ;
			{
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_6;
				nimln_(49, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
				if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
				if (!((NU)((NU64)(((NU) (((NU8)(s->data[i]))))) >> (NU64)(((NI) 2))) == ((NU) 62))) goto LA17_;
				if (nimAddInt(i, ((NI) 5), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_6)) { raiseOverflow(); };
				i = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_6);
			}
			goto LA3_;
			LA17_: ;
			{
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_7;
				nimln_(50, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
				if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
				if (!((NU)((NU64)(((NU) (((NU8)(s->data[i]))))) >> (NU64)(((NI) 1))) == ((NU) 126))) goto LA20_;
				if (nimAddInt(i, ((NI) 6), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_7)) { raiseOverflow(); };
				i = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_7);
			}
			goto LA3_;
			LA20_: ;
			{
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_8;
				nimln_(51, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
				if (nimAddInt(i, ((NI) 1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_8)) { raiseOverflow(); };
				i = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_8);
			}
			LA3_: ;
			nimln_(52, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
			if (nimAddInt(result, ((NI) 1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_9)) { raiseOverflow(); };
			result = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_9);
		} LA2: ;
	}
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, runeLenAt__WMpE2MYPWM1HlcK1wXx02Q)(NimStringDesc* s, NI i) {
	NI result;
	nimfr_("runeLenAt", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
	result = (NI)0;
	nimln_(64, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
	{
		if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
		if (!((NU64)(((NU) (((NU8)(s->data[i]))))) <= (NU64)(((NU) 127)))) goto LA3_;
		result = ((NI) 1);
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(65, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
		if (!((NU)((NU64)(((NU) (((NU8)(s->data[i]))))) >> (NU64)(((NI) 5))) == ((NU) 6))) goto LA6_;
		result = ((NI) 2);
	}
	goto LA1_;
	LA6_: ;
	{
		nimln_(66, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
		if (!((NU)((NU64)(((NU) (((NU8)(s->data[i]))))) >> (NU64)(((NI) 4))) == ((NU) 14))) goto LA9_;
		result = ((NI) 3);
	}
	goto LA1_;
	LA9_: ;
	{
		nimln_(67, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
		if (!((NU)((NU64)(((NU) (((NU8)(s->data[i]))))) >> (NU64)(((NI) 3))) == ((NU) 30))) goto LA12_;
		result = ((NI) 4);
	}
	goto LA1_;
	LA12_: ;
	{
		nimln_(68, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
		if (!((NU)((NU64)(((NU) (((NU8)(s->data[i]))))) >> (NU64)(((NI) 2))) == ((NU) 62))) goto LA15_;
		result = ((NI) 5);
	}
	goto LA1_;
	LA15_: ;
	{
		nimln_(69, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
		if (!((NU)((NU64)(((NU) (((NU8)(s->data[i]))))) >> (NU64)(((NI) 1))) == ((NU) 126))) goto LA18_;
		result = ((NI) 6);
	}
	goto LA1_;
	LA18_: ;
	{
		nimln_(70, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		result = ((NI) 1);
	}
	LA1_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, runeOffset__EnrqtYM0boqQqeAIRc9bdmA)(NimStringDesc* s, NI pos, NI start) {
	NI result;
	NI i;
	NI o;
	nimfr_("runeOffset", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
{	result = (NI)0;
	nimln_(321, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
	i = ((NI) 0);
	nimln_(322, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
	o = start;
	{
		nimln_(323, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		while (1) {
			NI T3_;
			NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_10;
			NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_11;
			if (!(i < ((NI) (pos)))) goto LA2;
			nimln_(324, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
			T3_ = (NI)0;
			T3_ = runeLenAt__WMpE2MYPWM1HlcK1wXx02Q(s, o);
			if ((T3_) < ((NI) 0) || (T3_) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(T3_, ((NI) 0), ((NI) IL64(9223372036854775807))); }
			if (nimAddInt(o, ((NI) (T3_)), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_10)) { raiseOverflow(); };
			if (TM__e1RUVS0Bw7xmj9cnDPXLJMQ_10 < 0 || TM__e1RUVS0Bw7xmj9cnDPXLJMQ_10 > IL64(9223372036854775807)){ raiseOverflow(); }
			o = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_10);
			nimln_(325, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
			{
				if (!((s ? s->Sup.len : 0) <= ((NI) (o)))) goto LA6_;
				nimln_(326, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
				result = ((NI) -1);
				goto BeforeRet_;
			}
			LA6_: ;
			nimln_(327, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
			if (nimAddInt(i, ((NI) 1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_11)) { raiseOverflow(); };
			i = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_11);
		} LA2: ;
	}
	nimln_(328, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
	result = ((NI) (o));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, validateUtf8__gZHDHaRdP4jROav7Hun29aA)(NimStringDesc* s) {
	NI result;
	NI i;
	NI L;
	nimfr_("validateUtf8", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
{	result = (NI)0;
	nimln_(174, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
	i = ((NI) 0);
	nimln_(175, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
	L = (s ? s->Sup.len : 0);
	{
		nimln_(176, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		while (1) {
			if (!(i < L)) goto LA2;
			nimln_(177, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
			{
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_12;
				if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
				if (!((NU64)(((NU) (((NU8)(s->data[i]))))) <= (NU64)(((NU) 127)))) goto LA5_;
				nimln_(178, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
				if (nimAddInt(i, ((NI) 1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_12)) { raiseOverflow(); };
				i = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_12);
			}
			goto LA3_;
			LA5_: ;
			{
				nimln_(179, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
				if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
				if (!((NU)((NU64)(((NU) (((NU8)(s->data[i]))))) >> (NU64)(((NI) 5))) == ((NU) 6))) goto LA8_;
				nimln_(180, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
				{
					if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
					if (!((NU64)(((NU) (((NU8)(s->data[i]))))) < (NU64)(((NU) 194)))) goto LA12_;
					result = i;
					goto BeforeRet_;
				}
				LA12_: ;
				nimln_(181, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
				{
					NIM_BOOL T16_;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_13;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_14;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_15;
					T16_ = (NIM_BOOL)0;
					if (nimAddInt(i, ((NI) 1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_13)) { raiseOverflow(); };
					T16_ = ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_13) < L);
					if (!(T16_)) goto LA17_;
					if (nimAddInt(i, ((NI) 1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_14)) { raiseOverflow(); };
					if ((NU)((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_14)) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_14),(s ? s->Sup.len : 0)-1); }
					T16_ = ((NU)((NU64)(((NU) (((NU8)(s->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_14)]))))) >> (NU64)(((NI) 6))) == ((NU) 2));
					LA17_: ;
					if (!T16_) goto LA18_;
					if (nimAddInt(i, ((NI) 2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_15)) { raiseOverflow(); };
					i = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_15);
				}
				goto LA14_;
				LA18_: ;
				{
					nimln_(182, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
					result = i;
					goto BeforeRet_;
				}
				LA14_: ;
			}
			goto LA3_;
			LA8_: ;
			{
				nimln_(183, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
				if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
				if (!((NU)((NU64)(((NU) (((NU8)(s->data[i]))))) >> (NU64)(((NI) 4))) == ((NU) 14))) goto LA22_;
				nimln_(184, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
				{
					NIM_BOOL T26_;
					NIM_BOOL T27_;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_16;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_17;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_18;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_19;
					T26_ = (NIM_BOOL)0;
					T27_ = (NIM_BOOL)0;
					if (nimAddInt(i, ((NI) 2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_16)) { raiseOverflow(); };
					T27_ = ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_16) < L);
					if (!(T27_)) goto LA28_;
					if (nimAddInt(i, ((NI) 1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_17)) { raiseOverflow(); };
					if ((NU)((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_17)) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_17),(s ? s->Sup.len : 0)-1); }
					T27_ = ((NU)((NU64)(((NU) (((NU8)(s->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_17)]))))) >> (NU64)(((NI) 6))) == ((NU) 2));
					LA28_: ;
					T26_ = T27_;
					if (!(T26_)) goto LA29_;
					if (nimAddInt(i, ((NI) 2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_18)) { raiseOverflow(); };
					if ((NU)((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_18)) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_18),(s ? s->Sup.len : 0)-1); }
					T26_ = ((NU)((NU64)(((NU) (((NU8)(s->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_18)]))))) >> (NU64)(((NI) 6))) == ((NU) 2));
					LA29_: ;
					if (!T26_) goto LA30_;
					nimln_(185, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
					if (nimAddInt(i, ((NI) 3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_19)) { raiseOverflow(); };
					i = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_19);
				}
				goto LA24_;
				LA30_: ;
				{
					nimln_(186, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
					result = i;
					goto BeforeRet_;
				}
				LA24_: ;
			}
			goto LA3_;
			LA22_: ;
			{
				nimln_(187, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
				if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
				if (!((NU)((NU64)(((NU) (((NU8)(s->data[i]))))) >> (NU64)(((NI) 3))) == ((NU) 30))) goto LA34_;
				nimln_(188, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
				{
					NIM_BOOL T38_;
					NIM_BOOL T39_;
					NIM_BOOL T40_;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_20;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_21;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_22;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_23;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_24;
					nimln_(189, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
					T38_ = (NIM_BOOL)0;
					nimln_(188, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
					T39_ = (NIM_BOOL)0;
					T40_ = (NIM_BOOL)0;
					if (nimAddInt(i, ((NI) 3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_20)) { raiseOverflow(); };
					T40_ = ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_20) < L);
					if (!(T40_)) goto LA41_;
					if (nimAddInt(i, ((NI) 1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_21)) { raiseOverflow(); };
					if ((NU)((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_21)) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_21),(s ? s->Sup.len : 0)-1); }
					T40_ = ((NU)((NU64)(((NU) (((NU8)(s->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_21)]))))) >> (NU64)(((NI) 6))) == ((NU) 2));
					LA41_: ;
					T39_ = T40_;
					if (!(T39_)) goto LA42_;
					nimln_(189, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
					if (nimAddInt(i, ((NI) 2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_22)) { raiseOverflow(); };
					if ((NU)((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_22)) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_22),(s ? s->Sup.len : 0)-1); }
					T39_ = ((NU)((NU64)(((NU) (((NU8)(s->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_22)]))))) >> (NU64)(((NI) 6))) == ((NU) 2));
					LA42_: ;
					T38_ = T39_;
					if (!(T38_)) goto LA43_;
					nimln_(190, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
					if (nimAddInt(i, ((NI) 3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_23)) { raiseOverflow(); };
					if ((NU)((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_23)) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_23),(s ? s->Sup.len : 0)-1); }
					T38_ = ((NU)((NU64)(((NU) (((NU8)(s->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_23)]))))) >> (NU64)(((NI) 6))) == ((NU) 2));
					LA43_: ;
					if (!T38_) goto LA44_;
					nimln_(191, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
					if (nimAddInt(i, ((NI) 4), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_24)) { raiseOverflow(); };
					i = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_24);
				}
				goto LA36_;
				LA44_: ;
				{
					nimln_(192, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
					result = i;
					goto BeforeRet_;
				}
				LA36_: ;
			}
			goto LA3_;
			LA34_: ;
			{
				nimln_(194, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
				result = i;
				goto BeforeRet_;
			}
			LA3_: ;
		} LA2: ;
	}
	nimln_(195, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
	result = ((NI) -1);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, lteqpercent___x8ObPz55IkLprSyPyqBSRAsystem)(NI32 x, NI32 y) {
	NIM_BOOL result;
	nimfr_("<=%", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/compari"
"sons.nim");
	result = (NIM_BOOL)0;
	nimln_(184, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/compari"
"sons.nim");
	result = ((NU32)(((NU32) (x))) <= (NU32)(((NU32) (y))));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nuctoUTF8)(NI32 c) {
	NimStringDesc* result;
	NI32 iX60gensym49_;
	nimfr_("toUTF8", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
	result = (NimStringDesc*)0;
	nimln_(266, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
	result = ((NimStringDesc*) NIM_NIL);
	nimln_(211, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
	iX60gensym49_ = c;
	nimln_(267, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
	{
		NIM_BOOL T3_;
		nimln_(212, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		T3_ = (NIM_BOOL)0;
		T3_ = lteqpercent___x8ObPz55IkLprSyPyqBSRAsystem(iX60gensym49_, ((NI32) 127));
		if (!T3_) goto LA4_;
		nimln_(213, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		result = setLengthStr(result, ((NI) 1));
		if ((NU)(((NI) 0)) >= (NU)(result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 0),(result ? result->Sup.len : 0)-1); }
		nimln_(214, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		if ((iX60gensym49_) < ((NI) 0) || (iX60gensym49_) > ((NI) 255)){ raiseRangeErrorI(iX60gensym49_, ((NI) 0), ((NI) 255)); }
		result->data[((NI) 0)] = ((NIM_CHAR) (((NI) (iX60gensym49_))));
	}
	goto LA1_;
	LA4_: ;
	{
		NIM_BOOL T7_;
		nimln_(216, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		T7_ = (NIM_BOOL)0;
		T7_ = lteqpercent___x8ObPz55IkLprSyPyqBSRAsystem(iX60gensym49_, ((NI32) 2047));
		if (!T7_) goto LA8_;
		nimln_(217, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		result = setLengthStr(result, ((NI) 2));
		if ((NU)(((NI) 0)) >= (NU)(result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 0),(result ? result->Sup.len : 0)-1); }
		nimln_(218, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		if (((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) | ((NI32) 192))) < ((NI) 0) || ((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) | ((NI32) 192))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) | ((NI32) 192)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) | ((NI32) 192))))));
		if ((NU)(((NI) 1)) >= (NU)(result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 1),(result ? result->Sup.len : 0)-1); }
		nimln_(219, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		if (((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))))));
	}
	goto LA1_;
	LA8_: ;
	{
		NIM_BOOL T11_;
		nimln_(221, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		T11_ = (NIM_BOOL)0;
		T11_ = lteqpercent___x8ObPz55IkLprSyPyqBSRAsystem(iX60gensym49_, ((NI32) 65535));
		if (!T11_) goto LA12_;
		nimln_(222, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		result = setLengthStr(result, ((NI) 3));
		if ((NU)(((NI) 0)) >= (NU)(result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 0),(result ? result->Sup.len : 0)-1); }
		nimln_(223, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		if (((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) | ((NI32) 224))) < ((NI) 0) || ((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) | ((NI32) 224))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) | ((NI32) 224)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) | ((NI32) 224))))));
		if ((NU)(((NI) 1)) >= (NU)(result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 1),(result ? result->Sup.len : 0)-1); }
		nimln_(224, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))))));
		if ((NU)(((NI) 2)) >= (NU)(result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 2),(result ? result->Sup.len : 0)-1); }
		nimln_(225, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		if (((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 2)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))))));
	}
	goto LA1_;
	LA12_: ;
	{
		NIM_BOOL T15_;
		nimln_(227, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		T15_ = (NIM_BOOL)0;
		T15_ = lteqpercent___x8ObPz55IkLprSyPyqBSRAsystem(iX60gensym49_, ((NI32) 2097151));
		if (!T15_) goto LA16_;
		nimln_(228, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		result = setLengthStr(result, ((NI) 4));
		if ((NU)(((NI) 0)) >= (NU)(result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 0),(result ? result->Sup.len : 0)-1); }
		nimln_(229, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		if (((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 18))) | ((NI32) 240))) < ((NI) 0) || ((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 18))) | ((NI32) 240))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 18))) | ((NI32) 240)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 18))) | ((NI32) 240))))));
		if ((NU)(((NI) 1)) >= (NU)(result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 1),(result ? result->Sup.len : 0)-1); }
		nimln_(230, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128))))));
		if ((NU)(((NI) 2)) >= (NU)(result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 2),(result ? result->Sup.len : 0)-1); }
		nimln_(231, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 2)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))))));
		if ((NU)(((NI) 3)) >= (NU)(result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 3),(result ? result->Sup.len : 0)-1); }
		nimln_(232, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		if (((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 3)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))))));
	}
	goto LA1_;
	LA16_: ;
	{
		NIM_BOOL T19_;
		nimln_(234, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		T19_ = (NIM_BOOL)0;
		T19_ = lteqpercent___x8ObPz55IkLprSyPyqBSRAsystem(iX60gensym49_, ((NI32) 67108863));
		if (!T19_) goto LA20_;
		nimln_(235, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		result = setLengthStr(result, ((NI) 5));
		if ((NU)(((NI) 0)) >= (NU)(result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 0),(result ? result->Sup.len : 0)-1); }
		nimln_(236, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		if (((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 24))) | ((NI32) 248))) < ((NI) 0) || ((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 24))) | ((NI32) 248))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 24))) | ((NI32) 248)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 24))) | ((NI32) 248))))));
		if ((NU)(((NI) 1)) >= (NU)(result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 1),(result ? result->Sup.len : 0)-1); }
		nimln_(237, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 18))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 18))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 18))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 18))) & ((NI32) 63)) | ((NI32) 128))))));
		if ((NU)(((NI) 2)) >= (NU)(result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 2),(result ? result->Sup.len : 0)-1); }
		nimln_(238, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 2)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128))))));
		if ((NU)(((NI) 3)) >= (NU)(result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 3),(result ? result->Sup.len : 0)-1); }
		nimln_(239, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 3)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))))));
		if ((NU)(((NI) 4)) >= (NU)(result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 4),(result ? result->Sup.len : 0)-1); }
		nimln_(240, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		if (((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 4)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))))));
	}
	goto LA1_;
	LA20_: ;
	{
		NIM_BOOL T23_;
		nimln_(242, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		T23_ = (NIM_BOOL)0;
		T23_ = lteqpercent___x8ObPz55IkLprSyPyqBSRAsystem(iX60gensym49_, ((NI32) 2147483647));
		if (!T23_) goto LA24_;
		nimln_(243, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		result = setLengthStr(result, ((NI) 6));
		if ((NU)(((NI) 0)) >= (NU)(result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 0),(result ? result->Sup.len : 0)-1); }
		nimln_(244, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		if (((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 30))) | ((NI32) 252))) < ((NI) 0) || ((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 30))) | ((NI32) 252))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 30))) | ((NI32) 252)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 30))) | ((NI32) 252))))));
		if ((NU)(((NI) 1)) >= (NU)(result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 1),(result ? result->Sup.len : 0)-1); }
		nimln_(245, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 24))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 24))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 24))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 24))) & ((NI32) 63)) | ((NI32) 128))))));
		if ((NU)(((NI) 2)) >= (NU)(result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 2),(result ? result->Sup.len : 0)-1); }
		nimln_(246, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 18))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 18))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 18))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 2)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 18))) & ((NI32) 63)) | ((NI32) 128))))));
		if ((NU)(((NI) 3)) >= (NU)(result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 3),(result ? result->Sup.len : 0)-1); }
		nimln_(247, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 3)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128))))));
		if ((NU)(((NI) 4)) >= (NU)(result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 4),(result ? result->Sup.len : 0)-1); }
		nimln_(248, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 4)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))))));
		if ((NU)(((NI) 5)) >= (NU)(result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 5),(result ? result->Sup.len : 0)-1); }
		nimln_(249, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/unicode.n"
"im");
		if (((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 5)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))))));
	}
	goto LA1_;
	LA24_: ;
	{
	}
	LA1_: ;
	popFrame();
	return result;
}
