/* Generated by Nim Compiler v1.4.4 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3   -I/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib -I/home/kyohei/nim/nmark/tests -o /home/kyohei/nim/nmark/nimcache/tests/testRegular.nim_0d61f8370cad1d412f80b84d143e1257/stdlib_algorithm.nim.c.o /home/kyohei/nim/nmark/nimcache/tests/testRegular.nim_0d61f8370cad1d412f80b84d143e1257/stdlib_algorithm.nim.c */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct tySequence__9aO0X1q9a9ctialmZT59bS3GxQ tySequence__9aO0X1q9a9ctialmZT59bS3GxQ;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_DelimObj__mUX4WOvugW9bAC9aSQLXPB6A tyObject_DelimObj__mUX4WOvugW9bAC9aSQLXPB6A;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct TNimType TNimType;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct TNimNode TNimNode;

/* section: NIM_merge_TYPES */
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_DelimPotential__goAqDIFOP48rbMJV9biZLfA;
struct tyObject_DelimObj__mUX4WOvugW9bAC9aSQLXPB6A {
NI position;
NimStringDesc* typeDelim;
NI numDelim;
NIM_BOOL isActive;
tyEnum_DelimPotential__goAqDIFOP48rbMJV9biZLfA potential;
};
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef struct {
N_NIMCALL_PTR(NI, ClP_0) (tyObject_DelimObj__mUX4WOvugW9bAC9aSQLXPB6A* x, tyObject_DelimObj__mUX4WOvugW9bAC9aSQLXPB6A* y, void* ClE_0);
void* ClE_0;
} tyProc__QeYGU9cWqp4ttFUXI1J6VXg;
typedef NU8 tyEnum_SortOrder__8iBc6wlNqBa9cju9cUAhUAxA;
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CLOSURE_PTR(NI, TM__JdC9c6SaUkvO1XjYuWP1JWQ_15) (tyObject_DelimObj__mUX4WOvugW9bAC9aSQLXPB6A* x, tyObject_DelimObj__mUX4WOvugW9bAC9aSQLXPB6A* y);
typedef N_CLOSURE_PTR(NI, TM__JdC9c6SaUkvO1XjYuWP1JWQ_19) (tyObject_DelimObj__mUX4WOvugW9bAC9aSQLXPB6A* x, tyObject_DelimObj__mUX4WOvugW9bAC9aSQLXPB6A* y);

/* section: NIM_merge_SEQ_TYPES */
struct tySequence__9aO0X1q9a9ctialmZT59bS3GxQ {
  TGenericSeq Sup;
  tyObject_DelimObj__mUX4WOvugW9bAC9aSQLXPB6A* data[SEQ_DECL_SIZE];
};

/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NIMCALL(tySequence__9aO0X1q9a9ctialmZT59bS3GxQ*, reversed__wjePxK0YF13tnAIM6IDD0g)(tyObject_DelimObj__mUX4WOvugW9bAC9aSQLXPB6A** a, NI aLen_0, NI first, NI last);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(tySequence__9aO0X1q9a9ctialmZT59bS3GxQ*, newSeq__MuQ0n7YmI9cvCyU4Yw6C4Kw)(NI len);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__AT1eRuflKWyTTBdLjEDZbgsystem)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___dgYAo7RfdUVVpvkfKDym8w_2system)(NI x, NI y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem)(void* usr);
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y);
static N_INLINE(void, decRef__AT1eRuflKWyTTBdLjEDZbg_2system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NIM_BOOL, ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_3system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__Y66tOYFjgwJ0k4aLz4bc0Q)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, sort__aOks1JeiOjki9azGB4yRdKw)(tyObject_DelimObj__mUX4WOvugW9bAC9aSQLXPB6A** a, NI aLen_0, tyProc__QeYGU9cWqp4ttFUXI1J6VXg cmp, tyEnum_SortOrder__8iBc6wlNqBa9cju9cUAhUAxA order);
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NIM_BOOL, nimDivInt)(NI a, NI b, NI* res);
N_LIB_PRIVATE N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(void, merge__H2rgPYglkLpPhMPmzHPOww)(tyObject_DelimObj__mUX4WOvugW9bAC9aSQLXPB6A** a, NI aLen_0, tyObject_DelimObj__mUX4WOvugW9bAC9aSQLXPB6A** b, NI bLen_0, NI lo, NI m, NI hi, tyProc__QeYGU9cWqp4ttFUXI1J6VXg cmp, tyEnum_SortOrder__8iBc6wlNqBa9cju9cUAhUAxA order);
static N_INLINE(NI, star___kgZDSIMT2vrZak9bMmeL40walgorithm)(NI x, tyEnum_SortOrder__8iBc6wlNqBa9cju9cUAhUAxA order);
N_LIB_PRIVATE N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);

/* section: NIM_merge_DATA */
STRING_LITERAL(TM__JdC9c6SaUkvO1XjYuWP1JWQ_3, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim(148, 10) `\012first - 1 <= last` ", 98);
extern TNimType NTI__9aO0X1q9a9ctialmZT59bS3GxQ_;
STRING_LITERAL(TM__JdC9c6SaUkvO1XjYuWP1JWQ_16, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim(343, 10) `j <= m` ", 86);

/* section: NIM_merge_VARS */
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__IcYaEuuWivYAS86vFMTS3Q;

/* section: NIM_merge_PROCS */
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
static N_INLINE(NI, pluspercent___dgYAo7RfdUVVpvkfKDym8w_2system)(NI x, NI y) {
	NI result;
	nimfr_("+%", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/arithme"
"tics.nim");
	result = (NI)0;
	nimln_(426, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/arithme"
"tics.nim");
	nimln_(430, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/arithme"
"tics.nim");
	result = ((NI) ((NU)((NU64)(((NU) (x))) + (NU64)(((NU) (y))))));
	popFrame();
	return result;
}
static N_INLINE(void, incRef__AT1eRuflKWyTTBdLjEDZbgsystem)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	nimln_(184, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	(*c).refcount = pluspercent___dgYAo7RfdUVVpvkfKDym8w_2system((*c).refcount, ((NI) 8));
	popFrame();
}
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y) {
	NI result;
	nimfr_("-%", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/arithme"
"tics.nim");
	result = (NI)0;
	nimln_(437, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/arithme"
"tics.nim");
	nimln_(441, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/arithme"
"tics.nim");
	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));
	popFrame();
	return result;
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	nimfr_("usrToCell", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(130, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	T1_ = (NI)0;
	T1_ = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (usr)), ((NI) 16));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem)(NI x, NI y) {
	NIM_BOOL result;
	nimfr_("<%", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/compari"
"sons.nim");
	result = (NIM_BOOL)0;
	nimln_(188, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/compari"
"sons.nim");
	nimln_(190, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/compari"
"sons.nim");
	result = ((NU64)(((NU) (x))) < (NU64)(((NU) (y))));
	popFrame();
	return result;
}
static N_INLINE(void, rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_3system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	nimln_(196, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	addZCT__Y66tOYFjgwJ0k4aLz4bc0Q((&gch__IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}
static N_INLINE(void, decRef__AT1eRuflKWyTTBdLjEDZbg_2system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	nimln_(201, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	(*c).refcount = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem((*c).refcount, ((NI) 8));
	nimln_(202, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___hPljn3JCDQ00ua1R07X9bxQsystem((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		nimln_(203, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
		rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_3system(c);
	}
	LA4_: ;
	popFrame();
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	nimln_(239, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem(src);
		incRef__AT1eRuflKWyTTBdLjEDZbgsystem(T5_);
	}
	LA3_: ;
	nimln_(240, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem((*dest));
		decRef__AT1eRuflKWyTTBdLjEDZbg_2system(T10_);
	}
	LA8_: ;
	nimln_(241, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/gc.nim");
	(*dest) = src;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tySequence__9aO0X1q9a9ctialmZT59bS3GxQ*, reversed__wjePxK0YF13tnAIM6IDD0g)(tyObject_DelimObj__mUX4WOvugW9bAC9aSQLXPB6A** a, NI aLen_0, NI first, NI last) {
	tySequence__9aO0X1q9a9ctialmZT59bS3GxQ* result;
	NI i;
	NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_4;
	NI x;
	NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_5;
	nimfr_("reversed", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
	result = (tySequence__9aO0X1q9a9ctialmZT59bS3GxQ*)0;
	nimln_(148, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
	{
		NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_2;
		if (nimSubInt(((NI) (first)), ((NI) 1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_2)) { raiseOverflow(); };
		if (!!(((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_2) <= last))) goto LA3_;
		failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(((NimStringDesc*) &TM__JdC9c6SaUkvO1XjYuWP1JWQ_3));
	}
	LA3_: ;
	nimln_(149, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
	if (nimSubInt(last, ((NI) (first)), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_4)) { raiseOverflow(); };
	i = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_4);
	nimln_(150, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
	x = ((NI) (first));
	nimln_(151, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
	if (nimAddInt(i, ((NI) 1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_5)) { raiseOverflow(); };
	if (((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_5)) < ((NI) 0) || ((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_5)) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_5), ((NI) 0), ((NI) IL64(9223372036854775807))); }
	result = newSeq__MuQ0n7YmI9cvCyU4Yw6C4Kw(((NI) ((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_5))));
	{
		nimln_(152, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
		while (1) {
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_6;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_7;
			if (!(((NI) 0) <= i)) goto LA6;
			if ((NU)(i) >= (NU)(result ? result->Sup.len : 0)){ raiseIndexError2(i,(result ? result->Sup.len : 0)-1); }
			nimln_(153, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
			if ((NU)(x) >= (NU)(aLen_0)){ raiseIndexError2(x,aLen_0-1); }
			asgnRef((void**) (&result->data[i]), a[x]);
			nimln_(154, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
			if (nimSubInt(i, ((NI) 1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_6)) { raiseOverflow(); };
			i = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_6);
			nimln_(155, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
			if (nimAddInt(x, ((NI) 1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_7)) { raiseOverflow(); };
			x = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_7);
		} LA6: ;
	}
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__9aO0X1q9a9ctialmZT59bS3GxQ*, reversed__3S4UfVVfHINFyL4770cdAg)(tyObject_DelimObj__mUX4WOvugW9bAC9aSQLXPB6A** a, NI aLen_0) {
	tySequence__9aO0X1q9a9ctialmZT59bS3GxQ* result;
	nimfr_("reversed", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
	result = (tySequence__9aO0X1q9a9ctialmZT59bS3GxQ*)0;
	nimln_(158, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
	nimln_(168, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
	result = reversed__wjePxK0YF13tnAIM6IDD0g(a, aLen_0, ((NI) 0), (aLen_0-1));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDivInt)(NI a, NI b, NI* res) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T3_)) goto LA4_;
		T3_ = (b == ((NI) -1));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = NIM_TRUE;
	}
	goto LA1_;
	LA5_: ;
	{
		(*res) = (NI)(a / b);
	}
	LA1_: ;
	return result;
}
static N_INLINE(NI, star___kgZDSIMT2vrZak9bMmeL40walgorithm)(NI x, tyEnum_SortOrder__8iBc6wlNqBa9cju9cUAhUAxA order) {
	NI result;
	NI y;
	NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_12;
	NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_13;
	nimfr_("*", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
	result = (NI)0;
	nimln_(66, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
	if (nimSubInt(order, ((NI) 1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_12)) { raiseOverflow(); };
	y = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_12);
	nimln_(67, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
	if (nimSubInt((NI)(x ^ y), y, &TM__JdC9c6SaUkvO1XjYuWP1JWQ_13)) { raiseOverflow(); };
	result = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_13);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, merge__H2rgPYglkLpPhMPmzHPOww)(tyObject_DelimObj__mUX4WOvugW9bAC9aSQLXPB6A** a, NI aLen_0, tyObject_DelimObj__mUX4WOvugW9bAC9aSQLXPB6A** b, NI bLen_0, NI lo, NI m, NI hi, tyProc__QeYGU9cWqp4ttFUXI1J6VXg cmp, tyEnum_SortOrder__8iBc6wlNqBa9cju9cUAhUAxA order) {
	NI j;
	NI bb;
	NI i;
	NI k;
	nimfr_("merge", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
{	nimln_(340, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
	{
		NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_14;
		NI T3_;
		NI T4_;
		if ((NU)(m) >= (NU)(aLen_0)){ raiseIndexError2(m,aLen_0-1); }
		if (nimAddInt(m, ((NI) 1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_14)) { raiseOverflow(); };
		if ((NU)((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_14)) >= (NU)(aLen_0)){ raiseIndexError2((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_14),aLen_0-1); }
		T3_ = (NI)0;
		T3_ = cmp.ClE_0? cmp.ClP_0(a[m], a[(NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_14)], cmp.ClE_0):((TM__JdC9c6SaUkvO1XjYuWP1JWQ_15)(cmp.ClP_0))(a[m], a[(NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_14)]);
		T4_ = (NI)0;
		T4_ = star___kgZDSIMT2vrZak9bMmeL40walgorithm(T3_, order);
		if (!(T4_ <= ((NI) 0))) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	nimln_(341, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
	j = lo;
	nimln_(343, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
	{
		if (!!((j <= m))) goto LA9_;
		failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(((NimStringDesc*) &TM__JdC9c6SaUkvO1XjYuWP1JWQ_16));
	}
	LA9_: ;
	nimln_(345, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
	bb = ((NI) 0);
	{
		nimln_(346, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
		while (1) {
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_17;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_18;
			if (!(j <= m)) goto LA12;
			if ((NU)(bb) >= (NU)(bLen_0)){ raiseIndexError2(bb,bLen_0-1); }
			nimln_(347, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
			if ((NU)(j) >= (NU)(aLen_0)){ raiseIndexError2(j,aLen_0-1); }
			unsureAsgnRef((void**) (&b[bb]), a[j]);
			nimln_(348, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
			if (nimAddInt(bb, ((NI) 1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_17)) { raiseOverflow(); };
			bb = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_17);
			nimln_(349, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
			if (nimAddInt(j, ((NI) 1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_18)) { raiseOverflow(); };
			j = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_18);
		} LA12: ;
	}
	nimln_(353, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
	i = ((NI) 0);
	nimln_(354, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
	k = lo;
	{
		nimln_(356, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
		while (1) {
			NIM_BOOL T15_;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_22;
			T15_ = (NIM_BOOL)0;
			T15_ = (k < j);
			if (!(T15_)) goto LA16_;
			T15_ = (j <= hi);
			LA16_: ;
			if (!T15_) goto LA14;
			nimln_(357, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
			{
				NI T19_;
				NI T20_;
				NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_20;
				if ((NU)(i) >= (NU)(bLen_0)){ raiseIndexError2(i,bLen_0-1); }
				if ((NU)(j) >= (NU)(aLen_0)){ raiseIndexError2(j,aLen_0-1); }
				T19_ = (NI)0;
				T19_ = cmp.ClE_0? cmp.ClP_0(b[i], a[j], cmp.ClE_0):((TM__JdC9c6SaUkvO1XjYuWP1JWQ_19)(cmp.ClP_0))(b[i], a[j]);
				T20_ = (NI)0;
				T20_ = star___kgZDSIMT2vrZak9bMmeL40walgorithm(T19_, order);
				if (!(T20_ <= ((NI) 0))) goto LA21_;
				if ((NU)(k) >= (NU)(aLen_0)){ raiseIndexError2(k,aLen_0-1); }
				nimln_(358, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
				if ((NU)(i) >= (NU)(bLen_0)){ raiseIndexError2(i,bLen_0-1); }
				unsureAsgnRef((void**) (&a[k]), b[i]);
				nimln_(359, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
				if (nimAddInt(i, ((NI) 1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_20)) { raiseOverflow(); };
				i = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_20);
			}
			goto LA17_;
			LA21_: ;
			{
				NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_21;
				if ((NU)(k) >= (NU)(aLen_0)){ raiseIndexError2(k,aLen_0-1); }
				nimln_(361, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
				if ((NU)(j) >= (NU)(aLen_0)){ raiseIndexError2(j,aLen_0-1); }
				unsureAsgnRef((void**) (&a[k]), a[j]);
				nimln_(362, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
				if (nimAddInt(j, ((NI) 1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_21)) { raiseOverflow(); };
				j = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_21);
			}
			LA17_: ;
			nimln_(363, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
			if (nimAddInt(k, ((NI) 1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_22)) { raiseOverflow(); };
			k = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_22);
		} LA14: ;
	}
	{
		nimln_(366, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
		while (1) {
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_23;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_24;
			if (!(k < j)) goto LA25;
			if ((NU)(k) >= (NU)(aLen_0)){ raiseIndexError2(k,aLen_0-1); }
			nimln_(367, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
			if ((NU)(i) >= (NU)(bLen_0)){ raiseIndexError2(i,bLen_0-1); }
			unsureAsgnRef((void**) (&a[k]), b[i]);
			nimln_(368, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
			if (nimAddInt(k, ((NI) 1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_23)) { raiseOverflow(); };
			k = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_23);
			nimln_(369, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
			if (nimAddInt(i, ((NI) 1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_24)) { raiseOverflow(); };
			i = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_24);
		} LA25: ;
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, sort__aOks1JeiOjki9azGB4yRdKw)(tyObject_DelimObj__mUX4WOvugW9bAC9aSQLXPB6A** a, NI aLen_0, tyProc__QeYGU9cWqp4ttFUXI1J6VXg cmp, tyEnum_SortOrder__8iBc6wlNqBa9cju9cUAhUAxA order) {
	NI n;
	tySequence__9aO0X1q9a9ctialmZT59bS3GxQ* b;
	NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_9;
	NI s;
	nimfr_("sort", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
	nimln_(415, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
	n = aLen_0;
	b = (tySequence__9aO0X1q9a9ctialmZT59bS3GxQ*)0;
	nimln_(417, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
	if (((NI) 2) == 0){ raiseDivByZero(); }
	if (nimDivInt(n, ((NI) 2), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_9)) { raiseOverflow(); };
	if (((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_9)) < ((NI) 0) || ((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_9)) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_9), ((NI) 0), ((NI) IL64(9223372036854775807))); }
	b = (tySequence__9aO0X1q9a9ctialmZT59bS3GxQ*) newSeq((&NTI__9aO0X1q9a9ctialmZT59bS3GxQ_), ((NI) ((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_9))));
	nimln_(418, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
	s = ((NI) 1);
	{
		nimln_(419, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
		while (1) {
			NI m;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_10;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_11;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_30;
			if (!(s < n)) goto LA2;
			nimln_(420, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
			if (nimSubInt(n, ((NI) 1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_10)) { raiseOverflow(); };
			if (nimSubInt((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_10), s, &TM__JdC9c6SaUkvO1XjYuWP1JWQ_11)) { raiseOverflow(); };
			m = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_11);
			{
				nimln_(421, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
				while (1) {
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_25;
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_26;
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_27;
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_28;
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_29;
					if (!(((NI) 0) <= m)) goto LA4;
					nimln_(422, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
					if (nimSubInt(m, s, &TM__JdC9c6SaUkvO1XjYuWP1JWQ_25)) { raiseOverflow(); };
					if (nimAddInt((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_25), ((NI) 1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_26)) { raiseOverflow(); };
					if (nimAddInt(m, s, &TM__JdC9c6SaUkvO1XjYuWP1JWQ_27)) { raiseOverflow(); };
					merge__H2rgPYglkLpPhMPmzHPOww(a, aLen_0, b->data, (b ? b->Sup.len : 0), (((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_26) >= ((NI) 0)) ? (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_26) : ((NI) 0)), m, (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_27), cmp, order);
					nimln_(423, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
					if (nimMulInt(s, ((NI) 2), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_28)) { raiseOverflow(); };
					if (nimSubInt(m, (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_28), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_29)) { raiseOverflow(); };
					m = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_29);
				} LA4: ;
			}
			nimln_(424, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
			if (nimMulInt(s, ((NI) 2), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_30)) { raiseOverflow(); };
			s = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_30);
		} LA2: ;
	}
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tySequence__9aO0X1q9a9ctialmZT59bS3GxQ*, sorted__gfjAjJw809cNS09a3J5OhuwQ)(tyObject_DelimObj__mUX4WOvugW9bAC9aSQLXPB6A** a, NI aLen_0, tyProc__QeYGU9cWqp4ttFUXI1J6VXg cmp, tyEnum_SortOrder__8iBc6wlNqBa9cju9cUAhUAxA order) {
	tySequence__9aO0X1q9a9ctialmZT59bS3GxQ* result;
	nimfr_("sorted", "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
	result = (tySequence__9aO0X1q9a9ctialmZT59bS3GxQ*)0;
	nimln_(453, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
	if ((aLen_0) < ((NI) 0) || (aLen_0) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(aLen_0, ((NI) 0), ((NI) IL64(9223372036854775807))); }
	result = newSeq__MuQ0n7YmI9cvCyU4Yw6C4Kw(((NI) (aLen_0)));
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(454, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
		colontmp_ = (aLen_0-1);
		nimln_(77, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs_1.nim");
		res = ((NI) 0);
		{
			nimln_(78, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs_1.nim");
			while (1) {
				NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_8;
				if (!(res <= colontmp_)) goto LA3;
				nimln_(454, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
				i = res;
				if ((NU)(i) >= (NU)(result ? result->Sup.len : 0)){ raiseIndexError2(i,(result ? result->Sup.len : 0)-1); }
				nimln_(455, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
				if ((NU)(i) >= (NU)(aLen_0)){ raiseIndexError2(i,aLen_0-1); }
				asgnRef((void**) (&result->data[i]), a[i]);
				nimln_(80, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/system/iterato"
"rs_1.nim");
				if (nimAddInt(res, ((NI) 1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_8)) { raiseOverflow(); };
				res = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_8);
			} LA3: ;
		}
	}
	nimln_(456, "/home/kyohei/.choosenim/toolchains/nim-1.4.4/lib/pure/algorithm"
".nim");
	sort__aOks1JeiOjki9azGB4yRdKw(result->data, (result ? result->Sup.len : 0), cmp, order);
	popFrame();
	return result;
}
